Repository Rust-GCC/gccrs, pull requests merged in 2021-09, with the labels that each got.

#655 Generic Qualified Paths
  gcc/rust/Make-lang.in
  gcc/rust/ast/rust-item.h
  gcc/rust/ast/rust-path.h
  gcc/rust/backend/rust-compile-context.h
  gcc/rust/hir/rust-ast-lower-type.h
  gcc/rust/hir/rust-ast-lower.cc
  gcc/rust/hir/tree/rust-hir-path.h
  gcc/rust/resolve/rust-ast-resolve-type.h
  gcc/rust/resolve/rust-ast-resolve.cc
  gcc/rust/typecheck/rust-hir-path-probe.h
  gcc/rust/typecheck/rust-hir-trait-ref.h
  gcc/rust/typecheck/rust-hir-trait-resolve.cc
  gcc/rust/typecheck/rust-hir-trait-resolve.h
  gcc/rust/typecheck/rust-hir-type-check-implitem.h
  gcc/rust/typecheck/rust-hir-type-check-item.h
  gcc/rust/typecheck/rust-hir-type-check-path.cc
  gcc/rust/typecheck/rust-hir-type-check-type.cc
  gcc/rust/typecheck/rust-hir-type-check-type.h
  gcc/rust/typecheck/rust-hir-type-check.cc
  gcc/rust/typecheck/rust-hir-type-check.h
  gcc/rust/typecheck/rust-substitution-mapper.h
  gcc/rust/typecheck/rust-tyctx.cc
  gcc/rust/typecheck/rust-tyty-coercion.h
  gcc/rust/typecheck/rust-tyty-rules.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust/compile/torture/traits12.rs
  gcc/testsuite/rust/compile/torture/traits13.rs
  gcc/testsuite/rust/compile/torture/traits14.rs
  gcc/testsuite/rust/compile/torture/traits15.rs
Labels: enhancement

#657 Add building blocks for enum support
  gcc/rust/ast/rust-ast-full-test.cc
  gcc/rust/ast/rust-item.h
  gcc/rust/hir/rust-ast-lower-enumitem.h
  gcc/rust/hir/rust-ast-lower-item.h
  gcc/rust/hir/rust-ast-lower-stmt.h
  gcc/rust/hir/rust-ast-lower.cc
  gcc/rust/hir/rust-ast-lower.h
  gcc/rust/hir/tree/rust-hir-full-test.cc
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/resolve/rust-ast-resolve-item.h
  gcc/rust/resolve/rust-ast-resolve-stmt.h
  gcc/rust/resolve/rust-ast-resolve-toplevel.h
  gcc/testsuite/rust/compile/bad_pub_enumitems.rs
  gcc/testsuite/rust/compile/bad_stmt_enums.rs
  gcc/testsuite/rust/compile/bad_toplevel_enums.rs
  gcc/testsuite/rust/compile/torture/tuple_enum_variants.rs
Labels: enhancement

#656 Add mangling switch
  gcc/rust/Make-lang.in
  gcc/rust/backend/rust-compile-context.h
  gcc/rust/backend/rust-compile.cc
  gcc/rust/backend/rust-mangle.cc
  gcc/rust/backend/rust-mangle.h
  gcc/rust/lang.opt
  gcc/rust/rust-session-manager.cc
Labels: enhancement

#659 Initial intrinsics builtin block
  gcc/rust/Make-lang.in
  gcc/rust/backend/rust-compile-base.h
  gcc/rust/backend/rust-compile-extern.h
  gcc/rust/backend/rust-compile-intrinsic.cc
  gcc/rust/backend/rust-compile-intrinsic.h
  gcc/rust/rust-backend.h
  gcc/rust/rust-gcc.cc
  gcc/rust/typecheck/rust-hir-type-check-implitem.h
  gcc/rust/typecheck/rust-hir-type-check-stmt.h
  gcc/rust/typecheck/rust-hir-type-check-toplevel.h
  gcc/rust/typecheck/rust-hir-type-check.cc
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust/compile/torture/intrinsics-1.rs
Labels: GCC, Rust Integrations

#662 Add building blocks for super-traits
  gcc/rust/hir/rust-ast-lower-item.h
  gcc/rust/resolve/rust-ast-resolve-item.h
  gcc/rust/typecheck/rust-hir-trait-resolve.h
Labels: enhancement

#666 Super Traits Support
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/typecheck/rust-hir-trait-resolve.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust/compile/torture/traits16.rs
  gcc/testsuite/rust/compile/torture/traits17.rs
  gcc/testsuite/rust/execute/torture/trait3.rs
Labels: enhancement

#669 Fix bug with monomorphizing of trait items
  gcc/rust/backend/rust-compile-context.h
  gcc/rust/backend/rust-compile-extern.h
  gcc/rust/backend/rust-compile-implitem.h
  gcc/rust/backend/rust-compile-item.h
Labels: bug

#671 Support indirection for struct and tuple field access
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/lint/rust-lint-marklive.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/testsuite/rust/compile/torture/autoderef1.rs
Labels: enhancement

#672 Initial autoderef support for method calls
  gcc/rust/backend/rust-compile.cc
  gcc/rust/hir/rust-ast-lower.cc
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/typecheck/rust-autoderef.h
  gcc/rust/typecheck/rust-hir-dot-operator.h
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check-implitem.h
  gcc/rust/typecheck/rust-hir-type-check.cc
  gcc/rust/typecheck/rust-hir-type-check.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust/compile/method1.rs
  gcc/testsuite/rust/execute/torture/method1.rs
Labels: enhancement

#673 Allow GCC to decide to inline functions is possible
  gcc/rust/rust-backend.h
  gcc/rust/rust-gcc.cc
Labels: enhancement

#674 Add test case to close out generics bug
  gcc/testsuite/rust/compile/torture/issue-368.rs
Labels: bug

#679 Fix bug when calling method from generic reciever type-bound
  gcc/rust/backend/rust-compile.cc
  gcc/testsuite/rust/execute/torture/trait4.rs
Labels: bug

#680 Building blocks for TraitObject Types
  gcc/rust/ast/rust-type.h
  gcc/rust/hir/rust-ast-lower-type.h
  gcc/rust/hir/rust-ast-lower.cc
  gcc/rust/hir/tree/rust-hir-type.h
  gcc/rust/resolve/rust-ast-resolve-type.h
  gcc/rust/resolve/rust-ast-resolve.cc
Labels: enhancement

#684 Initial Dynamic dispatch support
  gcc/rust/backend/rust-compile-base.h
  gcc/rust/backend/rust-compile-context.h
  gcc/rust/backend/rust-compile-stmt.h
  gcc/rust/backend/rust-compile-tyty.h
  gcc/rust/backend/rust-compile.cc
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/typecheck/rust-hir-const-fold.h
  gcc/rust/typecheck/rust-hir-trait-ref.h
  gcc/rust/typecheck/rust-hir-trait-resolve.cc
  gcc/rust/typecheck/rust-hir-trait-resolve.h
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check-implitem.h
  gcc/rust/typecheck/rust-hir-type-check-type.cc
  gcc/rust/typecheck/rust-hir-type-check-type.h
  gcc/rust/typecheck/rust-substitution-mapper.h
  gcc/rust/typecheck/rust-tyty-bounds.cc
  gcc/rust/typecheck/rust-tyty-call.h
  gcc/rust/typecheck/rust-tyty-cast.h
  gcc/rust/typecheck/rust-tyty-cmp.h
  gcc/rust/typecheck/rust-tyty-coercion.h
  gcc/rust/typecheck/rust-tyty-rules.h
  gcc/rust/typecheck/rust-tyty-visitor.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust/compile/traits10.rs
  gcc/testsuite/rust/compile/traits11.rs
  gcc/testsuite/rust/compile/traits9.rs
  gcc/testsuite/rust/compile/tuple_struct3.rs
  gcc/testsuite/rust/execute/torture/trait5.rs
Labels: enhancement

#687 Fix byte char and byte string lexing code
  gcc/rust/lex/rust-lex.cc
  gcc/testsuite/rust/compile/bytecharstring.rs
Labels: bug, cleanup

#688 Remove warnings from v0_mangle functions in rust-mangle.cc
  gcc/rust/backend/rust-mangle.cc
Labels: cleanup

#690 A bit of 'RichLocation' C++ tuning [#247], [#97, #374]
  gcc/rust/rust-diagnostics.cc
  gcc/rust/rust-diagnostics.h
  gcc/rust/rust-gcc-diagnostics.cc
  gcc/rust/rust-location.h
Labels: diagnostic, cleanup

#689 x86: Instead of 'TARGET_ISA_[...]', 'TARGET_ISA2_[...]', use 'TARGET_[...]' [#247]
  gcc/config/i386/i386-rust.c
  gcc/rust/rust-session-manager.cc
Labels: cleanup

#695 Fix raw byte string parsing of zero and out of range bytes
  gcc/rust/lex/rust-lex.cc
  gcc/testsuite/rust/compile/rawbytestring.rs
Labels: bug
