Repository Rust-GCC/gccrs, pull requests merged in 2021-03, with the labels that each got.

#257 Fix to parse inner attribute correctly
  gcc/rust/parse/rust-parse-impl.h
Labels: bug

#255 Add in support for string literals
  gcc/rust/backend/rust-compile-context.h
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/backend/rust-compile-tyty.h
  gcc/rust/resolve/rust-ast-resolve.cc
  gcc/rust/rust-backend.h
  gcc/rust/rust-gcc.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-tyty-call.h
  gcc/rust/typecheck/rust-tyty-rules.h
  gcc/rust/typecheck/rust-tyty-visitor.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust.test/compilable/str1.rs
Labels: enhancement

#273 Fix Woverloaded-virtual warnings.
  gcc/rust/Make-lang.in
  gcc/rust/backend/rust-compile-block.h
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/backend/rust-compile-fnparam.h
  gcc/rust/backend/rust-compile-implitem.h
  gcc/rust/backend/rust-compile-item.h
  gcc/rust/backend/rust-compile-resolve-path.h
  gcc/rust/backend/rust-compile-stmt.h
  gcc/rust/backend/rust-compile-struct-field-expr.h
  gcc/rust/backend/rust-compile-var-decl.h
  gcc/rust/hir/rust-ast-lower-block.h
  gcc/rust/hir/rust-ast-lower-expr.h
  gcc/rust/hir/rust-ast-lower-implitem.h
  gcc/rust/hir/rust-ast-lower-item.h
  gcc/rust/hir/rust-ast-lower-pattern.h
  gcc/rust/hir/rust-ast-lower-stmt.h
  gcc/rust/hir/rust-ast-lower-struct-field-expr.h
  gcc/rust/hir/rust-ast-lower-type.h
  gcc/rust/resolve/rust-ast-resolve-expr.h
  gcc/rust/resolve/rust-ast-resolve-implitem.h
  gcc/rust/resolve/rust-ast-resolve-item.h
  gcc/rust/resolve/rust-ast-resolve-pattern.h
  gcc/rust/resolve/rust-ast-resolve-stmt.h
  gcc/rust/resolve/rust-ast-resolve-struct-expr-field.h
  gcc/rust/resolve/rust-ast-resolve-toplevel.h
  gcc/rust/resolve/rust-ast-resolve-type.h
  gcc/rust/resolve/rust-ast-verify-assignee.h
  gcc/rust/typecheck/rust-hir-method-resolve.h
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check-implitem.h
  gcc/rust/typecheck/rust-hir-type-check-item.h
  gcc/rust/typecheck/rust-hir-type-check-stmt.h
  gcc/rust/typecheck/rust-hir-type-check-struct-field.h
  gcc/rust/typecheck/rust-hir-type-check-toplevel.h
  gcc/rust/typecheck/rust-hir-type-check-type.h
  gcc/rust/typecheck/rust-tycheck-dump.h
  gcc/rust/typecheck/rust-tyty-rules.h
Labels: bug, cleanup, enhancement

#277 CI workflow make -j commit
  .github/workflows/ccpp.yml
Labels: automation

#285 Documentation for issue #279
  README.md
Labels: cleanup, community, enhancement, good-first-pr

#290 Modify parser error message reporting system to allow recovery
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/parse/rust-parse.h
  gcc/rust/rust-diagnostics.cc
  gcc/rust/rust-diagnostics.h
Labels: diagnostic

#297 Generics continued this adds more type resolution to ADT and Functions
  gcc/rust/backend/rust-compile-context.h
  gcc/rust/backend/rust-compile-implitem.h
  gcc/rust/backend/rust-compile-item.h
  gcc/rust/backend/rust-compile-resolve-path.cc
  gcc/rust/backend/rust-compile-tyty.h
  gcc/rust/rust-backend.h
  gcc/rust/rust-gcc.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check-implitem.h
  gcc/rust/typecheck/rust-hir-type-check-item.h
  gcc/rust/typecheck/rust-hir-type-check-stmt.h
  gcc/rust/typecheck/rust-hir-type-check-toplevel.h
  gcc/rust/typecheck/rust-hir-type-check-type.h
  gcc/rust/typecheck/rust-hir-type-check.cc
  gcc/rust/typecheck/rust-substitution-mapper.h
  gcc/rust/typecheck/rust-tyty-rules.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust.test/compilable/generics3.rs
  gcc/testsuite/rust.test/compilable/generics4.rs
  gcc/testsuite/rust.test/compilable/generics5.rs
  gcc/testsuite/rust.test/compilable/generics6.rs
  gcc/testsuite/rust.test/compilable/generics7.rs
Labels: enhancement

#303 Add missing location info into TypePath
  gcc/rust/parse/rust-parse-impl.h
Labels: bug

#302 Fix error while unexpected EOF when scanning for end of comment
  gcc/rust/lex/rust-lex.cc
  gcc/testsuite/rust.test/fail_compilation/unterminated_c_comment.rs
Labels: bug

#319 Fix infinite loop when expanding cfg attributes
  gcc/rust/expand/rust-macro-expand.cc
  gcc/testsuite/rust.test/xfail_compile/cfg_attr.rs
Labels: bug

#326 Fixed bug TyTy::SubstitutionRef::needs_substitution
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust.test/compile/generics12.rs
Labels: bug
