Repository Rust-GCC/gccrs, pull requests merged in 2021-06, with the labels that each got.

#455 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: community

#495 HIR cleanup
  gcc/rust/backend/rust-compile-base.h
  gcc/rust/backend/rust-compile-implitem.h
  gcc/rust/backend/rust-compile-item.h
  gcc/rust/backend/rust-compile-resolve-path.cc
  gcc/rust/backend/rust-compile.cc
  gcc/rust/hir/rust-ast-lower-implitem.h
  gcc/rust/hir/rust-ast-lower-item.h
  gcc/rust/hir/rust-ast-lower-type.h
  gcc/rust/hir/rust-ast-lower.cc
  gcc/rust/hir/tree/rust-hir-full-decls.h
  gcc/rust/hir/tree/rust-hir-full-test.cc
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/hir/tree/rust-hir-visitor.h
  gcc/rust/hir/tree/rust-hir.h
  gcc/rust/lint/rust-lint-marklive-base.h
  gcc/rust/lint/rust-lint-marklive.cc
  gcc/rust/lint/rust-lint-marklive.h
  gcc/rust/typecheck/rust-hir-const-fold-base.h
  gcc/rust/typecheck/rust-hir-inherent-impl-overlap.h
  gcc/rust/typecheck/rust-hir-path-probe.h
  gcc/rust/typecheck/rust-hir-type-check-base.h
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check-implitem.h
  gcc/rust/typecheck/rust-hir-type-check-item.h
  gcc/rust/typecheck/rust-hir-type-check-toplevel.h
  gcc/rust/typecheck/rust-tycheck-dump.h
  gcc/rust/util/rust-hir-map.cc
  gcc/rust/util/rust-hir-map.h
Labels: bug, cleanup

#496 TraitImpl blocks have a different CanonicalPath to normal impl blocks
  gcc/rust/resolve/rust-ast-resolve-toplevel.h
  gcc/rust/resolve/rust-ast-resolve-type.h
  gcc/rust/resolve/rust-name-resolver.h
Labels: bug, cleanup

#498 Remove HIR::TraitItemMethod, this can be represented by TraitItemFunction
  gcc/rust/backend/rust-compile-base.h
  gcc/rust/backend/rust-compile-fnparam.h
  gcc/rust/hir/rust-ast-lower-implitem.h
  gcc/rust/hir/tree/rust-hir-full-decls.h
  gcc/rust/hir/tree/rust-hir-full-test.cc
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/hir/tree/rust-hir-visitor.h
  gcc/rust/hir/tree/rust-hir.h
  gcc/rust/lint/rust-lint-marklive-base.h
  gcc/rust/lint/rust-lint-marklive.h
  gcc/rust/typecheck/rust-hir-const-fold-base.h
  gcc/rust/typecheck/rust-hir-type-check-base.h
  gcc/rust/typecheck/rust-hir-type-check-implitem.h
Labels: cleanup

#503 Use DW_LANG_Rust in DWARF
  gcc/dwarf2out.c
  gcc/testsuite/rust/debug/debug.exp
  gcc/testsuite/rust/debug/lang.rs
  gcc/testsuite/rust/debug/oldlang.rs
Labels: GCC

#505 DWARF for Rust primitive types
  gcc/dwarf2out.c
  gcc/rust/rust-gcc.cc
  gcc/testsuite/rust/debug/chartype.rs
  gcc/testsuite/rust/debug/i8u8.rs
Labels: GCC

#512 Fix various Wformat-diag diagnostics
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/backend/rust-compile-resolve-path.cc
  gcc/rust/backend/rust-compile-stmt.h
  gcc/rust/backend/rust-compile.cc
  gcc/rust/lex/rust-lex.cc
  gcc/rust/lex/rust-token.cc
  gcc/rust/lint/rust-lint-scan-deadcode.h
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/resolve/rust-ast-resolve-type.h
  gcc/rust/resolve/rust-ast-resolve.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check-type.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/testsuite/rust/compile/break1.rs
  gcc/testsuite/rust/compile/break2.rs
  gcc/testsuite/rust/compile/continue1.rs
  gcc/testsuite/rust/compile/torture/unused.rs
  gcc/testsuite/rust/compile/torture/unused1.rs
  gcc/testsuite/rust/compile/tuple_struct1.rs
  gcc/testsuite/rust/compile/unary_not.rs
Labels: cleanup

#520 Add support for struct definitions to be within a block
  gcc/rust/backend/rust-compile-stmt.h
  gcc/rust/hir/rust-ast-lower-stmt.h
  gcc/rust/resolve/rust-ast-resolve-stmt.h
  gcc/rust/typecheck/rust-hir-type-check-stmt.h
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust/compile/torture/struct_init_10.rs
  gcc/testsuite/rust/compile/torture/struct_init_11.rs
  gcc/testsuite/rust/compile/torture/struct_init_9.rs
Labels: bug, cleanup

#521 Handle empty/unit tuple structs in the parser.
  gcc/rust/parse/rust-parse-impl.h
  gcc/testsuite/rust/compile/torture/tuple_struct_unit.rs
Labels: bug

#522 Handle empty/unit tuple enum variants in the parser.
  gcc/rust/parse/rust-parse-impl.h
  gcc/testsuite/rust/compile/torture/tuple_enum_variants.rs
Labels: bug

#523 Add support for nested functions
  gcc/rust/backend/rust-compile-base.h
  gcc/rust/backend/rust-compile-implitem.h
  gcc/rust/backend/rust-compile-item.h
  gcc/rust/backend/rust-compile.cc
  gcc/rust/hir/rust-ast-lower-stmt.h
  gcc/rust/resolve/rust-ast-resolve-stmt.h
  gcc/rust/resolve/rust-ast-resolve.cc
  gcc/rust/typecheck/rust-hir-type-check-stmt.h
  gcc/testsuite/rust/compile/lookup_err1.rs
  gcc/testsuite/rust/compile/torture/nested_fn1.rs
  gcc/testsuite/rust/compile/torture/nested_fn2.rs
Labels: bug, enhancement

#524 Change unit-type from void_type_node to a zero sized unsigned integer
  gcc/rust/backend/rust-compile-context.h
  gcc/rust/backend/rust-compile-tyty.h
  gcc/rust/rust-backend.h
  gcc/rust/rust-gcc.cc
  gcc/rust/typecheck/rust-hir-const-fold.h
  gcc/testsuite/rust/compile/torture/unit_type2.rs
Labels: GCC, bug, cleanup

#526 Add unit-type support for Identifier expressions
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/hir/rust-ast-lower-expr.h
  gcc/rust/lint/rust-lint-marklive.cc
  gcc/rust/resolve/rust-ast-resolve-expr.h
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust/compile/torture/unit_type3.rs
  gcc/testsuite/rust/compile/torture/unit_type4.rs
Labels: bug

#502 Trait Obligations building block
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/typecheck/rust-hir-trait-ref.h
  gcc/rust/typecheck/rust-hir-trait-resolve.h
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check-implitem.h
  gcc/rust/typecheck/rust-hir-type-check-item.h
  gcc/rust/typecheck/rust-hir-type-check.h
  gcc/rust/typecheck/rust-tyty-cmp.h
  gcc/testsuite/rust/compile/traits1.rs
  gcc/testsuite/rust/compile/traits2.rs
Labels: enhancement

#532 Marking live symbol for struct construction.
  gcc/rust/lint/rust-lint-marklive.cc
  gcc/rust/lint/rust-lint-marklive.h
  gcc/rust/lint/rust-lint-scan-deadcode.h
  gcc/rust/resolve/rust-ast-resolve-unused.h
  gcc/testsuite/rust/compile/torture/cfg_attr.rs
  gcc/testsuite/rust/compile/torture/unused1.rs
  gcc/testsuite/rust/compile/torture/unused_struct.rs
Labels: gsoc
