Repository Rust-GCC/gccrs, pull requests merged in 2021-11, with the labels that each got.

#783 Get rid of lambda within `AST::TypePath` and provide a method to return a reference
  gcc/rust/ast/rust-path.h
  gcc/rust/hir/rust-ast-lower-type.h
  gcc/rust/hir/rust-ast-lower.cc
Labels: cleanup

#788 gccrs: add the `-frust-crate=` option to set the crate name
  gcc/rust/lang.opt
  gcc/rust/rust-session-manager.cc
  gcc/rust/rust-session-manager.h
Labels: enhancement

#781 Add missing typechecking for enums
  gcc/rust/Make-lang.in
  gcc/rust/backend/rust-compile-context.h
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/backend/rust-compile.cc
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/hir/tree/rust-hir.h
  gcc/rust/lint/rust-lint-marklive.cc
  gcc/rust/typecheck/rust-hir-path-probe.h
  gcc/rust/typecheck/rust-hir-type-check-enumitem.h
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check-path.cc
  gcc/rust/typecheck/rust-hir-type-check-stmt.h
  gcc/rust/typecheck/rust-hir-type-check-struct-field.h
  gcc/rust/typecheck/rust-hir-type-check-struct.cc
  gcc/rust/typecheck/rust-hir-type-check-toplevel.h
  gcc/rust/typecheck/rust-hir-type-check.cc
  gcc/rust/typecheck/rust-hir-type-check.h
  gcc/rust/typecheck/rust-tyty-call.h
  gcc/rust/typecheck/rust-tyty-cast.h
  gcc/rust/typecheck/rust-tyty-cmp.h
  gcc/rust/typecheck/rust-tyty-coercion.h
  gcc/rust/typecheck/rust-tyty-rules.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust/compile/func2.rs
  gcc/testsuite/rust/compile/func3.rs
  gcc/testsuite/rust/compile/tuple_struct1.rs
  gcc/testsuite/rust/compile/tuple_struct2.rs
  gcc/testsuite/rust/compile/tuple_struct3.rs
Labels: enhancement

#794 Fix unhandled type bounds in TypeAlias
  gcc/rust/ast/rust-type.h
  gcc/rust/backend/rust-compile-base.h
  gcc/rust/backend/rust-compile-context.h
  gcc/rust/backend/rust-compile-implitem.h
  gcc/rust/backend/rust-compile.cc
  gcc/rust/hir/rust-ast-lower-type.h
  gcc/rust/hir/rust-ast-lower.cc
  gcc/rust/hir/tree/rust-hir-full-decls.h
  gcc/rust/hir/tree/rust-hir-full-test.cc
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/hir/tree/rust-hir-type.h
  gcc/rust/hir/tree/rust-hir-visitor.h
  gcc/rust/hir/tree/rust-hir.h
  gcc/rust/lint/rust-lint-marklive-base.h
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/resolve/rust-ast-resolve-type.h
  gcc/rust/resolve/rust-ast-resolve.cc
  gcc/rust/typecheck/rust-hir-const-fold-base.h
  gcc/rust/typecheck/rust-hir-trait-ref.h
  gcc/rust/typecheck/rust-hir-type-check-base.h
  gcc/rust/typecheck/rust-hir-type-check-item.h
  gcc/rust/typecheck/rust-hir-type-check-type.cc
  gcc/rust/typecheck/rust-hir-type-check-type.h
  gcc/rust/typecheck/rust-hir-type-check-util.h
  gcc/rust/typecheck/rust-tyty-bounds.cc
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust/compile/traits10.rs
  gcc/testsuite/rust/compile/traits11.rs
  gcc/testsuite/rust/execute/torture/trait12.rs
  gcc/testsuite/rust/execute/torture/trait13.rs
Labels: bug

#796 Handle forward declared items within blocks
  gcc/rust/ast/rust-ast.h
  gcc/rust/ast/rust-stmt.h
  gcc/rust/hir/tree/rust-hir-expr.h
  gcc/rust/hir/tree/rust-hir-stmt.h
  gcc/rust/hir/tree/rust-hir.h
  gcc/rust/lint/rust-lint-marklive.h
  gcc/rust/resolve/rust-ast-resolve.cc
  gcc/rust/typecheck/rust-hir-type-check.cc
  gcc/rust/typecheck/rust-tycheck-dump.h
  gcc/testsuite/rust/compile/torture/forward_decl_5.rs
Labels: bug

#801 operator overloading
  gcc/rust/Make-lang.in
  gcc/rust/ast/rust-ast.h
  gcc/rust/ast/rust-expr.h
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/backend/rust-compile.cc
  gcc/rust/hir/rust-ast-lower-expr.h
  gcc/rust/hir/rust-ast-lower-item.h
  gcc/rust/hir/tree/rust-hir-expr.h
  gcc/rust/hir/tree/rust-hir-full-test.cc
  gcc/rust/hir/tree/rust-hir-visitor.h
  gcc/rust/lint/rust-lint-marklive-base.h
  gcc/rust/lint/rust-lint-marklive.h
  gcc/rust/resolve/rust-ast-verify-assignee.h
  gcc/rust/typecheck/rust-autoderef.h
  gcc/rust/typecheck/rust-hir-const-fold-base.h
  gcc/rust/typecheck/rust-hir-path-probe.h
  gcc/rust/typecheck/rust-hir-trait-resolve.cc
  gcc/rust/typecheck/rust-hir-trait-resolve.h
  gcc/rust/typecheck/rust-hir-type-check-base.h
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check-implitem.h
  gcc/rust/typecheck/rust-hir-type-check-item.h
  gcc/rust/typecheck/rust-hir-type-check-stmt.h
  gcc/rust/typecheck/rust-hir-type-check-util.h
  gcc/rust/typecheck/rust-hir-type-check.h
  gcc/rust/typecheck/rust-tyctx.cc
  gcc/rust/util/rust-hir-map.h
  gcc/testsuite/rust/execute/torture/operator_overload_1.rs
  gcc/testsuite/rust/execute/torture/operator_overload_2.rs
  gcc/testsuite/rust/execute/torture/operator_overload_3.rs
  gcc/testsuite/rust/execute/torture/operator_overload_4.rs
  gcc/testsuite/rust/execute/torture/operator_overload_5.rs
Labels: enhancement

#805 Remove Btype, Bexpression, etc. abstractions over gcc trees
  gcc/rust/backend/rust-compile-base.h
  gcc/rust/backend/rust-compile-block.h
  gcc/rust/backend/rust-compile-context.h
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/backend/rust-compile-extern.h
  gcc/rust/backend/rust-compile-fnparam.h
  gcc/rust/backend/rust-compile-implitem.h
  gcc/rust/backend/rust-compile-intrinsic.cc
  gcc/rust/backend/rust-compile-intrinsic.h
  gcc/rust/backend/rust-compile-item.h
  gcc/rust/backend/rust-compile-resolve-path.cc
  gcc/rust/backend/rust-compile-resolve-path.h
  gcc/rust/backend/rust-compile-stmt.h
  gcc/rust/backend/rust-compile-struct-field-expr.h
  gcc/rust/backend/rust-compile-tyty.h
  gcc/rust/backend/rust-compile-var-decl.h
  gcc/rust/backend/rust-compile.cc
  gcc/rust/rust-backend.h
  gcc/rust/rust-gcc.cc
  gcc/rust/typecheck/rust-hir-const-fold-ctx.h
  gcc/rust/typecheck/rust-hir-const-fold.cc
  gcc/rust/typecheck/rust-hir-const-fold.h
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-tyty.h
Labels: GCC, cleanup

#810 Fix MethodCalls for covariant impl blocks
  gcc/rust/Make-lang.in
  gcc/rust/resolve/rust-ast-resolve-type.h
  gcc/rust/resolve/rust-ast-resolve.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-substitution-mapper.cc
  gcc/rust/typecheck/rust-substitution-mapper.h
  gcc/rust/typecheck/rust-tyty-call.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/testsuite/rust/compile/torture/issue-808.rs
Labels: bug

#811 Remove implicit name hack for trait associated types
  gcc/rust/resolve/rust-ast-resolve-item.h
  gcc/testsuite/rust/compile/torture/issue-808.rs
  gcc/testsuite/rust/compile/torture/traits11.rs
  gcc/testsuite/rust/compile/torture/traits4.rs
  gcc/testsuite/rust/compile/torture/traits5.rs
  gcc/testsuite/rust/compile/torture/traits6.rs
  gcc/testsuite/rust/execute/torture/operator_overload_1.rs
  gcc/testsuite/rust/execute/torture/operator_overload_2.rs
  gcc/testsuite/rust/execute/torture/operator_overload_3.rs
  gcc/testsuite/rust/execute/torture/operator_overload_4.rs
  gcc/testsuite/rust/execute/torture/operator_overload_5.rs
Labels: cleanup

#800 Added Remark markdown automation
  .github/workflows/Remark.yml
  .remarkrc
  CONTRIBUTING.md
  README.md
Labels: automation

#812 Remove implicit paths hack
  gcc/rust/resolve/rust-ast-resolve-implitem.h
  gcc/rust/resolve/rust-ast-resolve-item.h
  gcc/rust/resolve/rust-ast-resolve.cc
  gcc/rust/resolve/rust-name-resolver.h
  gcc/rust/typecheck/rust-hir-type-check-type.cc
Labels: bug

#813 Support QualifiedPathInType's within the same Trait
  gcc/rust/resolve/rust-ast-resolve-type.h
  gcc/rust/typecheck/rust-hir-type-bounds.h
  gcc/rust/typecheck/rust-hir-type-check-type.cc
  gcc/testsuite/rust/compile/torture/associated_types1.rs
Labels: bug

#814 Set TREE_ADDRESSABLE when we need to borrow any expression
  gcc/rust/Make-lang.in
  gcc/rust/backend/rust-compile-fnparam.h
  gcc/rust/backend/rust-compile-var-decl.h
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/typecheck/rust-autoderef.h
  gcc/rust/typecheck/rust-hir-address-taken.cc
  gcc/rust/typecheck/rust-hir-address-taken.h
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/testsuite/rust/execute/torture/operator_overload_6.rs
Labels: bug

#819 Update legacy mangling of names
  gcc/rust/backend/rust-mangle.cc
Labels: bug

#817 Remove bad mutability check pass
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/hir/rust-ast-lower-implitem.h
  gcc/rust/hir/rust-ast-lower-item.h
  gcc/rust/resolve/rust-ast-verify-assignee.h
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/testsuite/rust/compile/array3.rs
  gcc/testsuite/rust/compile/immutable1.rs
  gcc/testsuite/rust/compile/immutable2.rs
  gcc/testsuite/rust/compile/immutable3.rs
  gcc/testsuite/rust/compile/immutable4.rs
  gcc/testsuite/rust/compile/immutable5.rs
Labels: bug, cleanup

#820 Bug fix mutability checks in can_eq for autoderef
  gcc/rust/typecheck/rust-hir-dot-operator.h
  gcc/rust/typecheck/rust-tyty-cmp.h
  gcc/rust/typecheck/rust-tyty-rules.h
  gcc/rust/typecheck/rust-tyty.cc
Labels: bug, enhancement

#823 Support generics on operator overlads.
  gcc/rust/typecheck/rust-hir-type-check-expr.h
Labels: bug, cleanup

#818 Deref operator overloading
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/util/rust-hir-map.h
  gcc/testsuite/rust/execute/torture/operator_overload_10.rs
  gcc/testsuite/rust/execute/torture/operator_overload_7.rs
  gcc/testsuite/rust/execute/torture/operator_overload_8.rs
  gcc/testsuite/rust/execute/torture/operator_overload_9.rs
Labels: bug, enhancement
