Repository Rust-GCC/gccrs, pull requests merged in 2021-04, with the labels that each got.

#332 Placate GCC 4.8
  gcc/rust/parse/rust-parse-impl.h
Labels: cleanup

#331 Initial bors-ng integration
  .github/bors.toml
  .github/workflows/ccpp.yml
  .github/workflows/clang-format.yml
Labels: automation, community

#357 Create liveness analysis for dead code detection
  gcc/rust/Make-lang.in
  gcc/rust/analysis/rust-hir-liveness-base.h
  gcc/rust/analysis/rust-hir-liveness.cc
  gcc/rust/analysis/rust-hir-liveness.h
  gcc/rust/analysis/rust-hir-scan-deadcode.h
  gcc/rust/rust-session-manager.cc
  gcc/testsuite/rust.test/compile/unused.rs
Labels: diagnostic, gsoc

#358 Canonical Paths for Name Resolution and handle TurboFish properly
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/backend/rust-compile-resolve-path.h
  gcc/rust/hir/rust-ast-lower-item.h
  gcc/rust/hir/tree/rust-hir-path.h
  gcc/rust/resolve/rust-ast-resolve-expr.h
  gcc/rust/resolve/rust-ast-resolve-implitem.h
  gcc/rust/resolve/rust-ast-resolve-item.h
  gcc/rust/resolve/rust-ast-resolve-pattern.h
  gcc/rust/resolve/rust-ast-resolve-toplevel.h
  gcc/rust/resolve/rust-ast-resolve-type.h
  gcc/rust/resolve/rust-ast-resolve.cc
  gcc/rust/resolve/rust-ast-verify-assignee.h
  gcc/rust/resolve/rust-name-resolver.h
  gcc/rust/typecheck/rust-hir-inherent-impl-overlap.h
  gcc/rust/typecheck/rust-hir-method-resolve.h
  gcc/rust/typecheck/rust-hir-path-probe.h
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check-stmt.h
  gcc/rust/typecheck/rust-hir-type-check-struct-field.h
  gcc/rust/typecheck/rust-hir-type-check.cc
  gcc/rust/typecheck/rust-substitution-mapper.h
  gcc/rust/typecheck/rust-tyty-cmp.h
  gcc/rust/typecheck/rust-tyty-rules.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/rust/util/rust-hir-map.cc
  gcc/rust/util/rust-hir-map.h
  gcc/testsuite/rust.test/compile/generics13.rs
  gcc/testsuite/rust.test/compile/generics14.rs
  gcc/testsuite/rust.test/compile/generics15.rs
  gcc/testsuite/rust.test/compile/generics16.rs
  gcc/testsuite/rust.test/xfail_compile/generics6.rs
  gcc/testsuite/rust.test/xfail_compile/generics7.rs
  gcc/testsuite/rust.test/xfail_compile/redef_error6.rs
  gcc/testsuite/rust.test/xfail_compile/tuple1.rs
  gcc/testsuite/rust.test/xfail_compile/type-alias1.rs
Labels: cleanup, debug, enhancement

#369 Implement the inline visitor
  gcc/rust/util/rust-inline-visitor.h
Labels: cleanup, enhancement

#377 Fix crash when mapping of Generic argument changes.
  gcc/rust/resolve/rust-ast-resolve-item.h
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check-type.h
  gcc/rust/typecheck/rust-substitution-mapper.h
  gcc/rust/typecheck/rust-tyty-cmp.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust.test/compile/generics17.rs
  gcc/testsuite/rust.test/compile/generics18.rs
Labels: bug

#378 Add Check for unconstrained type parameters
  gcc/rust/typecheck/rust-hir-type-check-toplevel.h
  gcc/rust/typecheck/rust-hir-type-check-type.h
  gcc/testsuite/rust.test/xfail_compile/unconstrained_type_param.rs
Labels: diagnostic, enhancement

#381 Fix crash on empty parameters to generic data type
  gcc/rust/hir/tree/rust-hir-path.h
  gcc/rust/typecheck/rust-hir-type-check-toplevel.h
  gcc/rust/typecheck/rust-hir-type-check-type.h
  gcc/rust/typecheck/rust-substitution-mapper.h
  gcc/testsuite/rust.test/xfail_compile/expected_type_args2.rs
  gcc/testsuite/rust.test/xfail_compile/expected_type_args3.rs
  gcc/testsuite/rust.test/xfail_compile/generics8.rs
Labels: bug, diagnostic, enhancement

#383 Reuse fold-const.c from GCC to enforce const array capacities
  gcc/rust/Make-lang.in
  gcc/rust/backend/rust-compile-context.h
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/hir/rust-ast-lower-expr.h
  gcc/rust/hir/tree/rust-hir-expr.h
  gcc/rust/resolve/rust-ast-resolve-type.h
  gcc/rust/resolve/rust-ast-resolve.cc
  gcc/rust/rust-backend.h
  gcc/rust/rust-gcc.cc
  gcc/rust/rust-session-manager.cc
  gcc/rust/typecheck/rust-hir-const-fold-base.h
  gcc/rust/typecheck/rust-hir-const-fold-ctx.h
  gcc/rust/typecheck/rust-hir-const-fold.cc
  gcc/rust/typecheck/rust-hir-const-fold.h
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check-implitem.h
  gcc/rust/typecheck/rust-hir-type-check-toplevel.h
  gcc/rust/typecheck/rust-hir-type-check-type.h
  gcc/rust/typecheck/rust-hir-type-check.cc
  gcc/rust/typecheck/rust-tyty-rules.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust.test/compile/arrays3.rs
  gcc/testsuite/rust.test/compile/arrays4.rs
  gcc/testsuite/rust.test/xfail_compile/arrays2.rs
Labels: bug, cleanup

#394 Partial substitions of generic data types
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-substitution-mapper.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust.test/compile/generics19.rs
  gcc/testsuite/rust.test/compile/generics20.rs
Labels: bug

#397 Name resolve any specified types in TypeParams
  gcc/rust/resolve/rust-ast-resolve-type.h
  gcc/testsuite/rust.test/xfail_compile/generic-default1.rs
Labels: bug, diagnostic, enhancement

#398 ReferenceTypes and Tuple can hold Type Parameters
  gcc/rust/typecheck/rust-substitution-mapper.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust.test/compile/generics21.rs
  gcc/testsuite/rust.test/compile/generics22.rs
Labels: bug, enhancement

#399 Improve error diagnostics in generic argument handling
  gcc/rust/ast/rust-ast.h
  gcc/rust/ast/rust-path.h
  gcc/rust/hir/rust-ast-lower-base.h
  gcc/rust/hir/rust-ast-lower-type.h
  gcc/rust/hir/rust-ast-lower.cc
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/hir/tree/rust-hir-path.h
  gcc/rust/hir/tree/rust-hir.h
  gcc/rust/resolve/rust-ast-resolve-type.h
  gcc/rust/typecheck/rust-hir-type-check-implitem.h
  gcc/rust/typecheck/rust-hir-type-check-toplevel.h
  gcc/rust/typecheck/rust-hir-type-check-type.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust.test/compile/generics23.rs
  gcc/testsuite/rust.test/compile/generics24.rs
  gcc/testsuite/rust.test/compile/lifetime1.rs
  gcc/testsuite/rust.test/xfail_compile/expected_type_args2.rs
  gcc/testsuite/rust.test/xfail_compile/expected_type_args3.rs
  gcc/testsuite/rust.test/xfail_compile/generics4.rs
  gcc/testsuite/rust.test/xfail_compile/type-bindings1.rs
Labels: cleanup, diagnostic
