Repository Rust-GCC/gccrs, pull requests merged in 2021-08, with the labels that each got.

#601 union support for hir type checking and gcc backend
  gcc/rust/ast/rust-item.h
  gcc/rust/backend/rust-compile-context.h
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/backend/rust-compile.cc
  gcc/rust/hir/rust-ast-lower-item.h
  gcc/rust/hir/rust-ast-lower-stmt.h
  gcc/rust/hir/tree/rust-hir-expr.h
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/resolve/rust-ast-resolve-item.h
  gcc/rust/resolve/rust-ast-resolve-stmt.h
  gcc/rust/resolve/rust-ast-resolve-toplevel.h
  gcc/rust/rust-backend.h
  gcc/rust/rust-gcc.cc
  gcc/rust/typecheck/rust-hir-type-check-stmt.h
  gcc/rust/typecheck/rust-hir-type-check-toplevel.h
  gcc/rust/typecheck/rust-hir-type-check.cc
  gcc/rust/typecheck/rust-tycheck-dump.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust/compile/torture/union.rs
  gcc/testsuite/rust/compile/torture/union_union.rs
Labels: enhancement

#605 Merge both module classes in one
  gcc/rust/ast/rust-ast-full-decls.h
  gcc/rust/ast/rust-ast-full-test.cc
  gcc/rust/ast/rust-ast-visitor.h
  gcc/rust/ast/rust-item.h
  gcc/rust/expand/rust-macro-expand.cc
  gcc/rust/hir/rust-ast-lower-base.h
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/resolve/rust-ast-resolve-base.h
Labels: enhancement

#609 Initial TypeBounds support
  gcc/rust/Make-lang.in
  gcc/rust/ast/rust-ast.h
  gcc/rust/ast/rust-type.h
  gcc/rust/backend/rust-compile-resolve-path.cc
  gcc/rust/backend/rust-compile.cc
  gcc/rust/hir/rust-ast-lower-base.h
  gcc/rust/hir/rust-ast-lower-item.h
  gcc/rust/hir/rust-ast-lower-type.h
  gcc/rust/hir/rust-ast-lower.cc
  gcc/rust/hir/tree/rust-hir-full-test.cc
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/hir/tree/rust-hir-type.h
  gcc/rust/hir/tree/rust-hir.h
  gcc/rust/resolve/rust-ast-resolve-type.h
  gcc/rust/typecheck/rust-hir-path-probe.h
  gcc/rust/typecheck/rust-hir-trait-ref.h
  gcc/rust/typecheck/rust-hir-trait-resolve.h
  gcc/rust/typecheck/rust-hir-type-bounds.h
  gcc/rust/typecheck/rust-hir-type-check-base.h
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check-type.h
  gcc/rust/typecheck/rust-hir-type-check.cc
  gcc/rust/typecheck/rust-hir-type-check.h
  gcc/rust/typecheck/rust-substitution-mapper.h
  gcc/rust/typecheck/rust-tyty-bounds.cc
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/rust/util/rust-hir-map.cc
  gcc/rust/util/rust-hir-map.h
  gcc/testsuite/rust/compile/torture/traits8.rs
  gcc/testsuite/rust/compile/torture/traits9.rs
Labels: enhancement

#614 rust to gcc glue layer: Remove excess precision when done
  gcc/rust/rust-gcc.cc
Labels: bug

#611 Add check for TypeBounds on argument substitutions
  gcc/rust/backend/rust-compile-resolve-path.cc
  gcc/rust/backend/rust-compile.cc
  gcc/rust/typecheck/rust-hir-path-probe.h
  gcc/rust/typecheck/rust-hir-trait-ref.h
  gcc/rust/typecheck/rust-hir-trait-resolve.h
  gcc/rust/typecheck/rust-hir-type-bounds.h
  gcc/rust/typecheck/rust-hir-type-check-base.h
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check-item.h
  gcc/rust/typecheck/rust-hir-type-check-type.h
  gcc/rust/typecheck/rust-hir-type-check.h
  gcc/rust/typecheck/rust-tyty-bounds.cc
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/rust/util/rust-hir-map.cc
  gcc/rust/util/rust-hir-map.h
  gcc/testsuite/rust/compile/traits6.rs
  gcc/testsuite/rust/compile/traits7.rs
Labels: bug, enhancement

#618 Make insert_new_definition permissive of the same mapping.
  gcc/rust/resolve/rust-ast-resolve.cc
  gcc/rust/resolve/rust-name-resolver.h
Labels: bug

#620 Pass pratt parsed location to expr parser functions to fix expr locus
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/parse/rust-parse.h
Labels: bug, diagnostic

#621 Add docker image builds though github actions.
  .github/workflows/docker.yml
Labels: automation

#626 Optional trait items
  gcc/rust/Make-lang.in
  gcc/rust/ast/rust-path.h
  gcc/rust/backend/rust-compile-context.h
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/backend/rust-compile-implitem.h
  gcc/rust/backend/rust-compile-item.h
  gcc/rust/backend/rust-compile-resolve-path.cc
  gcc/rust/backend/rust-compile-resolve-path.h
  gcc/rust/backend/rust-compile-tyty.h
  gcc/rust/backend/rust-compile.cc
  gcc/rust/hir/rust-ast-lower-base.h
  gcc/rust/hir/rust-ast-lower-expr.h
  gcc/rust/hir/rust-ast-lower-implitem.h
  gcc/rust/hir/rust-ast-lower.cc
  gcc/rust/hir/tree/rust-hir-full-test.cc
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/hir/tree/rust-hir-path.h
  gcc/rust/hir/tree/rust-hir.h
  gcc/rust/resolve/rust-ast-resolve-expr.h
  gcc/rust/resolve/rust-ast-resolve-toplevel.h
  gcc/rust/resolve/rust-ast-resolve.cc
  gcc/rust/typecheck/rust-hir-const-fold.h
  gcc/rust/typecheck/rust-hir-path-probe.h
  gcc/rust/typecheck/rust-hir-trait-ref.h
  gcc/rust/typecheck/rust-hir-trait-resolve.cc
  gcc/rust/typecheck/rust-hir-trait-resolve.h
  gcc/rust/typecheck/rust-hir-type-bounds.h
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check-implitem.h
  gcc/rust/typecheck/rust-hir-type-check-item.h
  gcc/rust/typecheck/rust-hir-type-check-util.cc
  gcc/rust/typecheck/rust-hir-type-check-util.h
  gcc/rust/typecheck/rust-hir-type-check.h
  gcc/rust/typecheck/rust-substitution-mapper.h
  gcc/rust/typecheck/rust-tyty-bounds.cc
  gcc/rust/typecheck/rust-tyty-call.h
  gcc/rust/typecheck/rust-tyty-cast.h
  gcc/rust/typecheck/rust-tyty-cmp.h
  gcc/rust/typecheck/rust-tyty-coercion.h
  gcc/rust/typecheck/rust-tyty-rules.h
  gcc/rust/typecheck/rust-tyty-visitor.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/rust/util/rust-canonical-path.h
  gcc/testsuite/rust/compile/torture/traits10.rs
  gcc/testsuite/rust/compile/torture/traits11.rs
  gcc/testsuite/rust/compile/traits1.rs
  gcc/testsuite/rust/compile/traits2.rs
  gcc/testsuite/rust/execute/torture/trait1.rs
Labels: enhancement

#640 Optional Trait items constants
  gcc/rust/Make-lang.in
  gcc/rust/backend/rust-compile-implitem.h
  gcc/rust/backend/rust-compile-item.h
  gcc/rust/backend/rust-compile-resolve-path.cc
  gcc/rust/backend/rust-compile-resolve-path.h
  gcc/rust/resolve/rust-ast-resolve.cc
  gcc/rust/typecheck/rust-hir-path-probe.h
  gcc/rust/typecheck/rust-hir-trait-ref.h
  gcc/rust/typecheck/rust-hir-trait-resolve.cc
  gcc/rust/typecheck/rust-hir-trait-resolve.h
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check-path.cc
  gcc/testsuite/rust/execute/torture/trait2.rs
Labels: enhancement

#651 Qualified paths have a mandatory initial segment
  gcc/rust/ast/rust-path.h
  gcc/rust/parse/rust-parse-impl.h
Labels: enhancement
