Repository Rust-GCC/gccrs, pull requests merged in 2021-12, with the labels that each got.

#828 Add script to generate gource
  gcc/rust/gource-gccrs.sh
Labels: community

#831 Fix out-of-bounds in typechecking of ADTTypes
  gcc/rust/typecheck/rust-tyty-cmp.h
  gcc/rust/typecheck/rust-tyty-coercion.h
  gcc/rust/typecheck/rust-tyty-rules.h
Labels: bug

#834 Add enum code generation
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/backend/rust-compile-resolve-path.cc
  gcc/rust/backend/rust-compile-type.cc
  gcc/rust/backend/rust-compile-type.h
  gcc/rust/backend/rust-compile.cc
  gcc/rust/rust-backend.h
  gcc/rust/rust-gcc.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust/compile/torture/enum1.rs
Labels: enhancement

#835 Add name-resolution and HIR lowering pass for MatchExpr
  gcc/rust/Make-lang.in
  gcc/rust/ast/rust-expr.h
  gcc/rust/ast/rust-pattern.h
  gcc/rust/hir/rust-ast-lower-expr.h
  gcc/rust/hir/rust-ast-lower-pattern.cc
  gcc/rust/hir/rust-ast-lower-pattern.h
  gcc/rust/hir/tree/rust-hir-expr.h
  gcc/rust/hir/tree/rust-hir-full-decls.h
  gcc/rust/hir/tree/rust-hir-full-test.cc
  gcc/rust/hir/tree/rust-hir-pattern.h
  gcc/rust/resolve/rust-ast-resolve-expr.h
  gcc/rust/resolve/rust-ast-resolve-pattern.cc
  gcc/rust/resolve/rust-ast-resolve-pattern.h
Labels: enhancement

#836 BugFix NodeId skew on AST::Patterns
  gcc/rust/ast/rust-ast.h
  gcc/rust/ast/rust-macro.h
  gcc/rust/ast/rust-path.h
  gcc/rust/ast/rust-pattern.h
  gcc/rust/resolve/rust-ast-resolve-item.h
  gcc/rust/resolve/rust-ast-resolve-stmt.h
Labels: bug

#837 HIR::IdentifierPattern had all fields public
  gcc/rust/backend/rust-compile-fnparam.h
  gcc/rust/backend/rust-compile-var-decl.h
  gcc/rust/hir/tree/rust-hir-pattern.h
Labels: cleanup

#838 Add mssing mappings to HIR::Pattern
  gcc/rust/hir/rust-ast-lower-pattern.cc
  gcc/rust/hir/rust-ast-lower-pattern.h
  gcc/rust/hir/tree/rust-hir-path.h
  gcc/rust/hir/tree/rust-hir-pattern.h
  gcc/rust/hir/tree/rust-hir.h
  gcc/rust/typecheck/rust-hir-type-check-implitem.h
  gcc/rust/typecheck/rust-hir-type-check.cc
  gcc/rust/util/rust-hir-map.cc
  gcc/rust/util/rust-hir-map.h
Labels: bug, cleanup

#840 Add missing abstract method HIR::Pattern::get_locus() const
  gcc/rust/hir/tree/rust-hir-pattern.h
  gcc/rust/hir/tree/rust-hir.h
Labels: bug, cleanup

#841 Add support for enums on the match expression
  gcc/rust/Make-lang.in
  gcc/rust/backend/rust-compile-context.h
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/backend/rust-compile-pattern.cc
  gcc/rust/backend/rust-compile-pattern.h
  gcc/testsuite/rust/execute/torture/match1.rs
  gcc/testsuite/rust/execute/torture/match2.rs
Labels: enhancement

#842 add script to graph the changes over time
  gcc/rust/monthly-diff.py
Labels: diagnostic

#846 HIR visitor refactor
  gcc/rust/backend/rust-compile-base.h
  gcc/rust/hir/tree/rust-hir-cond-compilation.h
  gcc/rust/hir/tree/rust-hir-expr.h
  gcc/rust/hir/tree/rust-hir-full-test.cc
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/hir/tree/rust-hir-path.h
  gcc/rust/hir/tree/rust-hir-pattern.h
  gcc/rust/hir/tree/rust-hir-stmt.h
  gcc/rust/hir/tree/rust-hir-type.h
  gcc/rust/hir/tree/rust-hir-visitor.h
  gcc/rust/hir/tree/rust-hir.h
  gcc/rust/lint/rust-lint-marklive-base.h
  gcc/rust/typecheck/rust-hir-const-fold-base.h
  gcc/rust/typecheck/rust-hir-type-check-base.h
  gcc/rust/typecheck/rust-hir-type-check-util.h
  gcc/rust/typecheck/rust-tycheck-dump.h
Labels: cleanup
