Repository Rust-GCC/gccrs, pull requests merged in 2021-05, with the labels that each got.

#406 Add locations to implicit inference variables
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check.cc
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust.test/xfail_compile/array_empty_list.rs
  gcc/testsuite/rust.test/xfail_compile/generics11.rs
Labels: diagnostic, enhancement

#409 Fix crashing in assignment operation
  gcc/rust/parse/rust-parse-impl.h
  gcc/testsuite/rust.test/xfail_compile/issue-407.rs
Labels: bug, parser

#416 We need to monomorphize tuples as well as ADT's
  gcc/rust/backend/rust-compile-context.h
  gcc/testsuite/rust.test/compile/generics26.rs
  gcc/testsuite/rust.test/compile/generics27.rs
Labels: bug

#427 Fix duplicate function generation in the backend
  gcc/rust/backend/rust-compile-context.h
  gcc/rust/backend/rust-compile-implitem.h
  gcc/rust/backend/rust-compile-item.h
  gcc/rust/rust-diagnostics.h
  gcc/rust/typecheck/rust-hir-type-check-implitem.h
  gcc/rust/typecheck/rust-hir-type-check-toplevel.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
Labels: bug

#373 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: community

#430 Add FNV-128 hash for legacy symbol mangling
  gcc/rust/backend/rust-compile-context.h
  gcc/rust/backend/rust-compile-implitem.h
  gcc/rust/backend/rust-compile-item.h
  gcc/rust/backend/rust-compile.cc
  gcc/rust/util/fnv-hash.h
Labels: bug, cleanup

#433 Allow unused underscore identifiers
  gcc/rust/resolve/rust-ast-resolve-unused.h
  gcc/rust/resolve/rust-name-resolver.h
  gcc/testsuite/rust.test/compile/loop5.rs
  gcc/testsuite/rust.test/compile/loop7.rs
  gcc/testsuite/rust.test/compile/struct_base_init_1.rs
  gcc/testsuite/rust.test/compile/underscore_id.rs
Labels: diagnostic, enhancement

#372 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: community

#436 Fixed #419: only parse inner_attributes if it starts with "#!" not only "#"
  gcc/rust/parse/rust-parse-impl.h
  gcc/testsuite/rust.test/compile/top_attr.rs
Labels: bug

#438 DefId is a bit mask of CrateNum & LocalDefId
  gcc/rust/util/rust-hir-map.cc
Labels: bug
