Repository Rust-GCC/gccrs, pull requests merged in 2021-07, with the labels that each got.

#540 Add trait-impl support for methods
  gcc/rust/ast/rust-item.h
  gcc/rust/backend/rust-compile-base.h
  gcc/rust/backend/rust-compile-implitem.h
  gcc/rust/hir/rust-ast-lower-implitem.h
  gcc/rust/hir/rust-ast-lower-item.h
  gcc/rust/hir/rust-ast-lower-stmt.h
  gcc/rust/hir/tree/rust-hir-full-decls.h
  gcc/rust/hir/tree/rust-hir-full-test.cc
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/hir/tree/rust-hir-visitor.h
  gcc/rust/lint/rust-lint-marklive-base.h
  gcc/rust/lint/rust-lint-marklive.h
  gcc/rust/resolve/rust-ast-resolve-item.h
  gcc/rust/resolve/rust-ast-resolve-type.h
  gcc/rust/typecheck/rust-hir-const-fold-base.h
  gcc/rust/typecheck/rust-hir-inherent-impl-overlap.h
  gcc/rust/typecheck/rust-hir-path-probe.h
  gcc/rust/typecheck/rust-hir-trait-resolve.h
  gcc/rust/typecheck/rust-hir-type-check-base.h
  gcc/rust/typecheck/rust-hir-type-check-implitem.h
  gcc/rust/typecheck/rust-tycheck-dump.h
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust/compile/torture/traits3.rs
Labels: cleanup, enhancement

#546 shebang handling
  gcc/rust/ast/rust-ast-full-test.cc
  gcc/rust/ast/rust-ast.h
  gcc/rust/hir/rust-ast-lower.cc
  gcc/rust/hir/tree/rust-hir-full-test.cc
  gcc/rust/hir/tree/rust-hir.h
  gcc/rust/lex/rust-lex.cc
  gcc/rust/parse/rust-parse-impl.h
  gcc/testsuite/rust/compile/torture/not_shebang.rs
  gcc/testsuite/rust/compile/torture/not_shebang_block_comment.rs
  gcc/testsuite/rust/compile/torture/not_shebang_comment.rs
  gcc/testsuite/rust/compile/torture/not_shebang_multiline_comment.rs
  gcc/testsuite/rust/compile/torture/not_shebang_spaces.rs
  gcc/testsuite/rust/compile/torture/shebang.rs
  gcc/testsuite/rust/compile/torture/shebang_plus_attr.rs
  gcc/testsuite/rust/compile/torture/shebang_plus_attr2.rs
Labels: bug, cleanup

#552 UTF-8 BOM handling
  gcc/rust/ast/rust-ast-full-test.cc
  gcc/rust/ast/rust-ast.h
  gcc/rust/hir/rust-ast-lower.cc
  gcc/rust/hir/tree/rust-hir-full-test.cc
  gcc/rust/hir/tree/rust-hir.h
  gcc/rust/lex/rust-lex.cc
  gcc/rust/parse/rust-parse-impl.h
  gcc/testsuite/rust/compile/torture/bom.rs
  gcc/testsuite/rust/compile/torture/bom_comment.rs
  gcc/testsuite/rust/compile/torture/bom_shebang.rs
  gcc/testsuite/rust/compile/torture/bom_whitespace.rs
Labels: enhancement

#554 make the warning msg be searched easier
  gcc/rust/lint/rust-lint-scan-deadcode.h
Labels: cleanup, diagnostic, gsoc

#548 Fix bad naming of primitive types such as u64 which ended up as usize
  gcc/rust/backend/rust-compile-context.h
  gcc/rust/rust-gcc.cc
Labels: bug

#551 Initial AssociatedType support
  gcc/rust/ast/rust-path.h
  gcc/rust/backend/rust-compile-context.h
  gcc/rust/backend/rust-compile-tyty.h
  gcc/rust/hir/rust-ast-lower-implitem.h
  gcc/rust/hir/rust-ast-lower-item.h
  gcc/rust/hir/rust-ast-lower-type.h
  gcc/rust/hir/rust-ast-lower.cc
  gcc/rust/hir/tree/rust-hir-path.h
  gcc/rust/resolve/rust-ast-resolve-expr.h
  gcc/rust/resolve/rust-ast-resolve-implitem.h
  gcc/rust/resolve/rust-ast-resolve-item.h
  gcc/rust/resolve/rust-ast-resolve-pattern.h
  gcc/rust/resolve/rust-ast-resolve-stmt.h
  gcc/rust/resolve/rust-ast-resolve-toplevel.h
  gcc/rust/resolve/rust-ast-resolve-type.h
  gcc/rust/resolve/rust-ast-resolve.cc
  gcc/rust/resolve/rust-ast-verify-assignee.h
  gcc/rust/resolve/rust-name-resolver.h
  gcc/rust/typecheck/rust-hir-const-fold.h
  gcc/rust/typecheck/rust-hir-inherent-impl-overlap.h
  gcc/rust/typecheck/rust-hir-path-probe.h
  gcc/rust/typecheck/rust-hir-trait-resolve.h
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check-implitem.h
  gcc/rust/typecheck/rust-hir-type-check-type.h
  gcc/rust/typecheck/rust-substitution-mapper.h
  gcc/rust/typecheck/rust-tyty-call.h
  gcc/rust/typecheck/rust-tyty-cmp.h
  gcc/rust/typecheck/rust-tyty-rules.h
  gcc/rust/typecheck/rust-tyty-visitor.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust/compile/torture/traits3.rs
  gcc/testsuite/rust/compile/torture/traits4.rs
  gcc/testsuite/rust/compile/torture/traits5.rs
Labels: enhancement

#560 Remove HIR MacroItem and other hir macro forward declarations
  gcc/rust/hir/tree/rust-hir-expr.h
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/hir/tree/rust-hir-pattern.h
  gcc/rust/hir/tree/rust-hir-type.h
  gcc/rust/hir/tree/rust-hir.h
Labels: cleanup

#566 Further error checking for trait impl blocks
  gcc/rust/ast/rust-item.h
  gcc/rust/resolve/rust-ast-resolve-item.h
  gcc/rust/typecheck/rust-hir-trait-ref.h
  gcc/rust/typecheck/rust-hir-trait-resolve.h
  gcc/rust/typecheck/rust-hir-type-check-implitem.h
  gcc/rust/typecheck/rust-hir-type-check-item.h
  gcc/rust/typecheck/rust-hir-type-check.cc
  gcc/testsuite/rust/compile/torture/traits6.rs
  gcc/testsuite/rust/compile/torture/traits7.rs
  gcc/testsuite/rust/compile/traits3.rs
  gcc/testsuite/rust/compile/traits4.rs
  gcc/testsuite/rust/compile/traits5.rs
Labels: enhancement

#568 Add missing DefId mappings
  gcc/rust/hir/rust-ast-lower-implitem.h
  gcc/rust/hir/rust-ast-lower-stmt.h
  gcc/rust/typecheck/rust-hir-type-check-implitem.h
  gcc/rust/typecheck/rust-hir-type-check-stmt.h
  gcc/rust/typecheck/rust-hir-type-check-toplevel.h
  gcc/rust/typecheck/rust-hir-type-check.cc
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
Labels: cleanup

#571 call accept_vis directly instead of call it after get
  gcc/rust/lint/rust-lint-marklive.h
Labels: cleanup

#572 Cleanup and add const modifiers to equlity interface
  gcc/rust/hir/rust-ast-lower-item.h
  gcc/rust/typecheck/rust-hir-path-probe.h
  gcc/rust/typecheck/rust-tyty-cmp.h
  gcc/rust/typecheck/rust-tyty-visitor.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/rust/util/rust-hir-map.cc
  gcc/rust/util/rust-hir-map.h
Labels: cleanup

#578 Remove unused code
  gcc/rust/rust-backend.c
Labels: cleanup

#581 HIR and GENERIC lowering for unsafe blocks
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/hir/rust-ast-lower-block.h
  gcc/rust/hir/rust-ast-lower-expr.h
  gcc/rust/hir/tree/rust-hir-expr.h
  gcc/rust/resolve/rust-ast-resolve-expr.h
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/testsuite/rust/compile/torture/unsafe1.rs
  gcc/testsuite/rust/compile/torture/unsafe2.rs
  gcc/testsuite/rust/compile/unsafe.rs
Labels: bug

#579 Raw pointer support
  gcc/rust/backend/rust-compile-context.h
  gcc/rust/backend/rust-compile-tyty.h
  gcc/rust/hir/rust-ast-lower-type.h
  gcc/rust/hir/tree/rust-hir-full-test.cc
  gcc/rust/hir/tree/rust-hir-type.h
  gcc/rust/resolve/rust-ast-resolve-type.h
  gcc/rust/typecheck/rust-hir-const-fold.h
  gcc/rust/typecheck/rust-hir-type-check-type.h
  gcc/rust/typecheck/rust-substitution-mapper.h
  gcc/rust/typecheck/rust-tyty-call.h
  gcc/rust/typecheck/rust-tyty-cmp.h
  gcc/rust/typecheck/rust-tyty-coercion.h
  gcc/rust/typecheck/rust-tyty-rules.h
  gcc/rust/typecheck/rust-tyty-visitor.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust/compile/torture/coercion2.rs
Labels: enhancement

#582 unsafe blocks can be used in expressions
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/parse/rust-parse.h
Labels: bug

#586 Add mappings for trait items
  gcc/rust/hir/rust-ast-lower-implitem.h
  gcc/rust/util/rust-hir-map.cc
  gcc/rust/util/rust-hir-map.h
Labels: cleanup

#590 Better union support in the parser
  gcc/rust/parse/rust-parse-impl.h
Labels: enhancement

#591 Remove error handling in parse_type_no_bounds for PLUS token
  gcc/rust/parse/rust-parse-impl.h
Labels: bug

#594 Support byte and byte string literals
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/rust-backend.h
  gcc/rust/rust-gcc.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/testsuite/rust/compile/torture/byte_char_str.rs
Labels: enhancement

#593 Support RangeFrom ([x..]) and RangeFromTo ([x..y]) in the parser
  gcc/rust/parse/rust-parse-impl.h
Labels: bug

#592 TypeCastExpr
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/hir/rust-ast-lower-base.h
  gcc/rust/hir/rust-ast-lower-expr.h
  gcc/rust/hir/rust-ast-lower.cc
  gcc/rust/hir/tree/rust-hir-expr.h
  gcc/rust/resolve/rust-ast-resolve-expr.h
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-tyty-cast.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust/compile/cast1.rs
  gcc/testsuite/rust/compile/torture/cast1.rs
  gcc/testsuite/rust/compile/torture/cast2.rs
  gcc/testsuite/rust/compile/torture/cast3.rs
Labels: WIP, enhancement

#596 Fix crash when extern function item has no return type
  gcc/rust/ast/rust-ast-full-test.cc
Labels: bug

#597 Add name-resolution and HIR lowering for extern blocks
  gcc/rust/ast/rust-ast.h
  gcc/rust/ast/rust-item.h
  gcc/rust/hir/rust-ast-lower-extern.h
  gcc/rust/hir/rust-ast-lower-item.h
  gcc/rust/hir/tree/rust-hir-full-test.cc
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/resolve/rust-ast-resolve-implitem.h
  gcc/rust/resolve/rust-ast-resolve-item.h
  gcc/rust/resolve/rust-ast-resolve-toplevel.h
  gcc/rust/resolve/rust-ast-resolve.cc
Labels: enhancement

#599 Fix assertion for trait item mappings
  gcc/rust/util/rust-hir-map.cc
Labels: bug

#598 Hello world
  gcc/rust/backend/rust-compile-context.h
  gcc/rust/backend/rust-compile-extern.h
  gcc/rust/backend/rust-compile-item.h
  gcc/rust/backend/rust-compile-tyty.h
  gcc/rust/hir/rust-ast-lower-extern.h
  gcc/rust/hir/rust-ast-lower-item.h
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/resolve/rust-ast-resolve-item.h
  gcc/rust/resolve/rust-ast-resolve.cc
  gcc/rust/rust-backend.h
  gcc/rust/rust-gcc.cc
  gcc/rust/typecheck/rust-hir-type-check-implitem.h
  gcc/rust/typecheck/rust-hir-type-check-toplevel.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/rust/util/rust-hir-map.cc
  gcc/rust/util/rust-hir-map.h
  gcc/testsuite/rust/execute/torture/helloworld1.rs
  gcc/testsuite/rust/execute/torture/helloworld2.rs
Labels: enhancement

#600 Use correct lookahead to peek after 'while' token when parsing expression with block (parse_expr_with_block).
  gcc/rust/parse/rust-parse-impl.h
Labels: bug
