Repository Rust-GCC/gccrs, pull requests merged in 2021-02, with the labels that each got.

#202 Split out the integer inference variable tests
  gcc/testsuite/rust.test/compilable/integer_inference_var1.rs
  gcc/testsuite/rust.test/compilable/integer_inference_var2.rs
  gcc/testsuite/rust.test/compilable/integer_inference_var3.rs
  gcc/testsuite/rust.test/compilable/integer_inference_var4.rs
  gcc/testsuite/rust.test/compilable/integer_inference_var5.rs
  gcc/testsuite/rust.test/compilable/ints_infer1.rs
Labels: cleanup, testsuite

#207 Enforce Duplicate definition rules
  gcc/rust/resolve/rust-ast-resolve-implitem.h
  gcc/rust/resolve/rust-ast-resolve-toplevel.h
  gcc/rust/resolve/rust-ast-resolve.cc
  gcc/rust/resolve/rust-name-resolver.h
  gcc/testsuite/rust.test/compilable/name_resolve1.rs
  gcc/testsuite/rust.test/fail_compilation/redef_error1.rs
  gcc/testsuite/rust.test/fail_compilation/redef_error2.rs
  gcc/testsuite/rust.test/fail_compilation/redef_error3.rs
  gcc/testsuite/rust.test/fail_compilation/redef_error4.rs
  gcc/testsuite/rust.test/fail_compilation/redef_error5.rs
Labels: bug, cleanup

#210 This adds support for basic BlockExpressions
  gcc/rust/backend/rust-compile-base.h
  gcc/rust/backend/rust-compile-block.h
  gcc/rust/backend/rust-compile-context.h
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/backend/rust-compile-implitem.h
  gcc/rust/backend/rust-compile-item.h
  gcc/rust/backend/rust-compile-stmt.h
  gcc/rust/backend/rust-compile.cc
  gcc/rust/hir/tree/rust-hir-expr.h
  gcc/rust/typecheck/rust-hir-type-check.cc
  gcc/testsuite/rust.test/compilable/block_expr1.rs
Labels: cleanup, enhancement

#206 Move scan for unused names to be after type resolution
  gcc/rust/resolve/rust-ast-resolve-item.h
  gcc/rust/resolve/rust-ast-resolve-unused.h
  gcc/rust/resolve/rust-ast-resolve.cc
  gcc/rust/resolve/rust-name-resolver.h
  gcc/rust/rust-session-manager.cc
  gcc/rust/rust-session-manager.h
Labels: bug, cleanup

#209 Fix overloaded virtual and unused parameters warnings
  gcc/rust/backend/rust-compile-context.h
  gcc/rust/backend/rust-compile-tyty.h
  gcc/rust/resolve/rust-ast-resolve-base.h
  gcc/rust/typecheck/rust-hir-type-check-base.h
  gcc/rust/typecheck/rust-hir-type-check-item.h
  gcc/rust/typecheck/rust-tycheck-dump.h
Labels: cleanup

#211 With the merge of BlockExprs
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check-implitem.h
  gcc/rust/typecheck/rust-hir-type-check-item.h
  gcc/rust/typecheck/rust-hir-type-check-stmt.h
  gcc/rust/typecheck/rust-hir-type-check.cc
  gcc/testsuite/rust.test/compilable/block_expr2.rs
Labels: bug

#215 Conditional blocks with else can resolve into a non unit type expression
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/testsuite/rust.test/compilable/block_expr3.rs
  gcc/testsuite/rust.test/compilable/if_elif_else_expr1.rs
Labels: bug

#216 Fixes parsing if expressions as part of an expression.
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/parse/rust-parse.h
  gcc/testsuite/rust.test/compilable/block_expr_parser_bug.rs
Labels: bug

#218 Fix bad type resolution for CallExpr when fn is not simply PathInExpression
  gcc/rust/backend/rust-compile.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/testsuite/rust.test/compilable/function_reference3.rs
Labels: bug

#221 Fix parsing |= as a compound assignment expression.
  gcc/rust/parse/rust-parse-impl.h
  gcc/testsuite/rust.test/compilable/compound_assignment_expr1.rs
Labels: bug

#222 Enable -frust-dump-all option for debugging
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/parse/rust-parse.h
  gcc/rust/rust-session-manager.cc
  gcc/rust/rust-session-manager.h
  gcc/rust/typecheck/rust-tycheck-dump.h
Labels: cleanup, debug

#227 Changes to AST structure in preparation for macro expansion and cleanup
  gcc/rust/ast/rust-ast-full-test.cc
  gcc/rust/ast/rust-ast.h
  gcc/rust/ast/rust-expr.h
  gcc/rust/ast/rust-item.h
  gcc/rust/ast/rust-macro.h
  gcc/rust/ast/rust-path.h
  gcc/rust/expand/rust-macro-expand.cc
  gcc/rust/expand/rust-macro-expand.h
  gcc/rust/lex/rust-token.h
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/resolve/rust-ast-resolve.cc
  gcc/rust/rust-session-manager.cc
Labels: cleanup, enhancement

#231 Add ReferenceType with BorrowExpr and DereferenceExpr
  gcc/rust/ast/rust-expr.h
  gcc/rust/ast/rust-type.h
  gcc/rust/backend/rust-compile-context.h
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/backend/rust-compile-tyty.h
  gcc/rust/hir/rust-ast-lower-expr.h
  gcc/rust/hir/rust-ast-lower-type.h
  gcc/rust/hir/tree/rust-hir-expr.h
  gcc/rust/hir/tree/rust-hir-type.h
  gcc/rust/resolve/rust-ast-resolve-expr.h
  gcc/rust/resolve/rust-ast-resolve-type.h
  gcc/rust/rust-backend.h
  gcc/rust/rust-gcc.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check-stmt.h
  gcc/rust/typecheck/rust-hir-type-check-type.h
  gcc/rust/typecheck/rust-hir-type-check.cc
  gcc/rust/typecheck/rust-tyctx.cc
  gcc/rust/typecheck/rust-tyty-call.h
  gcc/rust/typecheck/rust-tyty-rules.h
  gcc/rust/typecheck/rust-tyty-visitor.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust.test/compilable/borrow1.rs
  gcc/testsuite/rust.test/compilable/deref1.rs
Labels: enhancement

#244 remove ast/clone-test.h
  gcc/rust/ast/clone-test.h
Labels: cleanup

#245 Add debug interface to GCC debug_tree on GENERIC graphs
  gcc/rust/rust-backend.h
  gcc/rust/rust-gcc.cc
Labels: GCC, debug, enhancement
