Repository Rust-GCC/gccrs, pull requests merged in 2022-09, with the labels that each got.

#1522 Add testcases to test folding
  gcc/rust/typecheck/rust-hir-type-check-stmt.cc
  gcc/testsuite/rust/compile/const6.rs
  gcc/testsuite/rust/compile/const7.rs
Labels: bug

#1526 backend: correctly formulate the exit condition
  gcc/rust/backend/rust-compile-expr.cc
  gcc/testsuite/rust/execute/torture/loop-condition-eval.rs
Labels: bug

#1528 add testcase with struct to test component_ref and constructor codes in eval_constant_expression()
  gcc/testsuite/rust/compile/const8.rs
Labels: enhancement

#1541 Static const eval safety
  gcc/rust/backend/rust-compile-item.cc
  gcc/rust/backend/rust-tree.cc
  gcc/rust/typecheck/rust-hir-type-check-toplevel.cc
  gcc/testsuite/rust/compile/rust-const-blog-issue.rs
Labels: bug

#1532 attributes: Add #[macro_use] as builtin
  gcc/rust/util/rust-attributes.cc
  gcc/testsuite/rust/compile/macro_export_1.rs
Labels: bug

#1521 expand: eager evaluate macros inside builtin macros
  gcc/rust/ast/rust-ast.h
  gcc/rust/ast/rust-expr.h
  gcc/rust/expand/rust-macro-builtins.cc
  gcc/rust/expand/rust-macro-expand.cc
  gcc/testsuite/rust/compile/builtin_macro_concat.rs
  gcc/testsuite/rust/compile/builtin_macro_env.rs
  gcc/testsuite/rust/compile/builtin_macro_recurse.rs
Labels: bug, enhancement, cleanup

#1551 Add catch for recusive type queries
  gcc/rust/typecheck/rust-hir-type-check-base.cc
  gcc/rust/typecheck/rust-hir-type-check.h
  gcc/rust/typecheck/rust-tyty-bounds.cc
Labels: bug
