Repository Rust-GCC/gccrs, pull requests merged in 2022-05, with the labels that each got.

#1191 Resolve simple paths in use items
  gcc/rust/ast/rust-ast.h
  gcc/rust/ast/rust-item.h
  gcc/rust/resolve/rust-ast-resolve-item.cc
  gcc/rust/resolve/rust-ast-resolve-item.h
  gcc/rust/resolve/rust-ast-resolve-type.cc
  gcc/rust/resolve/rust-ast-resolve-type.h
  gcc/rust/rust-lang.cc
  gcc/rust/rust-session-manager.cc
  gcc/testsuite/rust/compile/torture/cfg_attr.rs
  gcc/testsuite/rust/compile/use_1.rs
Labels: enhancement

#1201 Generic functions should not be TREE_PUBLIC
  gcc/rust/backend/rust-compile-base.cc
  gcc/rust/backend/rust-compile-base.h
Labels: bug, enhancement

#1199 Add new as_name interface for Dynamic types
  gcc/rust/typecheck/rust-tyty-bounds.cc
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
Labels: enhancement, cleanup

#1197 Support recursive coercion sites
  gcc/rust/backend/rust-compile-base.cc
  gcc/rust/backend/rust-compile-base.h
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-implitem.cc
  gcc/rust/backend/rust-compile-item.cc
  gcc/rust/backend/rust-compile-resolve-path.cc
  gcc/rust/backend/rust-compile.cc
Labels: bug

#1214 Replace SSH cloning with HTTPS cloning in README.md
  README.md
Labels: enhancement

#1205 Take advantage of OBJ_TYPE_REF'S in dyn calls
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/backend/rust-compile-type.cc
  gcc/rust/backend/rust-compile.cc
Labels: enhancement

#1202 Resolve module visibility properly
  gcc/rust/Make-lang.in
  gcc/rust/hir/rust-ast-lower-item.cc
  gcc/rust/hir/rust-ast-lower-item.h
  gcc/rust/hir/rust-ast-lower.cc
  gcc/rust/hir/tree/rust-hir-full-test.cc
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/hir/tree/rust-hir-path.h
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/privacy/rust-privacy-check.cc
  gcc/rust/privacy/rust-privacy-common.h
  gcc/rust/privacy/rust-visibility-resolver.cc
  gcc/rust/privacy/rust-visibility-resolver.h
  gcc/rust/util/rust-hir-map.cc
  gcc/rust/util/rust-hir-map.h
  gcc/testsuite/rust/compile/pub_restricted_1.rs
Labels: enhancement

#1216 ast: lower: Refactor ASTLowerItem in its own source file
  gcc/rust/hir/rust-ast-lower-item.cc
  gcc/rust/hir/rust-ast-lower-item.h
Labels: cleanup

#1220 Ensure the coercion sites are applied correctly on unions
  gcc/rust/backend/rust-compile-expr.h
Labels: bug

#1221 Ensure we don't return error_mark_node for loop expressions
  gcc/rust/backend/rust-compile-expr.h
Labels: bug

#1219 Add `Optional<T>` type
  gcc/rust/Make-lang.in
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/rust-lang.cc
  gcc/rust/util/rust-make-unique.h
  gcc/rust/util/rust-optional.h
Labels: enhancement

#1238 Assigning members to structures is a coercion site
  gcc/rust/typecheck/rust-hir-type-check-struct.cc
  gcc/testsuite/rust/compile/issue-1235.rs
Labels: bug

#1218 Lower IfLet expressions
  gcc/rust/hir/rust-ast-lower-block.h
  gcc/rust/hir/rust-ast-lower.cc
Labels: enhancement

#1242 Remove undefined behavior in context vector
  gcc/rust/expand/rust-attribute-visitor.cc
  gcc/rust/expand/rust-macro-expand.h
  gcc/testsuite/rust/compile/macro-issue1233.rs
Labels: bug

#1244 Allow match on integer and char types
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-pattern.cc
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust/execute/torture/match_byte1.rs
  gcc/testsuite/rust/execute/torture/match_char1.rs
  gcc/testsuite/rust/execute/torture/match_int1.rs
Labels: enhancement

#1248 Support RangePatterns in matches
  gcc/rust/ast/rust-pattern.h
  gcc/rust/backend/rust-compile-pattern.cc
  gcc/rust/backend/rust-compile-pattern.h
  gcc/rust/hir/rust-ast-lower-base.cc
  gcc/rust/hir/rust-ast-lower-base.h
  gcc/rust/hir/rust-ast-lower-pattern.cc
  gcc/rust/hir/rust-ast-lower-pattern.h
  gcc/rust/hir/tree/rust-hir-pattern.h
  gcc/rust/resolve/rust-ast-resolve-pattern.cc
  gcc/rust/resolve/rust-ast-resolve-pattern.h
  gcc/rust/typecheck/rust-hir-type-check-pattern.cc
  gcc/rust/typecheck/rust-hir-type-check-pattern.h
  gcc/testsuite/rust/execute/torture/match_range1.rs
  gcc/testsuite/rust/execute/torture/match_range2.rs
Labels: enhancement

#1246 Report simple privacy violations
  gcc/rust/Make-lang.in
  gcc/rust/privacy/rust-privacy-check.cc
  gcc/rust/privacy/rust-privacy-common.h
  gcc/rust/privacy/rust-privacy-reporter.cc
  gcc/rust/privacy/rust-privacy-reporter.h
  gcc/rust/privacy/rust-pub-restricted-visitor.cc
  gcc/rust/privacy/rust-pub-restricted-visitor.h
  gcc/rust/privacy/rust-visibility-resolver.cc
  gcc/rust/privacy/rust-visibility-resolver.h
  gcc/rust/resolve/rust-ast-resolve-base.h
  gcc/rust/resolve/rust-ast-resolve-item.cc
  gcc/rust/resolve/rust-ast-resolve-toplevel.h
  gcc/rust/resolve/rust-ast-resolve.cc
  gcc/rust/util/rust-hir-map.cc
  gcc/rust/util/rust-hir-map.h
  gcc/rust/util/rust-optional-test.cc
  gcc/rust/util/rust-optional.h
  gcc/testsuite/rust/compile/privacy1.rs
  gcc/testsuite/rust/compile/pub_restricted_3.rs
Labels: enhancement

#1255 Privacy report expressions
  gcc/rust/privacy/rust-privacy-reporter.cc
  gcc/rust/privacy/rust-privacy-reporter.h
  gcc/testsuite/rust/compile/privacy3.rs
  gcc/testsuite/rust/compile/privacy4.rs
Labels: enhancement

#1258 Report privacy errors on explicit types
  gcc/rust/hir/tree/rust-hir.h
  gcc/rust/privacy/rust-privacy-check.cc
  gcc/rust/privacy/rust-privacy-reporter.cc
  gcc/rust/privacy/rust-privacy-reporter.h
  gcc/rust/util/rust-hir-map.cc
  gcc/rust/util/rust-hir-map.h
  gcc/testsuite/rust/compile/privacy5.rs
  gcc/testsuite/rust/compile/privacy6.rs
Labels: enhancement

#1265 Canonicalize types based on hashing than HirIds and TyTy equality
  gcc/rust/Make-lang.in
  gcc/rust/backend/rust-compile-block.h
  gcc/rust/backend/rust-compile-context.cc
  gcc/rust/backend/rust-compile-context.h
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/backend/rust-compile-resolve-path.h
  gcc/rust/backend/rust-compile-stmt.h
  gcc/rust/backend/rust-compile-struct-field-expr.h
  gcc/rust/backend/rust-compile-type.cc
  gcc/rust/backend/rust-compile-type.h
  gcc/rust/backend/rust-compile-tyty.h
  gcc/rust/backend/rust-mangle.h
Labels: bug, enhancement

#1266 Make TyTy::BaseType::destructure recursive
  gcc/rust/backend/rust-compile-type.cc
  gcc/rust/backend/rust-compile-type.h
  gcc/rust/lang.opt
  gcc/rust/typecheck/rust-tyty.cc
Labels: bug, enhancement

#1276 Wrapup testing code within CHECKING_P guards
  gcc/rust/util/rust-optional-test.cc
Labels: cleanup

#1277 Reuse index_expr_ty type
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
Labels: bug

#1279 Implement type checking for the `IfLet` expression.
  gcc/rust/hir/tree/rust-hir-expr.h
  gcc/rust/typecheck/rust-hir-type-check-expr.h
Labels: enhancement

#1275 Remove old hack to handle type inferencing in untyped decalred bindings
  gcc/rust/typecheck/rust-hir-type-check-expr.h
Labels: bug

#1283 const folding in gccrs: remove ConstCtx class.
  gcc/rust/backend/rust-compile-base.cc
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/backend/rust-compile-pattern.cc
  gcc/rust/backend/rust-compile-resolve-path.cc
  gcc/rust/backend/rust-compile-type.cc
  gcc/rust/backend/rust-constexpr.cc
  gcc/rust/backend/rust-constexpr.h
Labels: enhancement
