Repository Rust-GCC/gccrs, pull requests merged in 2022-08, with the labels that each got.

#1429 expand: correctly handles non-macro nodes
  gcc/rust/expand/rust-macro-expand.h
  gcc/testsuite/rust/compile/macro-issue1403.rs
Labels: bug

#1430 hir: more conformant builtin macro detection
  gcc/rust/util/rust-hir-map.cc
  gcc/testsuite/rust/compile/builtin_macro_compile_error.rs
  gcc/testsuite/rust/compile/builtin_macro_concat.rs
  gcc/testsuite/rust/compile/builtin_macro_env.rs
  gcc/testsuite/rust/compile/builtin_macro_include_bytes.rs
  gcc/testsuite/rust/compile/builtin_macro_include_str.rs
  gcc/testsuite/rust/compile/macro42.rs
  gcc/testsuite/rust/execute/torture/builtin_macro_cfg.rs
  gcc/testsuite/rust/execute/torture/builtin_macro_concat.rs
  gcc/testsuite/rust/execute/torture/builtin_macro_env.rs
  gcc/testsuite/rust/execute/torture/builtin_macro_include_bytes.rs
  gcc/testsuite/rust/execute/torture/builtin_macro_include_str.rs
  gcc/testsuite/rust/execute/torture/builtin_macro_line.rs
  gcc/testsuite/rust/execute/torture/builtin_macros1.rs
  gcc/testsuite/rust/execute/torture/builtin_macros3.rs
  gcc/testsuite/rust/execute/torture/macros29.rs
  gcc/testsuite/rust/execute/torture/macros30.rs
  gcc/testsuite/rust/execute/torture/macros31.rs
Labels: bug

#1433 Fix bad transmute for aggregate types
  gcc/rust/backend/rust-compile-intrinsic.cc
  gcc/testsuite/rust/compile/torture/issue-1432.rs
Labels: bug

#1431 Incremental refactor for better coercion site support
  gcc/rust/Make-lang.in
  gcc/rust/backend/rust-compile-base.cc
  gcc/rust/backend/rust-compile-base.h
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/backend/rust-compile-extern.h
  gcc/rust/backend/rust-compile-implitem.cc
  gcc/rust/backend/rust-compile-item.cc
  gcc/rust/backend/rust-compile-resolve-path.cc
  gcc/rust/backend/rust-compile-stmt.h
  gcc/rust/backend/rust-compile.cc
  gcc/rust/hir/tree/rust-hir-expr.h
  gcc/rust/rust-backend.h
  gcc/rust/rust-gcc.cc
  gcc/rust/typecheck/rust-autoderef.cc
  gcc/rust/typecheck/rust-autoderef.h
  gcc/rust/typecheck/rust-coercion.cc
  gcc/rust/typecheck/rust-coercion.h
  gcc/rust/typecheck/rust-hir-dot-operator.cc
  gcc/rust/typecheck/rust-hir-dot-operator.h
  gcc/rust/typecheck/rust-hir-type-check-base.cc
  gcc/rust/typecheck/rust-hir-type-check-base.h
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check-stmt.h
  gcc/rust/typecheck/rust-hir-type-check-struct.cc
  gcc/rust/typecheck/rust-tyty-call.cc
  gcc/rust/typecheck/rust-tyty-cmp.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/testsuite/rust/compile/generics4.rs
  gcc/testsuite/rust/compile/reference1.rs
  gcc/testsuite/rust/compile/shadow1.rs
  gcc/testsuite/rust/compile/type-bindings1.rs
  gcc/testsuite/rust/execute/torture/issue-1198.rs
Labels: bug, enhancement, cleanup

#1437 Array index access does not need to unsize to a slice for access
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/testsuite/rust/compile/usize1.rs
  gcc/testsuite/rust/execute/torture/issue-1436.rs
Labels: bug

#1438 Enhance #1426 "Invalid recursive :stmt expansion in fragment specifiers" test case
  gcc/testsuite/rust/compile/torture/macro-issue1426.rs
Labels: cleanup

#1445 compile: Move and rename `SimpleIntrinsics` -> BuiltinsContext
  gcc/rust/backend/rust-builtins.h
  gcc/rust/backend/rust-compile-intrinsic.cc
  gcc/rust/backend/rust-compile-intrinsic.h
Labels: enhancement, cleanup

#1454 intrinsics: Refactor compilation of intrinsics
  gcc/rust/backend/rust-compile-intrinsic.cc
  gcc/testsuite/rust/compile/torture/intrinsics-2.rs
Labels: cleanup

#1452 transmute: Fix behavior by always performing the raw copy
  gcc/rust/backend/rust-compile-intrinsic.cc
  gcc/testsuite/rust/execute/torture/transmute1.rs
Labels: bug, enhancement, debug

#1453 Add in -m32,-m64 configuration to make check-rust
  .github/bors.toml
  .github/workflows/ccpp.yml
  gcc/testsuite/rust/compile/torture/issue-1432.rs
  gcc/testsuite/rust/debug/win64-abi.rs
Labels: plan, GCC, CI

#1462 Ensure we set TREE_SIDE_EFFECTS on call expressions
  gcc/rust/rust-gcc.cc
Labels: bug

#1468 Revert "Ensure we set TREE_SIDE_EFFECTS on call expressions"
  gcc/rust/rust-gcc.cc
Labels: cleanup

#1466 Dont return error_mark_node on bad CallExpr arguments
  gcc/rust/rust-gcc.cc
Labels: cleanup

#1459 intrinsics: Add copy_nonoverlapping<T>
  gcc/rust/backend/rust-builtins.h
  gcc/rust/backend/rust-compile-intrinsic.cc
  gcc/testsuite/rust/execute/torture/copy_nonoverlapping1.rs
Labels: enhancement

#1474 unsafe: Allow calls to safe intrinsics
  gcc/rust/checks/errors/rust-unsafe-checker.cc
  gcc/testsuite/rust/compile/unsafe10.rs
Labels: enhancement

#1492 Redo coercion site code
  gcc/rust/backend/rust-compile-base.h
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile.cc
  gcc/rust/typecheck/rust-autoderef.cc
  gcc/rust/typecheck/rust-autoderef.h
  gcc/rust/typecheck/rust-coercion.cc
  gcc/rust/typecheck/rust-coercion.h
  gcc/rust/typecheck/rust-hir-type-check-base.cc
  gcc/rust/typecheck/rust-hir-type-check-struct.cc
  gcc/rust/typecheck/rust-tyty-call.cc
  gcc/rust/typecheck/rust-tyty-coercion.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
Labels: bug, Rust Integrations, cleanup

#1493 Fix ICE in dyn impl block
  gcc/rust/resolve/rust-ast-resolve-item.cc
  gcc/rust/resolve/rust-ast-resolve-path.cc
  gcc/rust/resolve/rust-ast-resolve-type.cc
  gcc/rust/resolve/rust-ast-resolve-type.h
  gcc/rust/typecheck/rust-hir-type-check-path.cc
  gcc/testsuite/rust/execute/torture/issue-1249.rs
Labels: bug

#1500 Remove missed target hooks code
  gcc/config/aarch64/aarch64-rust.cc
  gcc/config/alpha/alpha-rust.cc
  gcc/config/arc/arc-rust.cc
  gcc/config/arm/arm-rust.cc
  gcc/config/c6x/c6x-rust.cc
  gcc/config/cr16/cr16-rust.cc
  gcc/config/csky/csky-rust.cc
  gcc/config/default-rust.cc
  gcc/config/epiphany/epiphany-rust.cc
  gcc/config/frv/frv-rust.cc
  gcc/config/i386/i386-rust.cc
  gcc/config/ia64/ia64-rust.cc
  gcc/config/m68k/m68k-rust.cc
  gcc/config/mips/mips-rust.cc
  gcc/config/nds32/nds32-rust.cc
  gcc/config/nios2/nios2-rust.cc
  gcc/config/nvptx/nvptx-rust.cc
  gcc/config/or1k/or1k-rust.cc
  gcc/config/pa/pa-rust.cc
  gcc/config/pdp11/pdp11-rust.cc
  gcc/config/riscv/riscv-rust.cc
  gcc/config/rs6000/rs6000-rust.cc
  gcc/config/rx/rx-rust.cc
  gcc/config/s390/s390-rust.cc
  gcc/config/sh/sh-rust.cc
  gcc/config/sparc/sparc-rust.cc
  gcc/config/v850/v850-rust.cc
Labels: GCC

#1497 Refactor our casts to follow the Rustc implemention
  gcc/rust/Make-lang.in
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/typecheck/rust-casts.cc
  gcc/rust/typecheck/rust-casts.h
  gcc/rust/typecheck/rust-coercion.cc
  gcc/rust/typecheck/rust-coercion.h
  gcc/rust/typecheck/rust-hir-type-check-base.cc
  gcc/rust/typecheck/rust-hir-type-check-base.h
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/rust/typecheck/rust-hir-type-check.h
  gcc/rust/typecheck/rust-tyty-cast.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust/execute/torture/issue-1496.rs
Labels: bug, cleanup

#1473 Improve AST dump
  gcc/rust/ast/rust-ast-dump.cc
  gcc/rust/ast/rust-ast-dump.h
  gcc/rust/rust-session-manager.cc
  gcc/rust/rust-session-manager.h
Labels: enhancement, cleanup

#1499 Constant folding in gccrs: port over rest of the code from CP frontend
  gcc/rust/backend/rust-compile-base.cc
  gcc/rust/backend/rust-compile-intrinsic.cc
  gcc/rust/backend/rust-constexpr.cc
  gcc/rust/backend/rust-constexpr.h
  gcc/rust/backend/rust-tree.cc
  gcc/rust/backend/rust-tree.h
  gcc/testsuite/rust/compile/const4.rs
  gcc/testsuite/rust/compile/const5.rs
Labels: GCC, important, gsoc

#1507 Desugar double borrows into two HIR:BorrowExpr's
  gcc/rust/hir/rust-ast-lower-expr.h
  gcc/rust/hir/tree/rust-hir-expr.h
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/testsuite/rust/compile/torture/issue-1506.rs
Labels: bug

#1509 constexpr: Fix warning in sorry fmt string
  gcc/rust/backend/rust-constexpr.cc
Labels: enhancement

#1512 Add missing language selection for rs6000
  gcc/config/rs6000/rs6000-logue.cc
Labels: bug

#1510 rustc_attrs: Allow `rustc_inherit_overflow_checks` as a builtin attribute
  gcc/rust/util/rust-attributes.cc
  gcc/testsuite/rust/compile/rustc_attr1.rs
Labels: enhancement

#1513 macros: Handle matchers properly in repetitions
  gcc/rust/expand/rust-macro-expand.cc
  gcc/rust/expand/rust-macro-expand.h
  gcc/testsuite/rust/compile/macro43.rs
Labels: bug, enhancement

#1514 Fix SEGV in transcribe_type when compiling libcore 1.29
  gcc/rust/ast/rust-ast-dump.h
  gcc/rust/ast/rust-ast.h
  gcc/rust/expand/rust-attribute-visitor.cc
  gcc/rust/expand/rust-macro-expand.cc
Labels: bug, enhancement

#1517 Refactor error handling on unify
  gcc/rust/typecheck/rust-autoderef.cc
  gcc/rust/typecheck/rust-coercion.cc
  gcc/rust/typecheck/rust-hir-dot-operator.cc
  gcc/rust/typecheck/rust-hir-trait-resolve.cc
  gcc/rust/typecheck/rust-hir-type-check-base.cc
  gcc/rust/typecheck/rust-hir-type-check-base.h
  gcc/rust/typecheck/rust-hir-type-check-enumitem.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check-implitem.cc
  gcc/rust/typecheck/rust-hir-type-check-item.cc
  gcc/rust/typecheck/rust-hir-type-check-path.cc
  gcc/rust/typecheck/rust-hir-type-check-pattern.cc
  gcc/rust/typecheck/rust-hir-type-check-stmt.cc
  gcc/rust/typecheck/rust-hir-type-check-struct.cc
  gcc/rust/typecheck/rust-hir-type-check-toplevel.cc
  gcc/rust/typecheck/rust-hir-type-check-type.cc
  gcc/rust/typecheck/rust-hir-type-check.cc
  gcc/rust/typecheck/rust-tyctx.cc
  gcc/rust/typecheck/rust-tyty-call.cc
  gcc/rust/typecheck/rust-tyty-cmp.h
  gcc/rust/typecheck/rust-tyty-rules.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust/compile/issue-1152.rs
  gcc/testsuite/rust/compile/tuple1.rs
  gcc/testsuite/rust/compile/type-alias1.rs
  gcc/testsuite/rust/execute/torture/operator_overload_9.rs
  gcc/testsuite/rust/execute/torture/slice1.rs
Labels: cleanup

#1505 Create canonical process of compiling constant items
  gcc/rust/backend/rust-compile-base.cc
  gcc/rust/backend/rust-tree.cc
Labels: bug, cleanup

#1519 Fix generic substitution on unit structs
  gcc/rust/typecheck/rust-hir-trait-resolve.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/rust/typecheck/rust-tyty-bounds.cc
  gcc/rust/typecheck/rust-tyty.h
Labels: bug
