Repository Rust-GCC/gccrs, pull requests merged in 2022-04, with the labels that each got.

#1083 bugfix: fix several minor issues
  gcc/rust/ast/rust-ast-full-test.cc
  gcc/rust/rust-session-manager.cc
Labels: bug

#1087 Use loop to initialize repeat arrays
  gcc/rust/backend/rust-compile-context.h
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-item.cc
  gcc/rust/rust-backend.h
  gcc/rust/rust-gcc.cc
  gcc/testsuite/rust/compile/torture/arrays5.rs
  gcc/testsuite/rust/compile/torture/arrays6.rs
Labels: enhancement

#1092 gcc/rust/Make-lang.in: add missing rust compiler driver
  gcc/rust/Make-lang.in
Labels: bug, enhancement, makefile

#1100 Add known lang item const_slice_ptr mappings
  gcc/rust/util/rust-lang-item.h
Labels: enhancement

#1091 Add -frust-edition flag and possible values
  gcc/rust/lang.opt
  gcc/rust/rust-session-manager.cc
  gcc/rust/rust-session-manager.h
Labels: enhancement

#1086 Slice support
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile.cc
  gcc/rust/typecheck/rust-hir-dot-operator.cc
  gcc/rust/typecheck/rust-hir-dot-operator.h
  gcc/rust/typecheck/rust-hir-trait-ref.h
  gcc/rust/typecheck/rust-hir-trait-resolve.cc
  gcc/rust/typecheck/rust-hir-trait-resolve.h
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check-item.h
  gcc/rust/typecheck/rust-hir-type-check-path.cc
  gcc/rust/typecheck/rust-substitution-mapper.cc
  gcc/rust/typecheck/rust-substitution-mapper.h
  gcc/rust/typecheck/rust-tyty-bounds.cc
  gcc/rust/typecheck/rust-tyty-cmp.h
  gcc/rust/typecheck/rust-tyty-coercion.h
  gcc/rust/typecheck/rust-tyty-rules.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust/compile/torture/traits19.rs
  gcc/testsuite/rust/execute/torture/slice-magic.rs
  gcc/testsuite/rust/execute/torture/slice-magic2.rs
Labels: bug, enhancement

#1103 Lower AST::Visibility to HIR::Visibility properly
  gcc/rust/ast/rust-item.h
  gcc/rust/backend/rust-compile-base.cc
  gcc/rust/backend/rust-compile-implitem.cc
  gcc/rust/hir/rust-ast-lower-enumitem.h
  gcc/rust/hir/rust-ast-lower-extern.h
  gcc/rust/hir/rust-ast-lower-implitem.h
  gcc/rust/hir/rust-ast-lower-item.h
  gcc/rust/hir/rust-ast-lower-stmt.h
  gcc/rust/hir/rust-ast-lower.cc
  gcc/rust/hir/rust-ast-lower.h
  gcc/rust/hir/tree/rust-hir-full-test.cc
  gcc/rust/hir/tree/rust-hir-item.h
Labels: enhancement

#1106 macros: fix an infinite loop in `concat!` macro parser
  gcc/rust/expand/rust-macro-builtins.cc
  gcc/testsuite/rust/compile/builtin_macro_concat.rs
Labels: bug, enhancement

#1082 Add base for privacy visitor
  gcc/rust/Make-lang.in
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/hir/tree/rust-hir.h
  gcc/rust/privacy/rust-privacy-check.cc
  gcc/rust/privacy/rust-privacy-check.h
  gcc/rust/privacy/rust-privacy-ctx.cc
  gcc/rust/privacy/rust-privacy-ctx.h
  gcc/rust/privacy/rust-reachability.cc
  gcc/rust/privacy/rust-reachability.h
  gcc/rust/rust-lang.cc
  gcc/rust/rust-session-manager.cc
  gcc/rust/typecheck/rust-hir-type-check.h
  gcc/rust/typecheck/rust-tyctx.cc
  gcc/rust/util/rust-mapping-common.h
Labels: enhancement

#1112 rust: Clang/macOS Testing
  .github/workflows/ccpp.yml
Labels: automation

#1114 rust: Use -Otarget when building and logging warnings
  .github/workflows/ccpp.yml
Labels: enhancement, CI

#1111 Add AST Private Visibilities
  gcc/rust/ast/rust-ast-full-test.cc
  gcc/rust/ast/rust-item.h
  gcc/rust/hir/rust-ast-lower.cc
  gcc/rust/parse/rust-parse-impl.h
Labels: enhancement

#1088 rust-session-manager: better crate name handling logic
  gcc/rust/rust-lang.cc
  gcc/rust/rust-session-manager.cc
  gcc/rust/rust-session-manager.h
  gcc/testsuite/rust/compile/bad-crate-name.rs
  gcc/testsuite/rust/compile/bad=file-name.rs
  gcc/testsuite/rust/compile/bad_file_name.txt.rs
  gcc/testsuite/rust/compile/canonical_paths1.rs
  gcc/testsuite/rust/compile/infer-crate-name.rs
  gcc/testsuite/rust/compile/specify-crate-name.rs
  gcc/testsuite/rust/compile/torture/struct_decl.rs
  gcc/testsuite/rust/compile/traits9.rs
Labels: enhancement

#1113 macros: Add env! macro
  gcc/rust/expand/rust-macro-builtins.cc
  gcc/rust/expand/rust-macro-builtins.h
  gcc/rust/util/rust-hir-map.cc
  gcc/testsuite/rust/compile/builtin_macro_env.rs
  gcc/testsuite/rust/execute/torture/builtin_macro_env.rs
Labels: enhancement

#1110 Add Reachability visitors for items with generics
  gcc/rust/privacy/rust-reachability.cc
  gcc/rust/privacy/rust-reachability.h
Labels: enhancement

#1107 tests: Improve timeout handling
  gcc/testsuite/lib/rust.exp
  gcc/testsuite/rust/compile/xfail/macro_return.rs
Labels: enhancement

#1118 Add reachability visitor to Enum variants
  gcc/rust/hir/tree/rust-hir-full-test.cc
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/privacy/rust-reachability.cc
Labels: enhancement

#1122 testsuite/rust: fix test case failure on macOS
  gcc/testsuite/rust/compile/xfail/macro_return.rs
Labels: CI

#1096 macros: add include! macro
  gcc/rust/expand/rust-macro-builtins.cc
  gcc/rust/expand/rust-macro-builtins.h
  gcc/rust/rust-session-manager.h
  gcc/rust/util/rust-hir-map.cc
Labels: enhancement

#1124 CI: do not push Docker image in a fork
  .github/workflows/docker.yml
Labels: CI

#1121 Fix bad projection substitution
  gcc/rust/typecheck/rust-hir-trait-ref.h
  gcc/rust/typecheck/rust-hir-trait-resolve.cc
  gcc/rust/typecheck/rust-hir-type-check-implitem.h
  gcc/rust/typecheck/rust-hir-type-check-item.h
  gcc/rust/typecheck/rust-hir-type-check.h
  gcc/rust/typecheck/rust-substitution-mapper.h
  gcc/rust/typecheck/rust-tyty-bounds.cc
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust/compile/traits9.rs
  gcc/testsuite/rust/execute/torture/issue-1120.rs
Labels: bug

#1134 Fix ICE during HIR lowering of ExprWithBlock MatchExpr
  gcc/rust/hir/rust-ast-lower-block.h
  gcc/rust/hir/rust-ast-lower-expr.h
  gcc/rust/hir/rust-ast-lower.cc
  gcc/testsuite/rust/execute/torture/issue-858.rs
Labels: bug

#1137 ast: lower: Split rust-lower-base in its own source file
  gcc/rust/Make-lang.in
  gcc/rust/hir/rust-ast-lower-base.cc
  gcc/rust/hir/rust-ast-lower-base.h
  gcc/rust/hir/rust-ast-lower.cc
Labels: cleanup

#1138 Support pattern bindings within function signitures
  gcc/rust/Make-lang.in
  gcc/rust/backend/rust-compile-fnparam.cc
  gcc/rust/backend/rust-compile-fnparam.h
  gcc/rust/backend/rust-compile-pattern.cc
  gcc/rust/backend/rust-compile-pattern.h
  gcc/rust/typecheck/rust-hir-type-check-implitem.h
  gcc/rust/typecheck/rust-hir-type-check-pattern.cc
  gcc/rust/typecheck/rust-hir-type-check-stmt.h
  gcc/rust/typecheck/rust-hir-type-check-toplevel.h
  gcc/rust/typecheck/rust-hir-type-check.cc
  gcc/testsuite/rust/execute/torture/issue-995.rs
Labels: bug

#1119 Add a test for the cfg!() macro
  gcc/testsuite/rust/execute/torture/builtin_macro_cfg.rs
Labels: enhancement, testsuite

#1144 Add name and type resolution support TuplePatterns in MatchArms
  gcc/rust/ast/rust-ast-full-test.cc
  gcc/rust/ast/rust-pattern.h
  gcc/rust/ast/rust-stmt.h
  gcc/rust/hir/rust-ast-lower-base.cc
  gcc/rust/hir/rust-ast-lower-base.h
  gcc/rust/hir/rust-ast-lower-expr.h
  gcc/rust/hir/rust-ast-lower-pattern.cc
  gcc/rust/hir/rust-ast-lower-pattern.h
  gcc/rust/hir/tree/rust-hir-expr.h
  gcc/rust/hir/tree/rust-hir-full-test.cc
  gcc/rust/hir/tree/rust-hir-pattern.h
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/resolve/rust-ast-resolve-pattern.cc
  gcc/rust/resolve/rust-ast-resolve-pattern.h
  gcc/rust/typecheck/rust-hir-type-check-base.cc
  gcc/rust/typecheck/rust-hir-type-check-base.h
  gcc/rust/typecheck/rust-hir-type-check-enumitem.h
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check-pattern.cc
  gcc/rust/typecheck/rust-hir-type-check-pattern.h
Labels: bug

#1139 hir: improve doc attribute handling
  gcc/rust/hir/rust-ast-lower-base.cc
  gcc/rust/hir/rust-ast-lower-base.h
  gcc/rust/util/rust-attributes.cc
  gcc/testsuite/rust/compile/torture/doc_comment.rs
Labels: enhancement

#1145 Fix generic param redefined bug
  gcc/rust/resolve/rust-ast-resolve-item.h
  gcc/testsuite/rust/compile/issue-1131.rs
Labels: bug

#1147 Add missing coercion rule from array to slice
  gcc/rust/typecheck/rust-tyty-coercion.h
  gcc/testsuite/rust/compile/issue-1129-1.rs
  gcc/testsuite/rust/compile/issue-1129-2.rs
Labels: bug

#1148 backend: handle cold attribute
  gcc/rust/backend/rust-compile-base.cc
  gcc/rust/backend/rust-compile-base.h
  gcc/rust/util/rust-attributes.cc
  gcc/testsuite/rust/compile/attr_cold.rs
Labels: enhancement

#1154 Add support for isize and usize type-hints
  gcc/rust/typecheck/rust-hir-type-check-base.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/testsuite/rust/compile/issue-1152.rs
Labels: bug

#1150 backend: handle link_section attribute
  gcc/rust/backend/rust-compile-base.cc
  gcc/rust/backend/rust-compile-base.h
  gcc/rust/util/rust-attributes.cc
  gcc/testsuite/rust/debug/custom_link_section.rs
Labels: enhancement

#1157 Resolve remaining simple visibilites
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/privacy/rust-visibility-resolver.cc
  gcc/rust/privacy/rust-visibility-resolver.h
Labels: enhancement

#1149 backend: handle no_mangle attribute
  gcc/rust/backend/rust-compile-base.cc
  gcc/rust/backend/rust-compile-base.h
  gcc/rust/util/rust-attributes.cc
  gcc/testsuite/rust/debug/no_mangle.rs
Labels: enhancement

#1156 tests/attr_cold: fix a typo
  gcc/testsuite/rust/compile/attr_cold.rs
Labels: bug

#1160 Refactor name resolver
  gcc/rust/Make-lang.in
  gcc/rust/backend/rust-compile-base.cc
  gcc/rust/resolve/rust-ast-resolve.cc
  gcc/rust/resolve/rust-name-resolver.cc
  gcc/rust/resolve/rust-name-resolver.h
Labels: cleanup

#1161 Implement macro expansion for ComparisonExpr, LazyBooleanExpr, AssignmentExpr
  gcc/rust/expand/rust-attribute-visitor.cc
  gcc/testsuite/rust/execute/torture/macros29.rs
  gcc/testsuite/rust/execute/torture/macros30.rs
  gcc/testsuite/rust/execute/torture/macros31.rs
Labels: bug

#1164 Add `NodeId`s to `SimplePath{Segment}`s
  gcc/rust/ast/rust-ast.h
  gcc/rust/ast/rust-item.h
Labels: enhancement

#1166 Support inference of generic parameters on paths behind reference's
  gcc/rust/parse/rust-parse-impl.h
  gcc/testsuite/rust/compile/issue-1165.rs
Labels: bug

#1171 Dockerfile: change base image
  Dockerfile
Labels: bug, automation

#1174 Remove default location for `SimplePath`s
  gcc/rust/ast/rust-ast-full-test.cc
  gcc/rust/ast/rust-ast.h
  gcc/rust/hir/rust-ast-lower.cc
  gcc/rust/rust-session-manager.cc
Labels: enhancement

#1176 Keep `SimplePath{Segment}`s in mappings
  gcc/rust/util/rust-hir-map.cc
  gcc/rust/util/rust-hir-map.h
Labels: enhancement

#1163 rust-session-manager: handle `crate_name` attribute
  gcc/rust/rust-session-manager.cc
  gcc/rust/rust-session-manager.h
  gcc/rust/util/rust-hir-map.h
  gcc/testsuite/rust/compile/attr-mismatch-crate-name.rs
  gcc/testsuite/rust/compile/mismatch-crate-name.rs
Labels: enhancement

#1184 Fix bad name resolution on path with generic segments
  gcc/rust/hir/tree/rust-hir-path.h
  gcc/rust/resolve/rust-ast-resolve-type.h
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check-path.cc
  gcc/rust/typecheck/rust-hir-type-check.cc
  gcc/rust/typecheck/rust-tyty-rules.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust/compile/issue-1173.rs
Labels: bug

#1186 Refactor `ResolvePath` in its own file
  gcc/rust/Make-lang.in
  gcc/rust/resolve/rust-ast-resolve-expr.cc
  gcc/rust/resolve/rust-ast-resolve-expr.h
  gcc/rust/resolve/rust-ast-resolve-path.cc
  gcc/rust/resolve/rust-ast-resolve-path.h
  gcc/rust/resolve/rust-ast-resolve-pattern.cc
  gcc/rust/resolve/rust-ast-resolve.cc
Labels: cleanup

#1189 Add missing `SimplePath`s location
  gcc/rust/ast/rust-ast-full-test.cc
  gcc/rust/ast/rust-item.h
  gcc/rust/ast/rust-macro.h
  gcc/rust/hir/rust-ast-lower.cc
  gcc/rust/parse/rust-parse-impl.h
Labels: enhancement

#1188 Support align and packed repr layout on structs
  gcc/rust/backend/rust-compile-type.cc
  gcc/rust/typecheck/rust-hir-type-check-base.cc
  gcc/rust/typecheck/rust-hir-type-check-base.h
  gcc/rust/typecheck/rust-hir-type-check-stmt.h
  gcc/rust/typecheck/rust-hir-type-check-toplevel.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/rust/util/rust-attributes.cc
  gcc/testsuite/rust/compile/struct_align1.rs
  gcc/testsuite/rust/compile/struct_align2.rs
  gcc/testsuite/rust/compile/struct_pack1.rs
  gcc/testsuite/rust/compile/struct_pack2.rs
Labels: enhancement
