Repository Rust-GCC/gccrs, pull requests merged in 2022-01, with the labels that each got.

#847 HIR::ImplBlock items should mangle based from their canonical path's
  gcc/rust/backend/rust-compile-context.h
  gcc/rust/backend/rust-compile-implitem.h
  gcc/rust/backend/rust-mangle.cc
  gcc/rust/backend/rust-mangle.h
  gcc/testsuite/rust/execute/torture/issue-845.rs
Labels: bug

#848 Add missing bitwise lang items for operator overloading
  gcc/rust/util/rust-hir-map.h
  gcc/testsuite/rust/execute/torture/operator_overload_11.rs
  gcc/testsuite/rust/execute/torture/operator_overload_12.rs
Labels: enhancement

#859 Fix ICE in generic subsitution of enums containing dataless variants
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust/execute/torture/issue-851.rs
Labels: bug

#866 Add support for wildcard patterns within MatchExprs
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-pattern.cc
  gcc/rust/backend/rust-compile-pattern.h
  gcc/rust/hir/rust-ast-lower-pattern.cc
  gcc/rust/hir/rust-ast-lower-pattern.h
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check-pattern.cc
  gcc/rust/typecheck/rust-hir-type-check-pattern.h
  gcc/testsuite/rust/execute/torture/match3.rs
Labels: bug

#860 Add overflow checking on LiteralExpression
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/hir/tree/rust-hir-expr.h
  gcc/rust/typecheck/rust-hir-const-fold.h
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-tycheck-dump.h
  gcc/rust/typecheck/rust-tyty-cast.h
  gcc/testsuite/rust/compile/issue-635-1.rs
  gcc/testsuite/rust/compile/issue-635-2.rs
Labels: bug

#870 Add constant folding to const functions
  gcc/rust/Make-lang.in
  gcc/rust/ast/rust-item.h
  gcc/rust/backend/rust-compile-base.h
  gcc/rust/backend/rust-compile-context.h
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/backend/rust-compile-implitem.h
  gcc/rust/backend/rust-compile-item.h
  gcc/rust/backend/rust-compile-pattern.cc
  gcc/rust/backend/rust-compile-resolve-path.cc
  gcc/rust/backend/rust-compile-stmt.h
  gcc/rust/backend/rust-compile-type.cc
  gcc/rust/backend/rust-compile-type.h
  gcc/rust/backend/rust-compile.cc
  gcc/rust/backend/rust-constexpr.cc
  gcc/rust/backend/rust-constexpr.h
  gcc/rust/hir/rust-ast-lower-base.h
  gcc/rust/hir/rust-ast-lower-item.h
  gcc/rust/hir/rust-ast-lower.cc
  gcc/rust/hir/tree/rust-hir-expr.h
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/hir/tree/rust-hir.h
  gcc/rust/rust-backend.h
  gcc/rust/rust-gcc.cc
  gcc/rust/rust-session-manager.cc
  gcc/rust/typecheck/rust-hir-const-fold-base.h
  gcc/rust/typecheck/rust-hir-const-fold.cc
  gcc/rust/typecheck/rust-hir-const-fold.h
  gcc/rust/typecheck/rust-hir-type-check-enumitem.h
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check-implitem.h
  gcc/rust/typecheck/rust-hir-type-check-stmt.h
  gcc/rust/typecheck/rust-hir-type-check-toplevel.h
  gcc/rust/typecheck/rust-hir-type-check-type.cc
  gcc/rust/typecheck/rust-hir-type-check.cc
  gcc/rust/typecheck/rust-tyty-cast.h
  gcc/rust/typecheck/rust-tyty-cmp.h
  gcc/rust/typecheck/rust-tyty-coercion.h
  gcc/rust/typecheck/rust-tyty-rules.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust/compile/arrays2.rs
  gcc/testsuite/rust/execute/torture/const_fold1.rs
  gcc/testsuite/rust/execute/torture/const_fold2.rs
Labels: bug, enhancement, GCC

#874 Track end locus of BlockExpr
  gcc/rust/ast/rust-expr.h
  gcc/rust/backend/rust-compile-implitem.h
  gcc/rust/backend/rust-compile-item.h
  gcc/rust/backend/rust-compile.cc
  gcc/rust/hir/rust-ast-lower.cc
  gcc/rust/hir/tree/rust-hir-expr.h
  gcc/rust/parse/rust-parse-impl.h
Labels: bug

#879 Record correct location when compiling ADT types
  gcc/rust/backend/rust-compile-type.cc
  gcc/testsuite/rust/compile/torture/struct_decl.rs
Labels: bug

#880 Covariant types should respect the get_name
  gcc/rust/typecheck/rust-tyty.h
Labels: cleanup

#885 Improve error message for failure in Method resolution
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/testsuite/rust/compile/method1.rs
Labels: bug, enhancement, diagnostic

#883 Extract AsyncConstStatus to be a shared enum between AST and HIR
  gcc/rust/ast/rust-ast-full-test.cc
  gcc/rust/ast/rust-item.h
  gcc/rust/ast/rust-type.h
  gcc/rust/hir/rust-ast-lower-implitem.h
  gcc/rust/hir/rust-ast-lower-stmt.h
  gcc/rust/hir/rust-ast-lower-type.h
  gcc/rust/hir/rust-ast-lower.cc
  gcc/rust/hir/tree/rust-hir-full-test.cc
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/util/rust-common.h
Labels: bug

#873 Method resolution should respect deref lang-items
  gcc/rust/Make-lang.in
  gcc/rust/backend/rust-compile-base.h
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-implitem.h
  gcc/rust/backend/rust-compile-item.h
  gcc/rust/backend/rust-compile-resolve-path.cc
  gcc/rust/backend/rust-compile-resolve-path.h
  gcc/rust/backend/rust-compile-var-decl.h
  gcc/rust/backend/rust-compile.cc
  gcc/rust/typecheck/rust-autoderef.cc
  gcc/rust/typecheck/rust-autoderef.h
  gcc/rust/typecheck/rust-hir-dot-operator.h
  gcc/rust/typecheck/rust-hir-inherent-impl-overlap.h
  gcc/rust/typecheck/rust-hir-path-probe.h
  gcc/rust/typecheck/rust-hir-trait-ref.h
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check-implitem.h
  gcc/rust/typecheck/rust-hir-type-check-item.h
  gcc/rust/typecheck/rust-hir-type-check.h
  gcc/rust/typecheck/rust-tyty-bounds.cc
  gcc/rust/typecheck/rust-tyty-cmp.h
  gcc/rust/typecheck/rust-tyty-rules.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust/execute/torture/method2.rs
Labels: bug, enhancement

#891 Remove hack to handle forward declared items
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/backend/rust-compile-extern.h
  gcc/rust/backend/rust-compile-implitem.h
  gcc/rust/backend/rust-compile-item.h
  gcc/rust/backend/rust-compile-resolve-path.cc
  gcc/rust/backend/rust-compile.cc
Labels: cleanup

#899 Add -frust-cfg=value option for adding config options
  gcc/rust/hir/rust-ast-lower-item.h
  gcc/rust/lang.opt
  gcc/rust/resolve/rust-ast-resolve-item.h
  gcc/rust/resolve/rust-ast-resolve-toplevel.h
  gcc/rust/rust-session-manager.cc
  gcc/rust/rust-session-manager.h
  gcc/testsuite/rust/compile/cfg1.rs
  gcc/testsuite/rust/execute/torture/cfg1.rs
Labels: enhancement

#900 Fixup logic in canonical-path for impl-blocks
  gcc/rust/resolve/rust-ast-resolve-item.h
Labels: cleanup
