Repository Rust-GCC/gccrs, pull requests merged in 2022-02, with the labels that each got.

#904 Apply the is_marked_for_strip check to the rest of the crate
  gcc/rust/hir/rust-ast-lower-item.h
  gcc/rust/resolve/rust-ast-resolve-implitem.h
  gcc/rust/resolve/rust-ast-resolve-item.h
  gcc/rust/resolve/rust-ast-resolve-stmt.h
  gcc/rust/resolve/rust-ast-resolve-toplevel.h
  gcc/testsuite/rust/execute/torture/cfg2.rs
  gcc/testsuite/rust/execute/torture/cfg3.rs
Labels: enhancement

#903 Add new RustIdent struct to track canonical-path and location info
  gcc/rust/backend/rust-compile-type.cc
  gcc/rust/resolve/rust-ast-resolve.cc
  gcc/rust/typecheck/rust-hir-type-check-enumitem.h
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check-implitem.h
  gcc/rust/typecheck/rust-hir-type-check-stmt.h
  gcc/rust/typecheck/rust-hir-type-check-toplevel.h
  gcc/rust/typecheck/rust-hir-type-check-type.cc
  gcc/rust/typecheck/rust-hir-type-check-type.h
  gcc/rust/typecheck/rust-hir-type-check.cc
  gcc/rust/typecheck/rust-hir-type-check.h
  gcc/rust/typecheck/rust-tyty-cast.h
  gcc/rust/typecheck/rust-tyty-coercion.h
  gcc/rust/typecheck/rust-tyty-rules.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/rust/util/rust-identifier.h
  gcc/testsuite/rust/compile/torture/struct_decl.rs
Labels: cleanup

#907 Support cfg expansions predicates
  gcc/rust/ast/rust-ast-full-test.cc
  gcc/rust/ast/rust-ast.h
  gcc/rust/ast/rust-macro.h
  gcc/testsuite/rust/compile/cfg2.rs
  gcc/testsuite/rust/compile/cfg3.rs
  gcc/testsuite/rust/compile/cfg4.rs
  gcc/testsuite/rust/execute/torture/cfg4.rs
Labels: enhancement

#751 Enable the usage of selftests
  gcc/c-family/c-common.cc
  gcc/c-family/c-common.h
  gcc/diagnostic.cc
  gcc/opt-problem.cc
  gcc/rust/Make-lang.in
  gcc/rust/rust-lang.cc
  gcc/selftest-run-tests.cc
  gcc/selftest.h
Labels: enhancement, GCC

#908 Fix '-Wformat-diag' issue in 'TypeCheckPattern::visit (HIR::TupleStructPattern &pattern)'
  gcc/rust/typecheck/rust-hir-type-check-pattern.cc
  gcc/testsuite/rust/compile/match5.rs
Labels: bug

#888 Added location data to Match Arm and removed unused code
  gcc/rust/ast/rust-expr.h
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/hir/rust-ast-lower-expr.h
  gcc/rust/hir/tree/rust-hir-expr.h
  gcc/rust/parse/rust-parse-impl.h
Labels: bug, enhancement

#909 Add support for key = value pairs on -frust-cfg=
  gcc/rust/rust-session-manager.cc
  gcc/testsuite/rust/compile/cfg5.rs
Labels: enhancement

#911 Refactor to_string from header to impl file
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
Labels: cleanup

#912 Handle generic substitution on path expressions
  gcc/rust/typecheck/rust-hir-type-check-path.cc
  gcc/rust/typecheck/rust-substitution-mapper.cc
  gcc/rust/typecheck/rust-substitution-mapper.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust/compile/torture/issue-893-2.rs
  gcc/testsuite/rust/compile/torture/issue-893.rs
Labels: bug

#917 remove tree addressable context during type checking
  gcc/rust/Make-lang.in
  gcc/rust/backend/rust-compile-base.cc
  gcc/rust/backend/rust-compile-base.h
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/backend/rust-compile-fnparam.h
  gcc/rust/backend/rust-compile-var-decl.h
  gcc/rust/backend/rust-compile.cc
  gcc/rust/rust-backend.h
  gcc/rust/rust-gcc.cc
  gcc/rust/typecheck/rust-hir-address-taken.cc
  gcc/rust/typecheck/rust-hir-address-taken.h
  gcc/rust/typecheck/rust-hir-type-check-expr.h
Labels: cleanup

#918 Refactor code to reuse a canonical way to compile items
  gcc/rust/Make-lang.in
  gcc/rust/backend/rust-compile-base.cc
  gcc/rust/backend/rust-compile-base.h
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/backend/rust-compile-extern.h
  gcc/rust/backend/rust-compile-implitem.cc
  gcc/rust/backend/rust-compile-implitem.h
  gcc/rust/backend/rust-compile-intrinsic.cc
  gcc/rust/backend/rust-compile-item.cc
  gcc/rust/backend/rust-compile-item.h
  gcc/rust/backend/rust-compile-resolve-path.cc
  gcc/rust/backend/rust-compile-resolve-path.h
  gcc/rust/backend/rust-compile-stmt.h
  gcc/rust/backend/rust-compile-var-decl.h
  gcc/rust/backend/rust-compile.cc
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/rust-backend.h
  gcc/rust/rust-gcc.cc
  gcc/rust/rust-session-manager.cc
  gcc/rust/rust-target.h
  gcc/rust/typecheck/rust-tycheck-dump.h
Labels: enhancement, cleanup

#920 Support deref_mut lang item during method resolution
  gcc/rust/Make-lang.in
  gcc/rust/backend/rust-compile-base.h
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/typecheck/rust-autoderef.cc
  gcc/rust/typecheck/rust-autoderef.h
  gcc/rust/typecheck/rust-hir-dot-operator.cc
  gcc/rust/typecheck/rust-hir-dot-operator.h
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/testsuite/rust/execute/torture/method3.rs
  gcc/testsuite/rust/execute/torture/method4.rs
Labels: bug

#922 Support inline never and always options
  gcc/rust/backend/rust-compile-base.cc
  gcc/rust/backend/rust-compile-base.h
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/testsuite/rust/compile/inline_1.rs
  gcc/testsuite/rust/compile/inline_2.rs
Labels: enhancement

#926 macros: Add multiple macro syntax tests
  gcc/testsuite/rust/compile/macro1.rs
  gcc/testsuite/rust/compile/macro2.rs
  gcc/testsuite/rust/compile/macro3.rs
  gcc/testsuite/rust/compile/macro4.rs
  gcc/testsuite/rust/compile/macro5.rs
  gcc/testsuite/rust/execute/xfail/macro1.rs
  gcc/testsuite/rust/execute/xfail/macro2.rs
  gcc/testsuite/rust/execute/xfail/macro3.rs
Labels: important

#931 rust-cfg: Quote option name when erroring out
  gcc/rust/rust-session-manager.cc
Labels: bug

#933 macrotranscriber: Add location info
  gcc/rust/ast/rust-macro.h
  gcc/rust/parse/rust-parse-impl.h
Labels: bug

#932 Add location information to MacroRule
  gcc/rust/ast/rust-macro.h
  gcc/rust/parse/rust-parse-impl.h
Labels: bug

#938 First pass at declarative macro expansion
  gcc/rust/ast/rust-ast-full-test.cc
  gcc/rust/ast/rust-ast.h
  gcc/rust/ast/rust-macro.h
  gcc/rust/expand/rust-macro-expand.cc
  gcc/rust/expand/rust-macro-expand.h
  gcc/rust/hir/rust-ast-lower-expr.h
  gcc/rust/hir/rust-ast-lower-implitem.h
  gcc/rust/hir/rust-ast-lower-item.h
  gcc/rust/hir/rust-ast-lower-stmt.h
  gcc/rust/lex/rust-lex.h
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/parse/rust-parse.cc
  gcc/rust/parse/rust-parse.h
  gcc/rust/resolve/rust-ast-resolve-expr.h
  gcc/rust/resolve/rust-ast-resolve-implitem.h
  gcc/rust/resolve/rust-ast-resolve-item.h
  gcc/rust/resolve/rust-ast-resolve-stmt.h
  gcc/rust/resolve/rust-ast-resolve-toplevel.h
  gcc/rust/resolve/rust-ast-resolve.cc
  gcc/rust/resolve/rust-name-resolver.h
  gcc/rust/typecheck/rust-tycheck-dump.h
  gcc/rust/util/rust-hir-map.cc
  gcc/rust/util/rust-hir-map.h
  gcc/testsuite/rust/execute/torture/macros1.rs
  gcc/testsuite/rust/execute/torture/macros2.rs
  gcc/testsuite/rust/execute/torture/macros3.rs
  gcc/testsuite/rust/execute/torture/macros4.rs
  gcc/testsuite/rust/execute/torture/macros5.rs
  gcc/testsuite/rust/execute/torture/macros6.rs
  gcc/testsuite/rust/execute/xfail/macro2.rs
  gcc/testsuite/rust/execute/xfail/macro3.rs
Labels: enhancement

#940 Add more location info to AST structures
  gcc/rust/ast/rust-expr.h
  gcc/rust/ast/rust-item.h
  gcc/rust/ast/rust-path.h
  gcc/rust/ast/rust-pattern.h
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/parse/rust-parse.h
  gcc/rust/resolve/rust-ast-resolve.cc
Labels: bug, cleanup

#942 Removed Lambda Function within AST::PathPattern
  gcc/rust/ast/rust-path.h
  gcc/rust/hir/rust-ast-lower.cc
Labels: cleanup

#951 Add name resolution to slices
  gcc/rust/Make-lang.in
  gcc/rust/resolve/rust-ast-resolve-expr.cc
  gcc/rust/resolve/rust-ast-resolve-expr.h
  gcc/rust/resolve/rust-ast-resolve-type.cc
  gcc/rust/resolve/rust-ast-resolve-type.h
  gcc/rust/resolve/rust-ast-resolve.cc
Labels: enhancement

#950 Match macro repetitions
  gcc/rust/ast/rust-ast-full-test.cc
  gcc/rust/ast/rust-macro.h
  gcc/rust/expand/rust-macro-expand.cc
  gcc/rust/expand/rust-macro-expand.h
  gcc/rust/parse/rust-parse-impl.h
  gcc/testsuite/rust/compile/macro6.rs
  gcc/testsuite/rust/compile/macro7.rs
  gcc/testsuite/rust/compile/macro8.rs
  gcc/testsuite/rust/execute/torture/macros7.rs
  gcc/testsuite/rust/execute/torture/macros8.rs
  gcc/testsuite/rust/execute/torture/macros9.rs
Labels: enhancement

#955 matched_fragment: Track and set fragment match amount
  gcc/rust/expand/rust-macro-expand.cc
  gcc/rust/expand/rust-macro-expand.h
Labels: enhancement

#953 Refactor lang item mappings
  gcc/rust/Make-lang.in
  gcc/rust/hir/rust-ast-lower-base.h
  gcc/rust/hir/rust-ast-lower-item.h
  gcc/rust/hir/rust-ast-lower.cc
  gcc/rust/typecheck/rust-hir-trait-resolve.h
  gcc/rust/util/rust-attributes.cc
  gcc/rust/util/rust-attributes.h
  gcc/rust/util/rust-hir-map.h
  gcc/rust/util/rust-lang-item.h
Labels: cleanup

#956 Substitute repetitions
  gcc/rust/ast/rust-ast.h
  gcc/rust/expand/rust-macro-expand.cc
  gcc/rust/expand/rust-macro-expand.h
  gcc/testsuite/rust/execute/torture/macros10.rs
  gcc/testsuite/rust/execute/torture/macros11.rs
  gcc/testsuite/rust/execute/torture/macros12.rs
  gcc/testsuite/rust/execute/torture/macros13.rs
  gcc/testsuite/rust/execute/torture/macros14.rs
Labels: enhancement

#974 Add support for ranges and index lang items along with the TyTy::SliceType
  gcc/rust/Make-lang.in
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/backend/rust-compile-type.cc
  gcc/rust/backend/rust-compile-type.h
  gcc/rust/backend/rust-compile-tyty.h
  gcc/rust/hir/rust-ast-lower-expr.h
  gcc/rust/hir/tree/rust-hir-expr.h
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-substitution-mapper.h
  gcc/rust/typecheck/rust-tyty-call.h
  gcc/rust/typecheck/rust-tyty-cast.h
  gcc/rust/typecheck/rust-tyty-cmp.h
  gcc/rust/typecheck/rust-tyty-coercion.h
  gcc/rust/typecheck/rust-tyty-rules.h
  gcc/rust/typecheck/rust-tyty-visitor.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/rust/util/rust-lang-item.h
  gcc/testsuite/rust/compile/torture/range-lang-item1.rs
  gcc/testsuite/rust/compile/usize1.rs
  gcc/testsuite/rust/execute/torture/index1.rs
Labels: enhancement

#970 Add file!() builtin
  gcc/rust/expand/rust-macro-builtins.cc
  gcc/rust/expand/rust-macro-builtins.h
  gcc/rust/util/rust-hir-map.cc
  gcc/testsuite/rust/execute/torture/builtin_macros1.rs
Labels: enhancement

#954 HIR Visitor refactoring
  gcc/rust/backend/rust-compile-base.h
  gcc/rust/backend/rust-compile-block.h
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/backend/rust-compile-extern.h
  gcc/rust/backend/rust-compile-fnparam.h
  gcc/rust/backend/rust-compile-implitem.h
  gcc/rust/backend/rust-compile-item.h
  gcc/rust/backend/rust-compile-pattern.h
  gcc/rust/backend/rust-compile-resolve-path.h
  gcc/rust/backend/rust-compile-stmt.h
  gcc/rust/backend/rust-compile-struct-field-expr.h
  gcc/rust/backend/rust-compile-var-decl.h
  gcc/rust/hir/tree/rust-hir-expr.h
  gcc/rust/hir/tree/rust-hir-full-test.cc
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/hir/tree/rust-hir-path.h
  gcc/rust/hir/tree/rust-hir-pattern.h
  gcc/rust/hir/tree/rust-hir-stmt.h
  gcc/rust/hir/tree/rust-hir-type.h
  gcc/rust/hir/tree/rust-hir-visitor.h
  gcc/rust/hir/tree/rust-hir.h
  gcc/rust/lint/rust-lint-scan-deadcode.h
Labels: cleanup
