Repository Rust-GCC/gccrs, pull requests merged in 2022-10, with the labels that each got.

#1554 testing: try loop in const function
  gcc/testsuite/rust/compile/const9.rs
Labels: testsuite

#1564 builtins: Move implementation into source file
  gcc/rust/Make-lang.in
  gcc/rust/backend/rust-builtins.cc
  gcc/rust/backend/rust-builtins.h
Labels: cleanup

#1560 Fix -Wunused using `rust-lang.cc` hack
  gcc/rust/lang.opt
  gcc/rust/rust-lang.cc
Labels: upstream

#1559 Fix include structure
  gcc/rust/ast/rust-ast-full-test.cc
  gcc/rust/ast/rust-macro.h
  gcc/rust/lex/rust-codepoint.h
  gcc/rust/lex/rust-lex.cc
  gcc/rust/lex/rust-token.cc
  gcc/rust/lex/rust-token.h
  gcc/rust/parse/rust-cfg-parser.h
  gcc/rust/rust-lang.cc
  gcc/rust/rust-object-export.cc
  gcc/rust/util/rust-attributes.cc
  gcc/rust/util/rust-make-unique.h
  gcc/rust/util/rust-optional-test.cc
Labels: upstream

#1565 Implement data prefetch intrinsics
  gcc/rust/backend/rust-builtins.cc
  gcc/rust/backend/rust-compile-intrinsic.cc
  gcc/testsuite/rust/execute/torture/prefetch_data.rs
Labels: enhancement

#1543 Reintroduce targetrustm hooks without the maze of macro definitions in target headers
  .github/bors_log_expected_warnings
  gcc/Makefile.in
  gcc/config.gcc
  gcc/config/darwin-rust.cc
  gcc/config/default-rust.cc
  gcc/config/i386/i386-rust.cc
  gcc/config/i386/i386-rust.h
  gcc/config/i386/t-i386
  gcc/config/t-darwin
  gcc/configure
  gcc/configure.ac
  gcc/doc/tm.texi
  gcc/doc/tm.texi.in
  gcc/genhooks.cc
  gcc/rust/rust-lang.cc
  gcc/rust/rust-session-manager.cc
  gcc/rust/rust-target-def.h
  gcc/rust/rust-target.def
  gcc/rust/rust-target.h
Labels: enhancement

#1574 fix ICE on missing closing paren
  gcc/rust/parse/rust-parse-impl.h
  gcc/testsuite/rust/compile/missing_closing_paren.rs
Labels: enhancement

#1570 Apply #1560 master
  gcc/rust/lang.opt
  gcc/rust/rust-lang.cc
Labels: enhancement

#1584 Add missing lang item mappings
  gcc/rust/util/rust-abi.cc
  gcc/rust/util/rust-lang-item.h
Labels: enhancement

#1583 Support type resolution on super traits on dyn objects
  gcc/rust/backend/rust-compile.cc
  gcc/rust/typecheck/rust-hir-trait-ref.h
  gcc/rust/typecheck/rust-tyty.cc
Labels: bug

#1587 Method resolution must support multiple candidates
  gcc/rust/typecheck/rust-autoderef.cc
  gcc/rust/typecheck/rust-hir-dot-operator.cc
  gcc/rust/typecheck/rust-hir-dot-operator.h
  gcc/rust/typecheck/rust-hir-inherent-impl-overlap.h
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/rust/typecheck/rust-tyty-cmp.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust/compile/generics7.rs
  gcc/testsuite/rust/execute/torture/operator_overload_9.rs
Labels: enhancement

#1590 AST: more dump improvements
  gcc/rust/ast/rust-ast-dump.cc
Labels: enhancement, cleanup

#1548 Dump module items
  gcc/rust/ast/rust-ast-dump.cc
Labels: enhancement

#1593 ast: dump TypeAlias
  gcc/rust/ast/rust-ast-dump.cc
Labels: enhancement, debug

#1599 [25/37] rust-privacy-reporter: Add copyright header
  gcc/rust/checks/errors/privacy/rust-privacy-reporter.cc
Labels: upstream

#1598 [10/37] rust-cfg-parser: Add copyright header
  gcc/rust/parse/rust-cfg-parser.cc
Labels: upstream

#1602 Add check for recursive trait cycles
  gcc/rust/typecheck/rust-hir-trait-resolve.cc
  gcc/rust/typecheck/rust-hir-type-check.h
  gcc/testsuite/rust/compile/issue-1589.rs
Labels: bug

#1605 [33/37] lang-specs: Rename language spec @rs -> @rust
  gcc/rust/lang-specs.h
Labels: upstream

#1549 Dump macro declarations properly
  gcc/rust/ast/rust-ast-dump.cc
  gcc/rust/ast/rust-ast-dump.h
  gcc/rust/ast/rust-macro.h
Labels: enhancement

#1608 Initial support for closures
  gcc/rust/Make-lang.in
  gcc/rust/ast/rust-expr.h
  gcc/rust/ast/rust-path.h
  gcc/rust/backend/rust-compile-block.h
  gcc/rust/backend/rust-compile-context.h
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/backend/rust-compile-type.cc
  gcc/rust/backend/rust-mangle.cc
  gcc/rust/backend/rust-tree.h
  gcc/rust/checks/errors/privacy/rust-privacy-reporter.cc
  gcc/rust/checks/errors/privacy/rust-privacy-reporter.h
  gcc/rust/checks/errors/rust-const-checker.cc
  gcc/rust/checks/errors/rust-const-checker.h
  gcc/rust/checks/errors/rust-unsafe-checker.cc
  gcc/rust/checks/errors/rust-unsafe-checker.h
  gcc/rust/checks/lints/rust-lint-marklive.h
  gcc/rust/hir/rust-ast-lower-base.cc
  gcc/rust/hir/rust-ast-lower-base.h
  gcc/rust/hir/rust-ast-lower-expr.cc
  gcc/rust/hir/rust-ast-lower-expr.h
  gcc/rust/hir/rust-ast-lower-pattern.cc
  gcc/rust/hir/rust-ast-lower-pattern.h
  gcc/rust/hir/rust-ast-lower-type.cc
  gcc/rust/hir/rust-ast-lower-type.h
  gcc/rust/hir/rust-ast-lower.cc
  gcc/rust/hir/rust-hir-dump.cc
  gcc/rust/hir/rust-hir-dump.h
  gcc/rust/hir/tree/rust-hir-expr.h
  gcc/rust/hir/tree/rust-hir-full-decls.h
  gcc/rust/hir/tree/rust-hir-full-test.cc
  gcc/rust/hir/tree/rust-hir-path.h
  gcc/rust/hir/tree/rust-hir-visitor.h
  gcc/rust/hir/tree/rust-hir.h
  gcc/rust/resolve/rust-ast-resolve-expr.cc
  gcc/rust/resolve/rust-ast-resolve-expr.h
  gcc/rust/resolve/rust-ast-resolve-type.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check.h
  gcc/rust/typecheck/rust-tyctx.cc
  gcc/rust/typecheck/rust-tyty-bounds.cc
  gcc/rust/typecheck/rust-tyty-call.cc
  gcc/rust/typecheck/rust-tyty-call.h
  gcc/rust/typecheck/rust-tyty-cmp.h
  gcc/rust/typecheck/rust-tyty-rules.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/rust/util/rust-lang-item.h
  gcc/testsuite/rust/execute/torture/closure1.rs
  gcc/testsuite/rust/execute/torture/closure2.rs
Labels: enhancement

#1614 intrinsics: Add rust_sorry wrapper for unimplemented intrinsics
  gcc/rust/backend/rust-compile-intrinsic.cc
  gcc/testsuite/rust/compile/torture/intrinsics-3.rs
Labels: enhancement

#1585 Apply #1556 on master
  .github/bors_log_expected_warnings
  .github/workflows/ccpp.yml
  gcc/rust/Make-lang.in
  gcc/rust/backend/rust-constexpr.cc
Labels: upstream

#1615 intrinsics: Add early implementation for atomic_store_{seqcst, relaxed, release}
  gcc/rust/backend/rust-builtins.cc
  gcc/rust/backend/rust-builtins.h
  gcc/rust/backend/rust-compile-intrinsic.cc
  gcc/testsuite/rust/compile/torture/intrinsics-4.rs
  gcc/testsuite/rust/compile/torture/intrinsics-5.rs
  gcc/testsuite/rust/execute/torture/atomic_store.rs
Labels: enhancement

#1619 parser: Fix ICE in closure parsing
  gcc/rust/parse/rust-parse-impl.h
Labels: enhancement

#1618 Add missing copyright headers
  gcc/rust/checks/errors/privacy/rust-privacy-reporter.cc
  gcc/rust/parse/rust-cfg-parser.cc
Labels: enhancement

#1621 intrinsics: Use lambdas for wrapping_<op> intrinsics
  gcc/rust/backend/rust-compile-intrinsic.cc
Labels: cleanup

#1620 Intrinsics unchecked ops
  gcc/rust/backend/rust-compile-intrinsic.cc
  gcc/testsuite/rust/compile/torture/intrinsics-6.rs
  gcc/testsuite/rust/compile/torture/intrinsics-7.rs
Labels: enhancement
