Repository Rust-GCC/gccrs, pull requests merged in 2022-07, with the labels that each got.

#1352 HIR: fixup MatchArm assignment operator
  gcc/rust/hir/tree/rust-hir-expr.h
Labels: bug, enhancement, cleanup

#1346 Support self paths
  gcc/rust/ast/rust-path.h
  gcc/rust/resolve/rust-ast-resolve-path.cc
  gcc/rust/resolve/rust-ast-resolve-type.cc
  gcc/testsuite/rust/compile/self-path1.rs
  gcc/testsuite/rust/compile/self-path2.rs
  gcc/testsuite/rust/execute/torture/issue-1231.rs
Labels: bug, enhancement

#1359 typecheck: Move TypeCheckItem into source and header file
  gcc/rust/Make-lang.in
  gcc/rust/typecheck/rust-hir-type-check-item.cc
  gcc/rust/typecheck/rust-hir-type-check-item.h
Labels: cleanup

#1355 Ambiguous generic arg
  gcc/rust/ast/rust-ast-full-test.cc
  gcc/rust/ast/rust-path.h
  gcc/rust/expand/rust-attribute-visitor.cc
  gcc/rust/hir/rust-ast-lower-base.cc
  gcc/rust/hir/rust-ast-lower-type.h
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/parse/rust-parse.h
  gcc/rust/resolve/rust-ast-resolve-type.cc
  gcc/testsuite/rust/compile/const_generics_2.rs
Labels: enhancement

#1363 Refactor Lexer to support an abstract InputSource class
  gcc/rust/ast/rust-ast-full-test.cc
  gcc/rust/expand/rust-macro-builtins.cc
  gcc/rust/expand/rust-macro-expand.cc
  gcc/rust/lex/rust-lex.cc
  gcc/rust/lex/rust-lex.h
  gcc/rust/parse/rust-cfg-parser.cc
  gcc/rust/parse/rust-parse.h
  gcc/rust/rust-buffered-queue.h
  gcc/rust/rust-session-manager.cc
Labels: bug

#1370 ast: Fix use after move in GenericArg
  gcc/rust/ast/rust-path.h
Labels: bug

#1367 Initial support for matches on tuples
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/hir/tree/rust-hir.h
  gcc/testsuite/rust/execute/torture/match_tuple1.rs
Labels: enhancement

#1356 gccrs const folding port: continue porting potential_constant_expression_1()
  gcc/rust/backend/rust-tree.cc
  gcc/rust/backend/rust-tree.h
Labels: enhancement

#1371 typecheck: Refactor TypeCheckTopLevel class
  gcc/rust/Make-lang.in
  gcc/rust/typecheck/rust-hir-type-check-toplevel.cc
  gcc/rust/typecheck/rust-hir-type-check-toplevel.h
Labels: cleanup

#1366 Refactor mappings class and HIR lowering to be consistent
  gcc/rust/ast/rust-item.h
  gcc/rust/backend/rust-compile-base.cc
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/backend/rust-compile-implitem.cc
  gcc/rust/backend/rust-compile-item.cc
  gcc/rust/backend/rust-compile-resolve-path.cc
  gcc/rust/expand/rust-attribute-visitor.cc
  gcc/rust/expand/rust-macro-expand.cc
  gcc/rust/hir/rust-ast-lower-base.cc
  gcc/rust/hir/rust-ast-lower-block.h
  gcc/rust/hir/rust-ast-lower-enumitem.h
  gcc/rust/hir/rust-ast-lower-expr.h
  gcc/rust/hir/rust-ast-lower-extern.h
  gcc/rust/hir/rust-ast-lower-implitem.h
  gcc/rust/hir/rust-ast-lower-item.cc
  gcc/rust/hir/rust-ast-lower-pattern.cc
  gcc/rust/hir/rust-ast-lower-pattern.h
  gcc/rust/hir/rust-ast-lower-stmt.h
  gcc/rust/hir/rust-ast-lower-struct-field-expr.h
  gcc/rust/hir/rust-ast-lower-type.h
  gcc/rust/hir/rust-ast-lower.cc
  gcc/rust/hir/rust-ast-lower.h
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/hir/tree/rust-hir-path.h
  gcc/rust/hir/tree/rust-hir-stmt.h
  gcc/rust/lint/rust-lint-marklive.cc
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/parse/rust-parse.h
  gcc/rust/privacy/rust-privacy-reporter.cc
  gcc/rust/privacy/rust-visibility-resolver.cc
  gcc/rust/resolve/rust-ast-resolve-implitem.h
  gcc/rust/resolve/rust-ast-resolve-item.cc
  gcc/rust/resolve/rust-ast-resolve-stmt.h
  gcc/rust/resolve/rust-ast-resolve-toplevel.h
  gcc/rust/resolve/rust-ast-resolve-type.cc
  gcc/rust/resolve/rust-ast-resolve-type.h
  gcc/rust/resolve/rust-name-resolver.cc
  gcc/rust/resolve/rust-name-resolver.h
  gcc/rust/rust-session-manager.cc
  gcc/rust/rust-session-manager.h
  gcc/rust/typecheck/rust-hir-trait-resolve.cc
  gcc/rust/typecheck/rust-hir-type-check-enumitem.h
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check-implitem.h
  gcc/rust/typecheck/rust-hir-type-check-path.cc
  gcc/rust/typecheck/rust-hir-type-check-stmt.h
  gcc/rust/typecheck/rust-hir-type-check-toplevel.cc
  gcc/rust/typecheck/rust-hir-type-check-type.cc
  gcc/rust/typecheck/rust-hir-type-check-type.h
  gcc/rust/typecheck/rust-hir-type-check.cc
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/util/rust-attributes.cc
  gcc/rust/util/rust-hir-map.cc
  gcc/rust/util/rust-hir-map.h
Labels: bug, enhancement, cleanup

#1372 typecheck-resolve-type: Move all remaining definitions
  gcc/rust/typecheck/rust-hir-type-check-type.cc
  gcc/rust/typecheck/rust-hir-type-check-type.h
Labels: cleanup

#1374 remove unused go code
  gcc/rust/rust-object-export.cc
Labels: cleanup

#1375 backend: properly handles foreign ABIs
  gcc/rust/backend/rust-compile-base.cc
  gcc/rust/util/rust-abi.cc
  gcc/rust/util/rust-abi.h
  gcc/testsuite/rust/debug/win64-abi.rs
Labels: cleanup

#1379 backend: explain why cdecl is treated differently when setting up the ABIs
  gcc/rust/backend/rust-compile-base.cc
Labels: cleanup, documentation

#1384 Support generics in check for valid types in arithmetic expressions
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/testsuite/rust/compile/issue-1383.rs
Labels: bug

#1362 extern crate loading
  gcc/rust/Make-lang.in
  gcc/rust/ast/rust-ast-dump.cc
  gcc/rust/ast/rust-ast-dump.h
  gcc/rust/expand/rust-attribute-visitor.cc
  gcc/rust/lang.opt
  gcc/rust/metadata/rust-export-metadata.cc
  gcc/rust/metadata/rust-export-metadata.h
  gcc/rust/metadata/rust-extern-crate.cc
  gcc/rust/metadata/rust-extern-crate.h
  gcc/rust/metadata/rust-import-archive.cc
  gcc/rust/metadata/rust-imports.cc
  gcc/rust/metadata/rust-imports.h
  gcc/rust/resolve/rust-ast-resolve-toplevel.h
  gcc/rust/rust-object-export.cc
  gcc/rust/rust-session-manager.cc
  gcc/rust/rust-session-manager.h
  gcc/testsuite/rust/link/generic_function_0.rs
  gcc/testsuite/rust/link/generic_function_1.rs
  gcc/testsuite/rust/link/link.exp
  gcc/testsuite/rust/link/simple_function_0.rs
  gcc/testsuite/rust/link/simple_function_1.rs
  gcc/testsuite/rust/link/trait_import_0.rs
  gcc/testsuite/rust/link/trait_import_1.rs
Labels: enhancement

#1391 Fix ICE on duplicate compilation of ExternBlock items
  gcc/rust/backend/rust-compile-extern.h
  gcc/testsuite/rust/compile/issue-1323-1.rs
  gcc/testsuite/rust/compile/issue-1323-2.rs
Labels: bug

#1373 Typecheck const generic params
  gcc/rust/hir/rust-hir-dump.cc
  gcc/rust/hir/rust-hir-dump.h
  gcc/rust/hir/tree/rust-hir-full-decls.h
  gcc/rust/hir/tree/rust-hir-visitor.h
  gcc/rust/hir/tree/rust-hir.h
  gcc/rust/typecheck/rust-hir-type-check-toplevel.cc
  gcc/testsuite/rust/compile/const_generics_6.rs
Labels: enhancement

#1392 Ensure we parse any inner item attributes when expanding a module
  gcc/rust/ast/rust-ast-full-test.cc
  gcc/rust/parse/rust-parse.h
  gcc/testsuite/rust/compile/issue-1089.rs
  gcc/testsuite/rust/compile/test_mod.rs
Labels: bug

#1394 Fix parsing grammer of grouped expressions as the block tail expression
  gcc/rust/parse/rust-parse-impl.h
  gcc/testsuite/rust/compile/issue-1393.rs
Labels: bug

#1397 lexer: Allow specifiying tokens as reserved in certain editions
  gcc/rust/lex/rust-lex.cc
  gcc/rust/rust-session-manager.h
  gcc/testsuite/rust/compile/macro-issue1395-2.rs
  gcc/testsuite/rust/compile/macro-issue1395.rs
Labels: enhancement

#1404 'gcc/testsuite/rust/link/link.exp': Fix 'runtest_file_p' usage
  gcc/testsuite/rust/link/link.exp
Labels: enhancement, testsuite

#1401 macros: properly handles recursive macros
  gcc/rust/expand/rust-attribute-visitor.cc
  gcc/rust/expand/rust-macro-expand.cc
  gcc/rust/expand/rust-macro-expand.h
  gcc/testsuite/rust/compile/macro_return.rs
  gcc/testsuite/rust/compile/torture/macro_as_expr.rs
Labels: enhancement

#1405 Allow repeating metavars alongside repetitions
  gcc/rust/expand/rust-macro-expand.cc
  gcc/rust/expand/rust-macro-expand.h
  gcc/rust/expand/rust-macro-substitute-ctx.cc
  gcc/testsuite/rust/compile/macro-issue1400-2.rs
  gcc/testsuite/rust/compile/macro-issue1400.rs
Labels: bug

#1409 checks: Refactor project architecture for checking passes
  gcc/rust/Make-lang.in
  gcc/rust/checks/errors/privacy/rust-privacy-check.cc
  gcc/rust/checks/errors/privacy/rust-privacy-check.h
  gcc/rust/checks/errors/privacy/rust-privacy-common.h
  gcc/rust/checks/errors/privacy/rust-privacy-ctx.cc
  gcc/rust/checks/errors/privacy/rust-privacy-ctx.h
  gcc/rust/checks/errors/privacy/rust-privacy-reporter.cc
  gcc/rust/checks/errors/privacy/rust-privacy-reporter.h
  gcc/rust/checks/errors/privacy/rust-pub-restricted-visitor.cc
  gcc/rust/checks/errors/privacy/rust-pub-restricted-visitor.h
  gcc/rust/checks/errors/privacy/rust-reachability.cc
  gcc/rust/checks/errors/privacy/rust-reachability.h
  gcc/rust/checks/errors/privacy/rust-visibility-resolver.cc
  gcc/rust/checks/errors/privacy/rust-visibility-resolver.h
  gcc/rust/checks/lints/rust-lint-marklive-base.h
  gcc/rust/checks/lints/rust-lint-marklive.cc
  gcc/rust/checks/lints/rust-lint-marklive.h
  gcc/rust/checks/lints/rust-lint-scan-deadcode.h
  gcc/rust/checks/lints/rust-lint-unused-var.cc
  gcc/rust/checks/lints/rust-lint-unused-var.h
Labels: cleanup

#1406 Add Attribute checking visitor
  gcc/rust/hir/rust-ast-lower-base.cc
  gcc/rust/lex/rust-codepoint.h
  gcc/rust/lex/rust-lex.cc
  gcc/rust/rust-session-manager.cc
  gcc/rust/util/rust-attributes.cc
  gcc/rust/util/rust-attributes.h
  gcc/testsuite/rust/compile/torture/check-doc-attr-string.rs
  gcc/testsuite/rust/compile/torture/undended-string-1.rs
  gcc/testsuite/rust/compile/torture/undended-string-2.rs
Labels: enhancement

#1410 unsafe: Add UnsafeCheck visitor
  gcc/rust/Make-lang.in
  gcc/rust/checks/errors/rust-unsafe-checker.cc
  gcc/rust/checks/errors/rust-unsafe-checker.h
  gcc/rust/hir/tree/rust-hir-expr.h
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/rust-session-manager.cc
  gcc/testsuite/rust/compile/unsafe4.rs
  gcc/testsuite/rust/compile/unsafe5.rs
Labels: enhancement

#1378 hir/dump: simple dumping of crate attrs and adding a few todos
  gcc/rust/hir/rust-hir-dump.cc
  gcc/rust/hir/rust-hir-dump.h
Labels: enhancement

#1417 unsafe: check uses of static variables
  gcc/rust/checks/errors/rust-unsafe-checker.cc
  gcc/rust/checks/errors/rust-unsafe-checker.h
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/hir/tree/rust-hir.h
  gcc/testsuite/rust/compile/unsafe1.rs
  gcc/testsuite/rust/compile/unsafe2.rs
  gcc/testsuite/rust/compile/unsafe3.rs
Labels: enhancement

#1416 unsafe: Add checks for union field accesses
  gcc/rust/checks/errors/rust-unsafe-checker.cc
  gcc/testsuite/rust/compile/unsafe9.rs
Labels: enhancement

#1415 Add generic `StackedContexts<T>` type
  gcc/rust/checks/errors/rust-unsafe-checker.cc
  gcc/rust/checks/errors/rust-unsafe-checker.h
Labels: enhancement, cleanup

#1402 CI Improvements and fixes
  .github/workflows/Remark.yml
Labels: CI

#1421 expand: further improves the handling of recursive macros
  gcc/rust/expand/rust-attribute-visitor.cc
  gcc/rust/expand/rust-attribute-visitor.h
  gcc/testsuite/rust/compile/torture/macro-issue1403.rs
Labels: bug

#1427 unsafe: Check for unsafe function/method calls
  gcc/rust/backend/rust-compile-resolve-path.cc
  gcc/rust/checks/errors/rust-unsafe-checker.cc
  gcc/rust/checks/errors/rust-unsafe-checker.h
  gcc/rust/hir/rust-ast-lower-base.cc
  gcc/rust/hir/rust-ast-lower-extern.h
  gcc/rust/util/rust-hir-map.cc
  gcc/rust/util/rust-hir-map.h
  gcc/testsuite/rust/compile/issue-1173.rs
  gcc/testsuite/rust/compile/torture/intrinsics-1.rs
  gcc/testsuite/rust/compile/torture/transmute-size-check-1.rs
  gcc/testsuite/rust/compile/torture/transmute1.rs
  gcc/testsuite/rust/compile/unsafe6.rs
  gcc/testsuite/rust/compile/unsafe7.rs
  gcc/testsuite/rust/compile/unsafe8.rs
  gcc/testsuite/rust/execute/torture/builtin_macro_cfg.rs
  gcc/testsuite/rust/execute/torture/builtin_macro_concat.rs
  gcc/testsuite/rust/execute/torture/builtin_macro_env.rs
  gcc/testsuite/rust/execute/torture/builtin_macro_include_bytes.rs
  gcc/testsuite/rust/execute/torture/builtin_macro_include_str.rs
  gcc/testsuite/rust/execute/torture/builtin_macro_line.rs
  gcc/testsuite/rust/execute/torture/builtin_macros1.rs
  gcc/testsuite/rust/execute/torture/builtin_macros3.rs
  gcc/testsuite/rust/execute/torture/macros10.rs
  gcc/testsuite/rust/execute/torture/macros12.rs
  gcc/testsuite/rust/execute/torture/macros13.rs
  gcc/testsuite/rust/execute/torture/macros14.rs
  gcc/testsuite/rust/execute/torture/macros22.rs
  gcc/testsuite/rust/execute/torture/macros29.rs
  gcc/testsuite/rust/execute/torture/macros30.rs
  gcc/testsuite/rust/execute/torture/macros31.rs
  gcc/testsuite/rust/execute/torture/match_bool1.rs
  gcc/testsuite/rust/execute/torture/match_byte1.rs
  gcc/testsuite/rust/execute/torture/match_char1.rs
  gcc/testsuite/rust/execute/torture/match_int1.rs
  gcc/testsuite/rust/execute/torture/match_loop1.rs
  gcc/testsuite/rust/execute/torture/match_range1.rs
  gcc/testsuite/rust/execute/torture/match_range2.rs
  gcc/testsuite/rust/execute/torture/match_tuple1.rs
  gcc/testsuite/rust/link/simple_function_0.rs
Labels: enhancement
