Repository Rust-GCC/gccrs, pull requests merged in 2022-03, with the labels that each got.

#981 macro-expand: Add SubstitutionCtx class in its own file
  gcc/rust/Make-lang.in
  gcc/rust/expand/rust-macro-expand.cc
  gcc/rust/expand/rust-macro-expand.h
  gcc/rust/expand/rust-macro-substitute-ctx.cc
  gcc/rust/expand/rust-macro-substitute-ctx.h
Labels: enhancement

#983 Parse proper cfg values
  gcc/rust/lex/rust-lex.cc
  gcc/rust/lex/rust-lex.h
  gcc/rust/parse/rust-cfg-parser.cc
  gcc/rust/parse/rust-cfg-parser.h
  gcc/rust/rust-session-manager.cc
  gcc/rust/rust-session-manager.h
  gcc/rust/util/rust-hir-map.cc
Labels: enhancement

#988 lexer: Add reference and warning documentation
  gcc/rust/lex/rust-lex.h
Labels: debug

#984 Implimented Soluion 1 and solution 2 for issue_734
  gcc/rust/backend/rust-compile-type.cc
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
Labels: cleanup

#990 Add must use attribute support
  gcc/rust/Make-lang.in
  gcc/rust/backend/rust-compile-base.cc
  gcc/rust/backend/rust-compile-base.h
  gcc/rust/backend/rust-compile-context.h
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/backend/rust-compile-stmt.h
  gcc/rust/backend/rust-compile.cc
  gcc/rust/backend/rust-constexpr.cc
  gcc/rust/backend/rust-tree.cc
  gcc/rust/backend/rust-tree.h
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/hir/tree/rust-hir.h
  gcc/rust/lang.opt
  gcc/rust/rust-backend.h
  gcc/rust/rust-gcc.cc
  gcc/rust/typecheck/rust-hir-type-check-implitem.h
  gcc/rust/util/rust-attributes.cc
  gcc/testsuite/rust/compile/torture/must_use1.rs
  gcc/testsuite/rust/compile/torture/must_use2.rs
Labels: enhancement, GCC, diagnostic

#985 Parse macro!(); as MacroInvocation with semicolon
  gcc/rust/ast/rust-ast-full-decls.h
  gcc/rust/ast/rust-ast-full-test.cc
  gcc/rust/ast/rust-ast-visitor.h
  gcc/rust/ast/rust-ast.h
  gcc/rust/ast/rust-item.h
  gcc/rust/ast/rust-macro.h
  gcc/rust/ast/rust-stmt.h
  gcc/rust/expand/rust-macro-expand.cc
  gcc/rust/expand/rust-macro-expand.h
  gcc/rust/hir/rust-ast-lower-base.h
  gcc/rust/hir/rust-ast-lower-implitem.h
  gcc/rust/hir/rust-ast-lower-item.h
  gcc/rust/hir/rust-ast-lower-stmt.h
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/parse/rust-parse.h
  gcc/rust/resolve/rust-ast-resolve-base.h
  gcc/rust/resolve/rust-ast-resolve-implitem.h
  gcc/rust/resolve/rust-ast-resolve-item.h
  gcc/rust/resolve/rust-ast-resolve-stmt.h
  gcc/rust/resolve/rust-ast-resolve-toplevel.h
Labels: enhancement

#986 Fix ICE on recursive macro invocation
  gcc/rust/expand/rust-macro-substitute-ctx.cc
  gcc/testsuite/rust/execute/torture/macros16.rs
  gcc/testsuite/rust/execute/torture/macros17.rs
  gcc/testsuite/rust/execute/torture/macros18.rs
Labels: bug

#999 Refactor ABI options as part of HIR function qualifiers
  gcc/rust/ast/rust-item.h
  gcc/rust/hir/rust-ast-lower-item.h
  gcc/rust/hir/rust-ast-lower.cc
  gcc/rust/hir/tree/rust-hir-full-test.cc
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/typecheck/rust-hir-type-check-implitem.h
  gcc/testsuite/rust/compile/abi-options1.rs
Labels: diagnostic

#998 Parse macro expansion properly
  gcc/rust/ast/rust-ast.h
  gcc/rust/ast/rust-macro.h
  gcc/rust/expand/rust-macro-expand.cc
  gcc/rust/expand/rust-macro-expand.h
  gcc/rust/hir/rust-ast-lower-expr.h
  gcc/rust/hir/rust-ast-lower-implitem.h
  gcc/rust/hir/rust-ast-lower-item.h
  gcc/rust/hir/rust-ast-lower-stmt.h
  gcc/rust/resolve/rust-ast-resolve-expr.cc
  gcc/rust/resolve/rust-ast-resolve-expr.h
  gcc/rust/resolve/rust-ast-resolve-implitem.h
  gcc/rust/resolve/rust-ast-resolve-item.h
  gcc/rust/resolve/rust-ast-resolve-stmt.h
  gcc/rust/resolve/rust-ast-resolve-toplevel.h
  gcc/testsuite/rust/compile/macro11.rs
  gcc/testsuite/rust/compile/macro12.rs
  gcc/testsuite/rust/compile/macro13.rs
  gcc/testsuite/rust/compile/macro14.rs
  gcc/testsuite/rust/compile/macro15.rs
  gcc/testsuite/rust/compile/macro6.rs
  gcc/testsuite/rust/compile/macro7.rs
  gcc/testsuite/rust/compile/macro8.rs
  gcc/testsuite/rust/execute/torture/macros11.rs
  gcc/testsuite/rust/execute/torture/macros17.rs
  gcc/testsuite/rust/execute/torture/macros2.rs
  gcc/testsuite/rust/execute/torture/macros22.rs
  gcc/testsuite/rust/execute/torture/macros3.rs
  gcc/testsuite/rust/execute/torture/macros7.rs
  gcc/testsuite/rust/execute/torture/macros8.rs
  gcc/testsuite/rust/execute/torture/macros9.rs
Labels: enhancement, WIP

#1002 macros: Add abstraction around multiple matches
  gcc/rust/expand/rust-macro-expand.cc
  gcc/rust/expand/rust-macro-expand.h
  gcc/rust/expand/rust-macro-substitute-ctx.cc
  gcc/rust/expand/rust-macro-substitute-ctx.h
Labels: enhancement

#1003 Add more intrinsics and refactor how we implement them
  gcc/rust/backend/rust-compile-fnparam.h
  gcc/rust/backend/rust-compile-intrinsic.cc
  gcc/rust/backend/rust-compile-resolve-path.cc
  gcc/rust/backend/rust-tree.cc
  gcc/rust/backend/rust-tree.h
  gcc/rust/hir/rust-ast-lower-type.h
  gcc/rust/resolve/rust-ast-resolve-type.cc
  gcc/rust/resolve/rust-ast-resolve-type.h
  gcc/rust/resolve/rust-ast-resolve.cc
  gcc/rust/rust-backend.h
  gcc/rust/rust-gcc.cc
  gcc/rust/typecheck/rust-hir-type-check-type.h
  gcc/testsuite/rust/compile/never_type_err2.rs
Labels: enhancement, cleanup

#1007 Add missing canonicalization of slices and raw pointer types
  gcc/rust/resolve/rust-ast-resolve-type.cc
  gcc/rust/resolve/rust-ast-resolve-type.h
  gcc/testsuite/rust/compile/issue-1005.rs
Labels: bug

#1016 Add missing HIR lowering for SliceTypes
  gcc/rust/hir/rust-ast-lower-type.h
Labels: enhancement

#1017 attr-visitor: Split in its own source and header
  gcc/rust/Make-lang.in
  gcc/rust/expand/rust-attribute-visitor.cc
  gcc/rust/expand/rust-attribute-visitor.h
  gcc/rust/expand/rust-macro-expand.cc
Labels: enhancement

#1004 Added column!() macro
  gcc/rust/expand/rust-macro-builtins.cc
  gcc/rust/expand/rust-macro-builtins.h
  gcc/rust/rust-linemap.cc
  gcc/rust/rust-linemap.h
  gcc/rust/util/rust-hir-map.cc
  gcc/testsuite/rust/execute/torture/builtin_macros3.rs
Labels: enhancement

#1021 macros: Do not try and re-expand if depth has exceeded recursion limit
  gcc/rust/expand/rust-attribute-visitor.cc
  gcc/rust/expand/rust-macro-expand.cc
  gcc/rust/expand/rust-macro-expand.h
  gcc/testsuite/rust/compile/macro17.rs
Labels: enhancement

#1030 Rewrite our unconstrained type-param error checking
  gcc/rust/Make-lang.in
  gcc/rust/hir/tree/rust-hir-path.h
  gcc/rust/typecheck/rust-hir-trait-ref.h
  gcc/rust/typecheck/rust-hir-trait-resolve.h
  gcc/rust/typecheck/rust-hir-type-check-base.cc
  gcc/rust/typecheck/rust-hir-type-check-base.h
  gcc/rust/typecheck/rust-hir-type-check-item.h
  gcc/rust/typecheck/rust-hir-type-check-toplevel.h
  gcc/rust/typecheck/rust-hir-type-check-type.cc
  gcc/rust/typecheck/rust-hir-type-check-type.h
  gcc/rust/typecheck/rust-tyty-bounds.cc
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust/compile/issue-1019.rs
  gcc/testsuite/rust/compile/traits12.rs
Labels: bug

#1037 Support placeholders becoming slices
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check-implitem.h
  gcc/rust/typecheck/rust-tyty-cmp.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/testsuite/rust/compile/issue-1034.rs
Labels: bug

#1029 Macro in trait impl
  gcc/rust/ast/rust-ast.h
  gcc/rust/ast/rust-macro.h
  gcc/rust/expand/rust-attribute-visitor.cc
  gcc/rust/expand/rust-attribute-visitor.h
  gcc/rust/expand/rust-macro-expand.cc
  gcc/rust/expand/rust-macro-expand.h
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/parse/rust-parse.h
  gcc/testsuite/rust/compile/macro20.rs
  gcc/testsuite/rust/compile/macro21.rs
  gcc/testsuite/rust/compile/macro22.rs
  gcc/testsuite/rust/compile/macro23.rs
  gcc/testsuite/rust/execute/torture/macros23.rs
Labels: enhancement

#1042 Parse reserved keywords as valid fragments identifiers
  gcc/rust/parse/rust-parse-impl.h
Labels: bug

#1040 Do not propagate parse errors in match repetitions
  gcc/rust/expand/rust-macro-expand.cc
  gcc/rust/parse/rust-parse.h
  gcc/testsuite/rust/compile/macro25.rs
  gcc/testsuite/rust/compile/macro9.rs
Labels: bug

#1041 macros: Only expand merged repetitions if they contain the same amount
  gcc/rust/expand/rust-macro-substitute-ctx.cc
  gcc/rust/expand/rust-macro-substitute-ctx.h
  gcc/testsuite/rust/compile/macro26.rs
  gcc/testsuite/rust/execute/torture/macros24.rs
Labels: enhancement

#1047 Add helper debugging function for substituted tokens
  gcc/rust/expand/rust-macro-expand.cc
Labels: cleanup

#1044 Restrict follow-up tokens on `expr` and `stmt`
  gcc/rust/ast/rust-ast-full-test.cc
  gcc/rust/ast/rust-macro.h
  gcc/rust/expand/rust-macro-expand.cc
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/parse/rust-parse.cc
  gcc/rust/parse/rust-parse.h
  gcc/testsuite/rust/compile/macro27.rs
  gcc/testsuite/rust/compile/macro28.rs
  gcc/testsuite/rust/compile/macro29.rs
  gcc/testsuite/rust/compile/macro30.rs
  gcc/testsuite/rust/compile/macro31.rs
  gcc/testsuite/rust/execute/torture/macros20.rs
Labels: enhancement

#1049 Add better restrictions around semicolons in statements
  gcc/rust/expand/rust-macro-expand.cc
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/parse/rust-parse.h
  gcc/testsuite/rust/compile/macro18.rs
  gcc/testsuite/rust/compile/macro32.rs
Labels: bug, enhancement

#1051 macros: Add remaining restrictions for follow-set restrictions
  gcc/rust/ast/rust-macro.h
  gcc/rust/lex/rust-token.h
  gcc/rust/parse/rust-parse.cc
  gcc/testsuite/rust/compile/macro33.rs
  gcc/testsuite/rust/compile/macro34.rs
  gcc/testsuite/rust/compile/macro35.rs
  gcc/testsuite/rust/compile/macro36.rs
Labels: enhancement

#1052 Add hints for valid follow tokens
  gcc/rust/parse/rust-parse.cc
  gcc/testsuite/rust/compile/macro27.rs
  gcc/testsuite/rust/compile/macro28.rs
  gcc/testsuite/rust/compile/macro29.rs
  gcc/testsuite/rust/compile/macro30.rs
  gcc/testsuite/rust/compile/macro31.rs
  gcc/testsuite/rust/compile/macro35.rs
Labels: enhancement

#1054 Fix overzealous follow set ambiguity
  gcc/rust/parse/rust-parse.cc
  gcc/testsuite/rust/compile/macro-issue1053-2.rs
  gcc/testsuite/rust/compile/macro-issue1053.rs
  gcc/testsuite/rust/compile/macro28.rs
Labels: bug

#1062 Properly perform follow set checking on matcher
  gcc/rust/parse/rust-parse.cc
  gcc/testsuite/rust/compile/macro39.rs
Labels: enhancement

#1055 Allow keeping list of last matches to check against
  gcc/rust/ast/rust-macro.h
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/parse/rust-parse.cc
  gcc/rust/parse/rust-parse.h
  gcc/testsuite/rust/compile/macro37.rs
  gcc/testsuite/rust/compile/macro38.rs
Labels: enhancement

#1063 Handle :meta fragments properly
  gcc/rust/ast/rust-expr.h
  gcc/rust/expand/rust-attribute-visitor.cc
  gcc/rust/expand/rust-attribute-visitor.h
  gcc/rust/expand/rust-macro-expand.cc
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/parse/rust-parse.h
  gcc/testsuite/rust/execute/torture/cfg5.rs
  gcc/testsuite/rust/execute/torture/macros27.rs
Labels: enhancement

#1066 Fix warning of uninitialized delim_id variable
  gcc/rust/parse/rust-parse.cc
Labels: cleanup

#1059 Add base for build job using older GCC version
  .github/workflows/ccpp.yml
  gcc/rust/typecheck/rust-hir-path-probe.h
Labels: CI

#1069 Handle macro invocations in type contexts
  gcc/rust/ast/rust-ast.h
  gcc/rust/expand/rust-attribute-visitor.cc
  gcc/rust/expand/rust-macro-expand.cc
  gcc/rust/expand/rust-macro-expand.h
  gcc/testsuite/rust/compile/macro40.rs
  gcc/testsuite/rust/execute/torture/macros28.rs
Labels: bug

#1071 Allow transcribing of zero nodes in certain cases
  gcc/rust/ast/rust-ast.h
  gcc/rust/ast/rust-macro.h
  gcc/rust/expand/rust-macro-builtins.cc
  gcc/rust/expand/rust-macro-expand.cc
  gcc/rust/expand/rust-macro-expand.h
  gcc/testsuite/rust/compile/macro41.rs
Labels: bug
