Repository Rust-GCC/gccrs, pull requests merged in 2022-12, with the labels that each got.

#1668 builtins: Remove unused parameter
  gcc/rust/backend/rust-builtins.cc
Labels: CI

#1676 Fix regressions in 32 bit mode and gcc4.8 builds
  gcc/rust/backend/rust-builtins.cc
  gcc/rust/backend/rust-builtins.h
  gcc/rust/backend/rust-compile-base.cc
  gcc/rust/backend/rust-compile-base.h
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/backend/rust-compile-fnparam.cc
  gcc/rust/backend/rust-compile-implitem.h
  gcc/rust/backend/rust-compile-intrinsic.cc
  gcc/rust/backend/rust-compile-pattern.cc
  gcc/rust/backend/rust-compile-resolve-path.cc
  gcc/rust/backend/rust-compile-resolve-path.h
  gcc/rust/backend/rust-compile-type.cc
  gcc/rust/backend/rust-compile.cc
  gcc/rust/backend/rust-constexpr.cc
  gcc/rust/backend/rust-tree.cc
  gcc/rust/checks/errors/privacy/rust-privacy-reporter.cc
  gcc/rust/checks/errors/privacy/rust-reachability.cc
  gcc/rust/checks/errors/privacy/rust-visibility-resolver.cc
  gcc/rust/checks/errors/rust-const-checker.cc
  gcc/rust/checks/errors/rust-unsafe-checker.cc
  gcc/rust/checks/lints/rust-lint-marklive.cc
  gcc/rust/checks/lints/rust-lint-unused-var.cc
  gcc/rust/expand/rust-macro-builtins.cc
  gcc/rust/hir/rust-ast-lower-base.cc
  gcc/rust/hir/rust-hir-dump.cc
  gcc/rust/hir/tree/rust-hir-full-test.cc
  gcc/rust/lex/rust-lex.cc
  gcc/rust/lex/rust-lex.h
  gcc/rust/metadata/rust-export-metadata.cc
  gcc/rust/resolve/rust-ast-resolve-expr.cc
  gcc/rust/resolve/rust-ast-resolve-type.cc
  gcc/rust/resolve/rust-ast-verify-assignee.h
  gcc/rust/resolve/rust-early-name-resolver.cc
  gcc/rust/rust-gcc.cc
  gcc/rust/typecheck/rust-hir-dot-operator.cc
  gcc/rust/typecheck/rust-hir-inherent-impl-overlap.h
  gcc/rust/typecheck/rust-hir-path-probe.cc
  gcc/rust/typecheck/rust-hir-trait-ref.h
  gcc/rust/typecheck/rust-hir-trait-resolve.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check-item.h
  gcc/rust/typecheck/rust-hir-type-check-path.cc
  gcc/rust/typecheck/rust-hir-type-check-pattern.cc
  gcc/rust/typecheck/rust-hir-type-check-stmt.h
  gcc/rust/typecheck/rust-hir-type-check-type.cc
  gcc/rust/typecheck/rust-hir-type-check-type.h
  gcc/rust/typecheck/rust-hir-type-check.cc
  gcc/rust/typecheck/rust-tyty-bounds.cc
  gcc/rust/typecheck/rust-tyty-call.h
  gcc/rust/typecheck/rust-tyty-cmp.h
  gcc/rust/typecheck/rust-tyty-rules.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/util/rust-attributes.cc
  gcc/testsuite/rust/compile/torture/intrinsics-4.rs
  gcc/testsuite/rust/execute/torture/atomic_load.rs
  gcc/testsuite/rust/execute/torture/atomic_store.rs
Labels: bug, GCC, important

#1611 Initial state capture for closures
  gcc/rust/backend/rust-compile-context.cc
  gcc/rust/backend/rust-compile-context.h
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-resolve-path.cc
  gcc/rust/backend/rust-compile-type.cc
  gcc/rust/resolve/rust-ast-resolve-expr.cc
  gcc/rust/resolve/rust-ast-resolve-implitem.h
  gcc/rust/resolve/rust-ast-resolve-item.cc
  gcc/rust/resolve/rust-ast-resolve-pattern.cc
  gcc/rust/resolve/rust-ast-resolve-pattern.h
  gcc/rust/resolve/rust-ast-resolve-stmt.h
  gcc/rust/resolve/rust-ast-resolve-toplevel.h
  gcc/rust/resolve/rust-ast-resolve-type.h
  gcc/rust/resolve/rust-name-resolver.cc
  gcc/rust/resolve/rust-name-resolver.h
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust/execute/torture/closure3.rs
Labels: enhancement

#1632 Fix mac-os regression in apply generic arguments to method calls
  gcc/rust/hir/tree/rust-hir-expr.h
  gcc/rust/hir/tree/rust-hir-full-decls.h
  gcc/rust/hir/tree/rust-hir-path.h
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust/debug/chartype.rs
Labels: bug

#1688 ci: Lock Ubuntu version to 20.04
  .github/workflows/bootstrap.yml
  .github/workflows/ccpp.yml
Labels: CI

#1540 Implement `-frust-incomplete-and-experimental-compiler-do-not-use` flag
  gcc/rust/Make-lang.in
  gcc/rust/lang.opt
  gcc/rust/rust-session-manager.cc
  gcc/testsuite/lib/rust.exp
Labels: GCC, upstream

#1683 backend: Replace double_int_to_tree -> wide_int_to_tree
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/rust-gcc.cc
Labels: upstream

#1681 Backport #1653
  gcc/rust/rust-gcc.cc
Labels: upstream

#1701 Standardize warning flags
  .github/bors_log_expected_warnings
  .github/workflows/bootstrap.yml
  .github/workflows/ccpp.yml
  gcc/rust/Make-lang.in
Labels: upstream

#1704 rust: fix link serialization [PR108113]
  gcc/rust/Make-lang.in
Labels: upstream
