Repository Rust-GCC/gccrs, pull requests merged in 2022-11, with the labels that each got.

#1623 ci: Use same CXXFLAGS in bootstrap workflow
  .github/workflows/bootstrap.yml
Labels: enhancement, CI

#1622 intrinsics: Add atomic_load_*
  gcc/rust/backend/rust-builtins.cc
  gcc/rust/backend/rust-compile-intrinsic.cc
  gcc/testsuite/rust/compile/torture/intrinsics-3.rs
  gcc/testsuite/rust/compile/torture/intrinsics-5.rs
  gcc/testsuite/rust/execute/torture/atomic_load.rs
Labels: enhancement

#1624 Ast dump refactor
  gcc/rust/ast/rust-ast-dump.cc
  gcc/rust/ast/rust-ast-dump.h
Labels: enhancement, cleanup

#1628 typecheck: Fix overzealous `delete` call
  gcc/rust/typecheck/rust-tyty-call.cc
Labels: enhancement

#1635 rust: Remove unused variables and fix dangling references
  gcc/rust/ast/rust-ast-dump.cc
  gcc/rust/backend/rust-compile-base.cc
  gcc/rust/backend/rust-compile-base.h
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/backend/rust-compile-fnparam.cc
  gcc/rust/backend/rust-compile-implitem.h
  gcc/rust/backend/rust-compile-intrinsic.cc
  gcc/rust/backend/rust-compile-pattern.cc
  gcc/rust/backend/rust-compile-resolve-path.cc
  gcc/rust/backend/rust-compile-resolve-path.h
  gcc/rust/backend/rust-compile-type.cc
  gcc/rust/backend/rust-compile.cc
  gcc/rust/backend/rust-constexpr.cc
  gcc/rust/backend/rust-tree.cc
  gcc/rust/checks/errors/privacy/rust-privacy-reporter.cc
  gcc/rust/checks/errors/privacy/rust-reachability.cc
  gcc/rust/checks/errors/privacy/rust-visibility-resolver.cc
  gcc/rust/checks/errors/rust-const-checker.cc
  gcc/rust/checks/errors/rust-unsafe-checker.cc
  gcc/rust/checks/lints/rust-lint-marklive.cc
  gcc/rust/checks/lints/rust-lint-unused-var.cc
  gcc/rust/expand/rust-macro-builtins.cc
  gcc/rust/hir/rust-ast-lower-base.cc
  gcc/rust/hir/rust-hir-dump.cc
  gcc/rust/hir/tree/rust-hir-full-test.cc
  gcc/rust/lex/rust-lex.cc
  gcc/rust/lex/rust-lex.h
  gcc/rust/metadata/rust-export-metadata.cc
  gcc/rust/resolve/rust-ast-resolve-expr.cc
  gcc/rust/resolve/rust-ast-resolve-type.cc
  gcc/rust/resolve/rust-ast-verify-assignee.h
  gcc/rust/resolve/rust-early-name-resolver.cc
  gcc/rust/typecheck/rust-hir-dot-operator.cc
  gcc/rust/typecheck/rust-hir-inherent-impl-overlap.h
  gcc/rust/typecheck/rust-hir-path-probe.cc
  gcc/rust/typecheck/rust-hir-trait-ref.h
  gcc/rust/typecheck/rust-hir-trait-resolve.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check-item.h
  gcc/rust/typecheck/rust-hir-type-check-path.cc
  gcc/rust/typecheck/rust-hir-type-check-pattern.cc
  gcc/rust/typecheck/rust-hir-type-check-stmt.h
  gcc/rust/typecheck/rust-hir-type-check-type.cc
  gcc/rust/typecheck/rust-hir-type-check-type.h
  gcc/rust/typecheck/rust-hir-type-check.cc
  gcc/rust/typecheck/rust-tyty-bounds.cc
  gcc/rust/typecheck/rust-tyty-call.h
  gcc/rust/typecheck/rust-tyty-cmp.h
  gcc/rust/typecheck/rust-tyty-rules.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/util/rust-attributes.cc
Labels: CI, cleanup

#1633 Implement PhantomData
  gcc/rust/util/rust-lang-item.h
  gcc/testsuite/rust/compile/torture/phantom_data.rs
Labels: enhancement

#1652 AST dump types
  gcc/rust/ast/rust-ast-dump.cc
  gcc/rust/ast/rust-ast-dump.h
  gcc/rust/ast/rust-ast-full-test.cc
  gcc/rust/ast/rust-type.h
Labels: enhancement

#1636 Add location to AST::Visibility
  gcc/rust/ast/rust-item.h
  gcc/rust/hir/rust-ast-lower.cc
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/parse/rust-parse-impl.h
Labels: enhancement

#1657 ci: Remove warning checks on gcc-patch-dev
  .github/workflows/bootstrap.yml
  .github/workflows/ccpp.yml
Labels: upstream

#1653 Release `mpz_t` values properly
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/rust-gcc.cc
Labels: upstream

#1656 No fold after convert to
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/rust-gcc.cc
  gcc/rust/rust-lang.cc
Labels: upstream

#1659 8e52e414f40b: Use build_int_cstu for size expressions
  gcc/rust/backend/rust-compile-expr.cc
Labels: upstream

#1661 58e75f65e56d: Remove HOST_WIDE_INT struct member
  gcc/rust/backend/rust-constexpr.cc
Labels: upstream

#1662 48fa248760da: Simplify get_nth_callarg
  gcc/rust/backend/rust-constexpr.cc
Labels: upstream

#1663 dwarf2out.c: Don't emit DW_LANG_Rust_old
  gcc/dwarf2out.cc
  gcc/testsuite/rust/debug/oldlang.rs
Labels: upstream

#1664 8e52e414f40b: Fix merge issue
  gcc/rust/backend/rust-compile-expr.cc
Labels: upstream

#1651 Improve dump lex
  gcc/rust/lex/rust-lex.cc
  gcc/rust/lex/rust-lex.h
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/parse/rust-parse.h
  gcc/rust/rust-session-manager.cc
  gcc/rust/util/rust-optional.h
Labels: enhancement

#1660 Use `wide_int_to_tree` instead of `double_int_to_tree`
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/rust-gcc.cc
Labels: upstream

#1630 Cleanup builtin handling
  gcc/rust/backend/rust-builtins.cc
  gcc/rust/backend/rust-builtins.h
  gcc/rust/backend/rust-compile-intrinsic.cc
  gcc/rust/rust-gcc.cc
  gcc/testsuite/rust/compile/torture/intrinsics-4.rs
  gcc/testsuite/rust/execute/torture/atomic_load.rs
  gcc/testsuite/rust/execute/torture/atomic_store.rs
Labels: enhancement, cleanup
