Repository Rust-GCC/gccrs, pull requests merged in 2022-06, with the labels that each got.

#1287 Add AST dump visitor
  gcc/rust/Make-lang.in
  gcc/rust/ast/rust-ast-dump.cc
  gcc/rust/ast/rust-ast-dump.h
Labels: enhancement

#1288 docker: Add commit information to Docker image
  Dockerfile
Labels: enhancement, CI

#1295 AST Dump impl traits
  gcc/rust/ast/rust-ast-dump.cc
  gcc/rust/ast/rust-ast-dump.h
  gcc/rust/ast/rust-item.h
Labels: enhancement

#1298 rust/intrinsic: add a basic size check for `transmute`
  gcc/rust/backend/rust-compile-intrinsic.cc
  gcc/rust/hir/tree/rust-hir-type.h
  gcc/testsuite/rust/compile/torture/transmute-size-check-1.rs
Labels: enhancement

#1286 gccrs const folding: port over cp_walk_subtrees()
  gcc/rust/backend/rust-tree.cc
  gcc/rust/backend/rust-tree.h
Labels: plan, GCC

#1307 Handle super and crate in path resolution
  gcc/rust/ast/rust-ast.h
  gcc/rust/ast/rust-path.h
  gcc/rust/backend/rust-compile-base.cc
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/backend/rust-compile-resolve-path.cc
  gcc/rust/backend/rust-compile-stmt.h
  gcc/rust/backend/rust-compile-var-decl.h
  gcc/rust/hir/rust-ast-lower.cc
  gcc/rust/lint/rust-lint-marklive.cc
  gcc/rust/privacy/rust-visibility-resolver.cc
  gcc/rust/resolve/rust-ast-resolve-base.h
  gcc/rust/resolve/rust-ast-resolve-expr.cc
  gcc/rust/resolve/rust-ast-resolve-implitem.h
  gcc/rust/resolve/rust-ast-resolve-item.cc
  gcc/rust/resolve/rust-ast-resolve-path.cc
  gcc/rust/resolve/rust-ast-resolve-path.h
  gcc/rust/resolve/rust-ast-resolve-pattern.cc
  gcc/rust/resolve/rust-ast-resolve-pattern.h
  gcc/rust/resolve/rust-ast-resolve-stmt.h
  gcc/rust/resolve/rust-ast-resolve-toplevel.h
  gcc/rust/resolve/rust-ast-resolve-type.cc
  gcc/rust/resolve/rust-ast-resolve-type.h
  gcc/rust/resolve/rust-ast-resolve.cc
  gcc/rust/resolve/rust-name-resolver.cc
  gcc/rust/resolve/rust-name-resolver.h
  gcc/rust/rust-session-manager.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check-path.cc
  gcc/rust/typecheck/rust-hir-type-check-pattern.cc
  gcc/rust/typecheck/rust-hir-type-check-pattern.h
  gcc/rust/typecheck/rust-hir-type-check-stmt.h
  gcc/rust/typecheck/rust-hir-type-check-type.cc
  gcc/rust/typecheck/rust-tycheck-dump.h
  gcc/rust/util/rust-hir-map.cc
  gcc/rust/util/rust-hir-map.h
  gcc/testsuite/rust/compile/complex-path1.rs
  gcc/testsuite/rust/compile/issue-1251.rs
Labels: bug, enhancement

#1296 Ast dump trait impl
  gcc/rust/ast/rust-ast-dump.cc
Labels: enhancement

#1313 Parse const generics properly
  gcc/rust/parse/rust-parse-impl.h
  gcc/testsuite/rust/compile/const_generics_1.rs
  gcc/testsuite/rust/compile/const_generics_2.rs
Labels: enhancement, parser

#1308 Fix formatting error on 32-bits targets
  gcc/rust/expand/rust-macro-expand.cc
  gcc/rust/expand/rust-macro-substitute-ctx.cc
  gcc/rust/lex/rust-lex.cc
  gcc/rust/lint/rust-lint-marklive.cc
  gcc/rust/rust-session-manager.cc
  gcc/rust/typecheck/rust-hir-type-check-pattern.cc
  gcc/rust/typecheck/rust-tyty.cc
Labels: enhancement

#1315 Add base for parsing const generic application
  gcc/rust/ast/rust-path.h
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/parse/rust-parse.h
  gcc/testsuite/rust/compile/const_generics_3.rs
Labels: enhancement, parser

#1316 Add const generic declaration to AST
  gcc/rust/ast/rust-ast-dump.cc
  gcc/rust/ast/rust-ast-dump.h
  gcc/rust/ast/rust-ast-full-decls.h
  gcc/rust/ast/rust-ast-full-test.cc
  gcc/rust/ast/rust-ast-visitor.h
  gcc/rust/ast/rust-ast.h
  gcc/rust/expand/rust-attribute-visitor.cc
  gcc/rust/expand/rust-attribute-visitor.h
  gcc/rust/hir/rust-ast-lower-base.cc
  gcc/rust/hir/rust-ast-lower-base.h
  gcc/rust/hir/rust-ast-lower-type.h
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/resolve/rust-ast-resolve-base.cc
  gcc/rust/resolve/rust-ast-resolve-base.h
  gcc/rust/resolve/rust-ast-resolve-type.h
Labels: enhancement

#1317 AST for const generic arguments/const application
  gcc/rust/ast/rust-ast-full-test.cc
  gcc/rust/ast/rust-path.h
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/parse/rust-parse.h
Labels: enhancement

#1326 ast: Add location to ConstGenericArg
  gcc/rust/ast/rust-path.h
  gcc/rust/parse/rust-parse-impl.h
Labels: enhancement

#1331 Fix remaining misuses of format specifiers on 32-bit targets
  gcc/rust/backend/rust-compile-intrinsic.cc
Labels: bug, enhancement

#1341 ci: Temporarily disable Remark CI
  .github/workflows/Remark.yml
Labels: bug, automation

#1342 Refactor name-resolution pass
  gcc/rust/Make-lang.in
  gcc/rust/resolve/rust-ast-resolve-base.cc
  gcc/rust/resolve/rust-ast-resolve-base.h
  gcc/rust/resolve/rust-ast-resolve-expr.cc
  gcc/rust/resolve/rust-ast-resolve-expr.h
  gcc/rust/resolve/rust-ast-resolve-implitem.h
  gcc/rust/resolve/rust-ast-resolve-item.cc
  gcc/rust/resolve/rust-ast-resolve-item.h
  gcc/rust/resolve/rust-ast-resolve-path.cc
  gcc/rust/resolve/rust-ast-resolve-path.h
  gcc/rust/resolve/rust-ast-resolve-pattern.cc
  gcc/rust/resolve/rust-ast-resolve-pattern.h
  gcc/rust/resolve/rust-ast-resolve-stmt.h
  gcc/rust/resolve/rust-ast-resolve-struct-expr-field.cc
  gcc/rust/resolve/rust-ast-resolve-struct-expr-field.h
  gcc/rust/resolve/rust-ast-resolve-toplevel.h
  gcc/rust/resolve/rust-ast-resolve-type.cc
  gcc/rust/resolve/rust-ast-resolve-type.h
  gcc/rust/resolve/rust-ast-resolve.cc
  gcc/rust/resolve/rust-ast-verify-assignee.h
  gcc/rust/resolve/rust-name-resolver.cc
  gcc/rust/resolve/rust-name-resolver.h
  gcc/rust/util/rust-canonical-path.h
Labels: enhancement, cleanup

#1338 gccrs const folding port: continue porting potential_constant_expression_1()
  gcc/rust/backend/rust-constexpr.cc
  gcc/rust/backend/rust-tree.cc
  gcc/rust/backend/rust-tree.h
Labels: enhancement

#1336 Resolve const generic parameters
  gcc/rust/ast/rust-ast-full-test.cc
  gcc/rust/ast/rust-ast.h
  gcc/rust/ast/rust-path.h
  gcc/rust/hir/rust-ast-lower-type.h
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/resolve/rust-ast-resolve-item.cc
  gcc/rust/resolve/rust-ast-resolve-item.h
  gcc/rust/resolve/rust-ast-resolve-stmt.cc
  gcc/rust/resolve/rust-ast-resolve-stmt.h
  gcc/rust/resolve/rust-ast-resolve-type.h
  gcc/testsuite/rust/compile/const_generics_4.rs
Labels: enhancement
