Repository Rust-GCC/gccrs, pull requests merged in 2023-11, with the labels that each got.

#2746 fixup: Ensure buffer allocation for bootstrap
  gcc/rust/expand/rust-proc-macro.cc
Labels: important

#2750 Add AST union validation
  gcc/rust/checks/errors/rust-ast-validation.cc
  gcc/rust/checks/errors/rust-ast-validation.h
  gcc/testsuite/rust/compile/const_generics_8.rs
  gcc/testsuite/rust/compile/empty_union.rs
Labels: enhancement

#2764 Remove class ```AST::InherentImplItem```
  gcc/rust/ast/rust-ast-full-decls.h
  gcc/rust/ast/rust-ast.cc
  gcc/rust/ast/rust-ast.h
  gcc/rust/ast/rust-item.h
  gcc/rust/ast/rust-macro.h
  gcc/rust/expand/rust-expand-visitor.cc
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/parse/rust-parse.h
Labels: cleanup
