Repository Rust-GCC/gccrs, pull requests merged in 2023-02, with the labels that each got.

#1816 Move rust-buffered-queue.h to util folder #1766
  gcc/rust/util/rust-buffered-queue.h
Labels: cleanup

#1812 parser: Allow parsing multiple reference types
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/parse/rust-parse.h
  gcc/testsuite/rust/compile/multi_reference_type.rs
Labels: enhancement

#1698 update the ubuntu version
  .github/bors_log_expected_warnings
  .github/workflows/bootstrap.yml
  .github/workflows/ccpp.yml
Labels: enhancement, CI

#1737 Add support for feature check.
  gcc/rust/Make-lang.in
  gcc/rust/checks/errors/rust-feature-gate.cc
  gcc/rust/checks/errors/rust-feature-gate.h
  gcc/rust/checks/errors/rust-feature.cc
  gcc/rust/checks/errors/rust-feature.h
  gcc/rust/rust-session-manager.cc
  gcc/testsuite/rust/compile/feature.rs
Labels: enhancement

#1818 Implement lowering ReferencePattern from AST to HIR
  gcc/rust/ast/rust-pattern.h
  gcc/rust/hir/rust-ast-lower-pattern.cc
  gcc/rust/hir/rust-ast-lower-pattern.h
  gcc/rust/hir/tree/rust-hir-full-test.cc
  gcc/rust/hir/tree/rust-hir-pattern.h
Labels: enhancement

#1826 Removed comment copy-pasted from gcc/tree.def
  gcc/rust/backend/rust-compile-expr.cc
Labels: cleanup

#1739 Initial type bounds checking for all type checks
  gcc/rust/Make-lang.in
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/typecheck/rust-coercion.cc
  gcc/rust/typecheck/rust-hir-path-probe.cc
  gcc/rust/typecheck/rust-hir-path-probe.h
  gcc/rust/typecheck/rust-hir-trait-reference.h
  gcc/rust/typecheck/rust-hir-trait-resolve.cc
  gcc/rust/typecheck/rust-hir-trait-resolve.h
  gcc/rust/typecheck/rust-hir-type-check-base.cc
  gcc/rust/typecheck/rust-hir-type-check-path.cc
  gcc/rust/typecheck/rust-hir-type-check.h
  gcc/rust/typecheck/rust-substitution-mapper.cc
  gcc/rust/typecheck/rust-substitution-mapper.h
  gcc/rust/typecheck/rust-tyctx.cc
  gcc/rust/typecheck/rust-typecheck-context.cc
  gcc/rust/typecheck/rust-tyty-bounds.cc
  gcc/rust/typecheck/rust-tyty-bounds.h
  gcc/rust/typecheck/rust-tyty-call.cc
  gcc/rust/typecheck/rust-tyty-rules.h
  gcc/rust/typecheck/rust-tyty-subst.cc
  gcc/rust/typecheck/rust-tyty-subst.h
  gcc/rust/typecheck/rust-tyty-util.cc
  gcc/rust/typecheck/rust-tyty-util.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/rust/typecheck/rust-unify.cc
  gcc/rust/typecheck/rust-unify.h
  gcc/rust/util/rust-lang-item.h
  gcc/testsuite/rust/bounds1.rs
  gcc/testsuite/rust/compile/func3.rs
  gcc/testsuite/rust/compile/issue-1773.rs
  gcc/testsuite/rust/compile/issue-1786.rs
  gcc/testsuite/rust/compile/never_type1.rs
  gcc/testsuite/rust/compile/torture/intrinsics-4.rs
  gcc/testsuite/rust/compile/torture/intrinsics-5.rs
  gcc/testsuite/rust/execute/torture/atomic_load.rs
  gcc/testsuite/rust/execute/torture/atomic_store.rs
  gcc/testsuite/rust/execute/torture/issue-1720-2.rs
Labels: enhancement, cleanup

#1817 ci: Require commits check to pass for bors to merge and fix CI names
  .github/bors.toml
  .github/workflows/commit-format.yml
Labels: CI

#1832 ci: Run commit format checker on push to `trying` branch
  .github/bors.toml
Labels: bug, CI

#1789 Run workflow
  gcc/rust/Make-lang.in
  gcc/rust/rust-diagnostics.cc
  gcc/rust/rust-gcc-diagnostics.cc
Labels: CI, cleanup

#1820 Support for TuplePattern in let statements
  gcc/rust/backend/rust-compile-pattern.cc
  gcc/rust/backend/rust-compile-pattern.h
  gcc/rust/hir/tree/rust-hir-pattern.h
  gcc/testsuite/rust/execute/torture/let-pattern-1.rs
Labels: enhancement

#1750 Implement fixed point macro expansion
  gcc/rust/Make-lang.in
  gcc/rust/ast/rust-ast-fragment.cc
  gcc/rust/ast/rust-ast-fragment.h
  gcc/rust/ast/rust-ast.cc
  gcc/rust/ast/rust-ast.h
  gcc/rust/ast/rust-item.h
  gcc/rust/ast/rust-macro.cc
  gcc/rust/ast/rust-macro.h
  gcc/rust/expand/rust-attribute-visitor.cc
  gcc/rust/expand/rust-attribute-visitor.h
  gcc/rust/expand/rust-macro-builtins.cc
  gcc/rust/expand/rust-macro-expand.cc
  gcc/rust/expand/rust-macro-expand.h
  gcc/rust/expand/rust-macro-invoc-lexer.cc
  gcc/rust/expand/rust-macro-invoc-lexer.h
  gcc/rust/parse/rust-parse.h
  gcc/rust/resolve/rust-early-name-resolver.cc
  gcc/rust/resolve/rust-early-name-resolver.h
  gcc/rust/rust-session-manager.cc
  gcc/testsuite/rust/compile/builtin_macro_eager1.rs
  gcc/testsuite/rust/compile/builtin_macro_eager2.rs
  gcc/testsuite/rust/compile/builtin_macro_recurse2.rs
  gcc/testsuite/rust/compile/macro17.rs
  gcc/testsuite/rust/compile/macro44.rs
  gcc/testsuite/rust/compile/macro46.rs
Labels: enhancement

#1825 Add feature gate for "rust-intrinsic".
  gcc/rust/checks/errors/rust-feature-gate.cc
  gcc/rust/checks/errors/rust-feature-gate.h
  gcc/rust/checks/errors/rust-feature.h
  gcc/testsuite/rust/compile/const-issue1440.rs
  gcc/testsuite/rust/compile/feature_intrinsics.rs
  gcc/testsuite/rust/compile/issue-1031.rs
  gcc/testsuite/rust/compile/issue-1130.rs
  gcc/testsuite/rust/compile/issue-1131.rs
  gcc/testsuite/rust/compile/issue-1237.rs
  gcc/testsuite/rust/compile/issue-1289.rs
  gcc/testsuite/rust/compile/rust-const-blog-issue.rs
  gcc/testsuite/rust/compile/torture/intrinsics-3.rs
  gcc/testsuite/rust/compile/torture/intrinsics-4.rs
  gcc/testsuite/rust/compile/torture/intrinsics-5.rs
  gcc/testsuite/rust/compile/torture/intrinsics-6.rs
  gcc/testsuite/rust/compile/torture/intrinsics-7.rs
  gcc/testsuite/rust/compile/torture/issue-1024.rs
  gcc/testsuite/rust/compile/torture/issue-1075.rs
  gcc/testsuite/rust/compile/torture/issue-1432.rs
  gcc/testsuite/rust/compile/unsafe10.rs
  gcc/testsuite/rust/execute/torture/atomic_load.rs
  gcc/testsuite/rust/execute/torture/atomic_store.rs
  gcc/testsuite/rust/execute/torture/copy_nonoverlapping1.rs
  gcc/testsuite/rust/execute/torture/issue-1120.rs
  gcc/testsuite/rust/execute/torture/issue-1133.rs
  gcc/testsuite/rust/execute/torture/issue-1232.rs
  gcc/testsuite/rust/execute/torture/slice-magic.rs
  gcc/testsuite/rust/execute/torture/slice-magic2.rs
  gcc/testsuite/rust/execute/torture/str-layout1.rs
  gcc/testsuite/rust/execute/torture/transmute1.rs
  gcc/testsuite/rust/execute/torture/wrapping_op1.rs
  gcc/testsuite/rust/execute/torture/wrapping_op2.rs
Labels: enhancement

#1858 ci: Add missing `merge_group` trigger for workflow
  .github/workflows/bootstrap.yml
  .github/workflows/ccpp.yml
  .github/workflows/clang-format.yml
  .github/workflows/commit-format.yml
Labels: CI

#1821 Improve WildcardPattern let statement handling
  gcc/rust/backend/rust-compile-pattern.cc
  gcc/rust/backend/rust-compile-var-decl.h
  gcc/rust/resolve/rust-ast-resolve-pattern.h
Labels: enhancement

#1855 Add support for parsing empty tuple patterns.
  gcc/rust/parse/rust-parse-impl.h
  gcc/testsuite/rust/compile/parse_empty_tuple_pattern.rs
Labels: bug, enhancement

#1727 Implemented utf-8 checking
  gcc/rust/expand/rust-macro-builtins.cc
  gcc/testsuite/rust/compile/builtin_macro_include_str.rs
  gcc/testsuite/rust/compile/invalid_utf8
Labels: bug

#1863 Add trailing newline
  gcc/rust/checks/errors/rust-feature-gate.h
Labels: cleanup

#1866 include!(): Return empty list of tokens instead of nullptr
  gcc/rust/expand/rust-macro-builtins.cc
  gcc/testsuite/rust/compile/empty.in
  gcc/testsuite/rust/compile/include_empty.rs
Labels: bug, enhancement

#1862 Add AST::AltPattern class
  gcc/rust/ast/rust-ast-dump.cc
  gcc/rust/ast/rust-ast-dump.h
  gcc/rust/ast/rust-ast-full-decls.h
  gcc/rust/ast/rust-ast-visitor.h
  gcc/rust/ast/rust-ast.cc
  gcc/rust/ast/rust-pattern.h
  gcc/rust/checks/errors/rust-feature-gate.h
  gcc/rust/expand/rust-attribute-visitor.cc
  gcc/rust/expand/rust-attribute-visitor.h
  gcc/rust/hir/rust-ast-lower-base.cc
  gcc/rust/hir/rust-ast-lower-base.h
  gcc/rust/resolve/rust-ast-resolve-base.cc
  gcc/rust/resolve/rust-ast-resolve-base.h
  gcc/rust/resolve/rust-early-name-resolver.cc
  gcc/rust/resolve/rust-early-name-resolver.h
  gcc/rust/util/rust-attributes.cc
  gcc/rust/util/rust-attributes.h
Labels: enhancement

#1869 Fix up DejaGnu directives in 'rust/compile/issue-1830_{bytes,str}.rs' test cases [#1838]
  gcc/testsuite/rust/compile/issue-1830_bytes.rs
  gcc/testsuite/rust/compile/issue-1830_str.rs
Labels: enhancement

#1877 gccrs: add test case to show our query-type system is working
  gcc/testsuite/rust/compile/issue-1361.rs
Labels: bug

#1868 ast: Refactor TraitItem to keep Location info
  gcc/rust/ast/rust-ast.h
  gcc/rust/ast/rust-item.h
  gcc/rust/ast/rust-macro.h
Labels: enhancement

#1867 diagnostic: Refactor Error class
  gcc/rust/ast/rust-ast.cc
  gcc/rust/checks/errors/privacy/rust-visibility-resolver.cc
  gcc/rust/expand/rust-macro-builtins.cc
  gcc/rust/expand/rust-macro-expand.cc
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/rust-diagnostics.cc
  gcc/rust/rust-diagnostics.h
  gcc/rust/rust-session-manager.cc
Labels: enhancement

#1884 Added AST Node AST::InlineAsm
  gcc/rust/ast/rust-ast-full-decls.h
  gcc/rust/ast/rust-expr.h
Labels: enhancement

#1879 Unsafe block parsing fix
  gcc/rust/parse/rust-parse-impl.h
  gcc/testsuite/rust/compile/issue-1422.rs
Labels: enhancement

#1878 Parse AltPattern
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/parse/rust-parse.h
  gcc/testsuite/rust/compile/pattern-or.rs
Labels: enhancement

#1873 Add feature gate for "rustc_attri".
  gcc/rust/checks/errors/rust-feature-gate.cc
  gcc/rust/checks/errors/rust-feature-gate.h
  gcc/testsuite/rust/compile/builtin_macro_compile_error.rs
  gcc/testsuite/rust/compile/builtin_macro_concat.rs
  gcc/testsuite/rust/compile/builtin_macro_eager1.rs
  gcc/testsuite/rust/compile/builtin_macro_eager2.rs
  gcc/testsuite/rust/compile/builtin_macro_env.rs
  gcc/testsuite/rust/compile/builtin_macro_include_bytes.rs
  gcc/testsuite/rust/compile/builtin_macro_include_str.rs
  gcc/testsuite/rust/compile/builtin_macro_not_found.rs
  gcc/testsuite/rust/compile/builtin_macro_recurse2.rs
  gcc/testsuite/rust/compile/feature_rust_attri0.rs
  gcc/testsuite/rust/compile/feature_rust_attri1.rs
  gcc/testsuite/rust/compile/include_empty.rs
  gcc/testsuite/rust/compile/issue-1830_bytes.rs
  gcc/testsuite/rust/compile/issue-1830_str.rs
  gcc/testsuite/rust/compile/macro42.rs
  gcc/testsuite/rust/execute/torture/builtin_macro_cfg.rs
  gcc/testsuite/rust/execute/torture/builtin_macro_concat.rs
  gcc/testsuite/rust/execute/torture/builtin_macro_env.rs
  gcc/testsuite/rust/execute/torture/builtin_macro_include_bytes.rs
  gcc/testsuite/rust/execute/torture/builtin_macro_include_str.rs
  gcc/testsuite/rust/execute/torture/builtin_macro_line.rs
  gcc/testsuite/rust/execute/torture/builtin_macros1.rs
  gcc/testsuite/rust/execute/torture/builtin_macros3.rs
  gcc/testsuite/rust/execute/torture/macros29.rs
  gcc/testsuite/rust/execute/torture/macros30.rs
  gcc/testsuite/rust/execute/torture/macros31.rs
Labels: enhancement

#1906 ci: Run GCC 4.8 job in Ubuntu 18.04 container
  .github/workflows/ccpp.yml
Labels: CI

#1907 typecheck: Refactor unify_site
  gcc/rust/typecheck/rust-autoderef.cc
  gcc/rust/typecheck/rust-hir-trait-resolve.cc
  gcc/rust/typecheck/rust-hir-type-check-base.cc
  gcc/rust/typecheck/rust-hir-type-check-base.h
  gcc/rust/typecheck/rust-hir-type-check.cc
  gcc/rust/typecheck/rust-type-util.cc
  gcc/rust/typecheck/rust-type-util.h
  gcc/rust/typecheck/rust-tyty-call.cc
Labels: enhancement

#1875 parser: Parse auto_traits
  gcc/rust/ast/rust-item.h
  gcc/rust/checks/errors/rust-feature.cc
  gcc/rust/checks/errors/rust-feature.h
  gcc/rust/lex/rust-lex.cc
  gcc/rust/lex/rust-token.h
  gcc/rust/parse/rust-parse-impl.h
  gcc/testsuite/rust/compile/auto_trait_invalid.rs
  gcc/testsuite/rust/compile/auto_trait_valid.rs
Labels: bug, enhancement

#1905 macro_invoc_lexer: Add `split_current_token` implementation
  gcc/rust/expand/rust-macro-invoc-lexer.cc
  gcc/testsuite/rust/compile/expand_macro_qual_path_in_type.rs
Labels: bug, enhancement

#1921 parser: Parse `default` impl Functions and Methods
  gcc/rust/ast/rust-item.h
  gcc/rust/parse/rust-parse-impl.h
  gcc/testsuite/rust/compile/default_not_a_kw.rs
  gcc/testsuite/rust/compile/parse_invalid_specialization.rs
  gcc/testsuite/rust/compile/parse_specialization.rs
Labels: enhancement

#1871 builtins: Implement eager expansion for include_str!()
  gcc/rust/expand/rust-macro-builtins.cc
  gcc/testsuite/rust/compile/builtin_macro_eager3.rs
Labels: enhancement

#1937 Add `RestPattern` AST node
  gcc/rust/ast/rust-ast-dump.cc
  gcc/rust/ast/rust-ast-dump.h
  gcc/rust/ast/rust-ast-full-decls.h
  gcc/rust/ast/rust-ast-visitor.h
  gcc/rust/ast/rust-ast.cc
  gcc/rust/ast/rust-pattern.h
  gcc/rust/checks/errors/rust-feature-gate.h
  gcc/rust/expand/rust-attribute-visitor.cc
  gcc/rust/expand/rust-attribute-visitor.h
  gcc/rust/hir/rust-ast-lower-base.cc
  gcc/rust/hir/rust-ast-lower-base.h
  gcc/rust/resolve/rust-ast-resolve-base.cc
  gcc/rust/resolve/rust-ast-resolve-base.h
  gcc/rust/resolve/rust-early-name-resolver.cc
  gcc/rust/resolve/rust-early-name-resolver.h
  gcc/rust/util/rust-attributes.cc
  gcc/rust/util/rust-attributes.h
Labels: enhancement
