Repository Rust-GCC/gccrs, pull requests merged in 2023-07, with the labels that each got.

#2359 gccrs: Track fn_once output lang item properly
  gcc/rust/typecheck/rust-tyty-bounds.cc
  gcc/rust/util/rust-hir-map.cc
  gcc/rust/util/rust-hir-map.h
  gcc/testsuite/rust/compile/issue-2105.rs
Labels: bug

#2347 Remove unnecessary methods/fields of `Rust::Lexer`
  gcc/rust/lex/rust-lex.cc
  gcc/rust/lex/rust-lex.h
Labels: cleanup

#2360 gccrs: minor HIR interface cleanup
  gcc/rust/hir/tree/rust-hir-expr.h
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/hir/tree/rust-hir-pattern.h
Labels: cleanup

#2367 [E0229] associated type bindings error
  gcc/rust/typecheck/rust-tyty-subst.cc
Labels: diagnostic

#2365 [E0034] Ambiguous Method Call Error
  gcc/rust/typecheck/rust-hir-path-probe.h
Labels: diagnostic

#2372 gccrs: HIR cleanup
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-stmt.cc
  gcc/rust/checks/errors/privacy/rust-privacy-reporter.cc
  gcc/rust/checks/errors/rust-const-checker.cc
  gcc/rust/checks/errors/rust-unsafe-checker.cc
  gcc/rust/hir/rust-hir-dump.cc
  gcc/rust/hir/tree/rust-hir-expr.h
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/hir/tree/rust-hir-pattern.h
  gcc/rust/hir/tree/rust-hir-stmt.h
  gcc/rust/hir/tree/rust-hir-type.h
  gcc/rust/hir/tree/rust-hir.h
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/rust/typecheck/rust-hir-type-check-stmt.cc
Labels: cleanup

#2362 Change class Location into typedef
  gcc/rust/backend/rust-compile-base.cc
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-intrinsic.cc
  gcc/rust/resolve/rust-ast-resolve-expr.cc
  gcc/rust/rust-diagnostics.cc
  gcc/rust/rust-diagnostics.h
  gcc/rust/rust-gcc.cc
  gcc/rust/rust-linemap.cc
  gcc/rust/rust-location.h
  gcc/rust/typecheck/rust-hir-trait-resolve.cc
  gcc/rust/typecheck/rust-hir-type-check-stmt.cc
  gcc/rust/util/rust-token-converter.cc
Labels: cleanup

#2364 Add location info to `Rust::Identifier`
  gcc/rust/ast/rust-ast.h
  gcc/rust/ast/rust-pattern.h
  gcc/rust/checks/lints/rust-lint-scan-deadcode.h
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/resolve/rust-ast-resolve-item.cc
  gcc/rust/typecheck/rust-hir-type-check-implitem.cc
Labels: cleanup

#2377 [E0046] Missing Items in Trait Implementation
  gcc/rust/typecheck/rust-hir-type-check-item.cc
Labels: diagnostic

#2292 Ignore semicolon following a macro expansion in expression context
  gcc/rust/expand/rust-macro-expand.cc
  gcc/testsuite/rust/compile/macro-issue2273.rs
Labels: bug, enhancement

#2374 Add utf-8 validation for input source
  gcc/rust/lex/rust-lex.cc
  gcc/rust/lex/rust-lex.h
  gcc/rust/rust-session-manager.cc
  gcc/testsuite/rust/compile/broken_utf8.rs
Labels: enhancement

#2380 [E0053] method 'x' has an incompatible type for trait 'y'
  gcc/rust/typecheck/rust-hir-type-check-implitem.cc
Labels: diagnostic

#2370 Reduce Linemap/Gcc_linemap abstraction
  gcc/rust/rust-linemap.cc
  gcc/rust/rust-linemap.h
Labels: GCC, cleanup

#2383 [E0425] Use of unresolved name
  gcc/rust/resolve/rust-ast-resolve-expr.cc
  gcc/testsuite/rust/compile/break-rust2.rs
  gcc/testsuite/rust/compile/const_generics_3.rs
  gcc/testsuite/rust/compile/const_generics_4.rs
  gcc/testsuite/rust/compile/not_find_value_in_scope.rs
Labels: diagnostic

#2371 Reduce Linemap/Gcc_linemap abstraction further
  gcc/rust/expand/rust-macro-builtins.cc
  gcc/rust/rust-linemap.cc
  gcc/rust/rust-linemap.h
Labels: diagnostic, cleanup

#2351 Create MacroInvocLexerBase
  gcc/rust/expand/rust-macro-invoc-lexer.h
Labels: enhancement

#2317 util: Add tl::expected type
  gcc/rust/util/expected.h
Labels: enhancement

#2342 nr2.0: Add complex testcases
  gcc/testsuite/rust/compile/name_resolution1.rs
  gcc/testsuite/rust/compile/name_resolution2.rs
  gcc/testsuite/rust/compile/name_resolution3.rs
  gcc/testsuite/rust/compile/name_resolution4.rs
  gcc/testsuite/rust/compile/name_resolution5.rs
Labels: enhancement

#2373 [E0061] Refactored argument mismatch error function
  gcc/rust/typecheck/rust-tyty-call.cc
  gcc/testsuite/rust/compile/func2.rs
  gcc/testsuite/rust/compile/tuple_struct2.rs
  gcc/testsuite/rust/compile/wrong_no_of_parameters.rs
Labels: diagnostic

#2390 [E0070] invalid left-hand side of assignment
  gcc/rust/resolve/rust-ast-verify-assignee.h
  gcc/testsuite/rust/compile/wrong_lhs_assignment.rs
Labels: diagnostic

#2392 Replace ```Linemap::unknown_location``` with ```UNKNOWN_LOCATION```
  gcc/rust/ast/rust-ast.cc
  gcc/rust/ast/rust-path.cc
  gcc/rust/hir/tree/rust-hir.cc
  gcc/rust/metadata/rust-imports.cc
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/parse/rust-parse.h
  gcc/rust/rust-backend.h
  gcc/rust/rust-diagnostics.cc
  gcc/rust/rust-linemap.h
  gcc/rust/rust-session-manager.cc
  gcc/rust/typecheck/rust-tyty.cc
Labels: cleanup

#2328 Remove old uses of Optional<T>
  gcc/rust/Make-lang.in
  gcc/rust/ast/rust-macro.h
  gcc/rust/backend/rust-compile-base.cc
  gcc/rust/checks/errors/privacy/rust-privacy-reporter.cc
  gcc/rust/checks/errors/privacy/rust-privacy-reporter.h
  gcc/rust/checks/errors/rust-feature-gate.cc
  gcc/rust/checks/errors/rust-feature.cc
  gcc/rust/checks/errors/rust-feature.h
  gcc/rust/expand/rust-macro-builtins.cc
  gcc/rust/lex/rust-lex.cc
  gcc/rust/lex/rust-lex.h
  gcc/rust/resolve/rust-ast-resolve-path.cc
  gcc/rust/resolve/rust-ast-resolve-type.cc
  gcc/rust/rust-lang.cc
  gcc/rust/rust-session-manager.cc
  gcc/rust/rust-session-manager.h
  gcc/rust/util/rust-hir-map.cc
  gcc/rust/util/rust-hir-map.h
  gcc/rust/util/rust-optional-test.cc
  gcc/rust/util/rust-optional.h
Labels: cleanup

#2393 Merge ```Linemap``` and ```Gcc_linemap```
  gcc/rust/rust-linemap.cc
  gcc/rust/rust-linemap.h
Labels: cleanup

#2395 Add ```rust_error_at``` accepting ```location_t``` and ```ErrorCode```
  gcc/rust/rust-diagnostics.cc
  gcc/rust/rust-diagnostics.h
Labels: enhancement

#2405 gccrs: minor HIR cleanup
  gcc/rust/hir/tree/rust-hir-expr.h
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/hir/tree/rust-hir-path.h
  gcc/rust/hir/tree/rust-hir-pattern.h
  gcc/rust/hir/tree/rust-hir.h
Labels: cleanup

#2400 Merge ```Linemap::to_string``` into ```Linemap::location_to_string```
  gcc/rust/lex/rust-lex.cc
  gcc/rust/rust-linemap.cc
  gcc/rust/rust-linemap.h
Labels: cleanup

#2406 Remove unnecessary usage of ```Location``` copy constructor
  gcc/rust/ast/rust-expr.h
  gcc/rust/backend/rust-constexpr.cc
  gcc/rust/util/rust-token-converter.cc
Labels: cleanup

#2415 gccrs: minor HIR cleanup
  gcc/rust/hir/tree/rust-hir-type.h
Labels: cleanup

#2399 dump: Output escaped character values
  gcc/rust/lex/rust-token.cc
Labels: enhancement

#2414 mklog: handle Signed-Off-By, minor cleanup
  contrib/mklog.py
  contrib/prepare-commit-msg
Labels: enhancement, community, CI

#2401 Remove ```Linemap::get_location```
  gcc/rust/lex/rust-lex.cc
  gcc/rust/rust-linemap.cc
  gcc/rust/rust-linemap.h
  gcc/rust/rust-session-manager.cc
Labels: cleanup

#2402 Remove ```Linemap::start_line```
  gcc/rust/lex/rust-lex.cc
  gcc/rust/rust-linemap.cc
  gcc/rust/rust-linemap.h
Labels: cleanup

#2416 rust-unreachable: Add specific behavior for rust_unreachable
  gcc/rust/ast/rust-ast-collector.cc
  gcc/rust/ast/rust-ast-dump.h
  gcc/rust/ast/rust-ast-formatting.cc
  gcc/rust/ast/rust-ast.cc
  gcc/rust/ast/rust-ast.h
  gcc/rust/ast/rust-macro.h
  gcc/rust/ast/rust-path.h
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-intrinsic.cc
  gcc/rust/backend/rust-compile-pattern.cc
  gcc/rust/backend/rust-constexpr.cc
  gcc/rust/backend/rust-mangle.cc
  gcc/rust/backend/rust-tree.cc
  gcc/rust/backend/rust-tree.h
  gcc/rust/checks/errors/privacy/rust-visibility-resolver.cc
  gcc/rust/checks/errors/rust-const-checker.cc
  gcc/rust/checks/errors/rust-feature.cc
  gcc/rust/expand/rust-expand-visitor.cc
  gcc/rust/expand/rust-macro-expand.cc
  gcc/rust/expand/rust-macro-expand.h
  gcc/rust/expand/rust-macro-invoc-lexer.h
  gcc/rust/expand/rust-macro-substitute-ctx.cc
  gcc/rust/expand/rust-proc-macro-invoc-lexer.h
  gcc/rust/expand/rust-proc-macro.cc
  gcc/rust/hir/rust-ast-lower-base.cc
  gcc/rust/hir/rust-ast-lower-expr.cc
  gcc/rust/hir/rust-ast-lower-pattern.cc
  gcc/rust/hir/rust-ast-lower-type.cc
  gcc/rust/hir/rust-hir-dump.cc
  gcc/rust/hir/tree/rust-hir.cc
  gcc/rust/lex/rust-lex.cc
  gcc/rust/lex/rust-token.cc
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/parse/rust-parse.cc
  gcc/rust/resolve/rust-ast-resolve-path.cc
  gcc/rust/resolve/rust-ast-resolve-pattern.cc
  gcc/rust/resolve/rust-ast-resolve-type.cc
  gcc/rust/rust-gcc.cc
  gcc/rust/rust-lang.cc
  gcc/rust/rust-system.h
  gcc/rust/typecheck/rust-autoderef.h
  gcc/rust/typecheck/rust-hir-path-probe.cc
  gcc/rust/typecheck/rust-hir-trait-reference.cc
  gcc/rust/typecheck/rust-hir-type-check-base.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check-implitem.cc
  gcc/rust/typecheck/rust-hir-type-check-pattern.cc
  gcc/rust/typecheck/rust-hir-type-check-stmt.h
  gcc/rust/typecheck/rust-hir-type-check.cc
  gcc/rust/typecheck/rust-substitution-mapper.h
  gcc/rust/typecheck/rust-typecheck-context.cc
  gcc/rust/typecheck/rust-tyty-call.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-unify.cc
  gcc/rust/util/rust-token-converter.cc
Labels: enhancement, cleanup

#2407 [E0093] Declaration of unknown intrinsic function
  gcc/rust/backend/rust-compile-intrinsic.cc
  gcc/testsuite/rust/compile/torture/intrinsics-3.rs
Labels: diagnostic

#2408 [E0658] Use of unstable feature
  gcc/rust/checks/errors/rust-feature-gate.cc
  gcc/testsuite/rust/compile/changed_intrinsics.rs
Labels: diagnostic

#2429 Remove ```Linemap::predeclared_location```
  gcc/rust/backend/rust-compile-type.cc
  gcc/rust/resolve/rust-name-resolver.cc
  gcc/rust/rust-linemap.h
  gcc/rust/typecheck/rust-hir-type-check-type.cc
  gcc/rust/typecheck/rust-tyty.cc
Labels: cleanup

#2428 Move some ```Gcc_backend``` method definitions out of class declaration
  gcc/rust/rust-gcc.cc
Labels: cleanup

#2343 nr2.0: Add basic Rib class
  gcc/rust/Make-lang.in
  gcc/rust/resolve/rust-rib.cc
  gcc/rust/resolve/rust-rib.h
Labels: enhancement

#2261 Rework the HIR dump pass
  gcc/rust/hir/rust-hir-dump.cc
  gcc/rust/hir/rust-hir-dump.h
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/hir/tree/rust-hir-type.h
  gcc/rust/hir/tree/rust-hir.cc
  gcc/rust/util/rust-common.h
Labels: enhancement

#2344 nr2.0: Add `ForeverStack` data structure.
  gcc/rust/resolve/rust-forever-stack.h
  gcc/rust/resolve/rust-forever-stack.hxx
Labels: enhancement

#2435 cli: Add frust-type option
  gcc/rust/lang.opt
  gcc/rust/rust-session-manager.cc
  gcc/rust/rust-session-manager.h
Labels: enhancement

#2453 [E0268] break or continue used outside of loop
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/testsuite/rust/compile/break1.rs
  gcc/testsuite/rust/compile/break_continue_outside_loop.rs
  gcc/testsuite/rust/compile/continue1.rs
Labels: enhancement, diagnostic

#2447 Replace default argument with ```UNDEF_LOCATION```
  gcc/rust/ast/rust-ast-collector.h
Labels: enhancement

#2448 Replace ```Location``` with ```location_t``` in gccrs backend
  gcc/rust/backend/rust-compile-base.cc
  gcc/rust/backend/rust-compile-base.h
  gcc/rust/backend/rust-compile-block.cc
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/backend/rust-compile-extern.h
  gcc/rust/backend/rust-compile-implitem.h
  gcc/rust/backend/rust-compile-intrinsic.cc
  gcc/rust/backend/rust-compile-item.h
  gcc/rust/backend/rust-compile-pattern.h
  gcc/rust/backend/rust-compile-resolve-path.cc
  gcc/rust/backend/rust-compile-stmt.cc
  gcc/rust/backend/rust-compile-type.cc
  gcc/rust/backend/rust-compile.cc
  gcc/rust/backend/rust-constexpr.cc
Labels: cleanup

#2222 Improve keyword check while parsing a macro match
  gcc/rust/parse/rust-parse-impl.h
Labels: enhancement

#2420 Replace usages of ```Location``` with ```location_t``` in the lexer, AST, and HIR
  gcc/rust/ast/rust-ast-builder.h
  gcc/rust/ast/rust-ast.h
  gcc/rust/ast/rust-expr.h
  gcc/rust/ast/rust-item.h
  gcc/rust/ast/rust-macro.h
  gcc/rust/ast/rust-path.h
  gcc/rust/hir/tree/rust-hir-expr.h
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/hir/tree/rust-hir-path.h
  gcc/rust/hir/tree/rust-hir.h
  gcc/rust/lex/rust-lex.cc
  gcc/rust/lex/rust-lex.h
Labels: cleanup

#2441 Replace ```Location``` with ```location_t``` in parsing and macro expansion
  gcc/rust/expand/rust-derive-clone.cc
  gcc/rust/expand/rust-derive-clone.h
  gcc/rust/expand/rust-derive-copy.cc
  gcc/rust/expand/rust-derive-copy.h
  gcc/rust/expand/rust-derive.cc
  gcc/rust/expand/rust-derive.h
  gcc/rust/expand/rust-macro-builtins.cc
  gcc/rust/expand/rust-macro-builtins.h
  gcc/rust/expand/rust-macro-expand.cc
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/parse/rust-parse.cc
  gcc/rust/parse/rust-parse.h
Labels: cleanup

#2419 Continue to replace usages of ```Location``` with ```location_t```
  gcc/rust/backend/rust-compile-base.cc
  gcc/rust/backend/rust-compile-base.h
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/lex/rust-token.h
  gcc/rust/metadata/rust-import-archive.cc
  gcc/rust/metadata/rust-imports.cc
  gcc/rust/metadata/rust-imports.h
  gcc/rust/rust-backend.h
  gcc/rust/rust-diagnostics.cc
  gcc/rust/rust-diagnostics.h
  gcc/rust/rust-gcc.cc
  gcc/rust/rust-linemap.cc
  gcc/rust/util/rust-token-converter.cc
Labels: cleanup

#2445 [E0323] Implemented associated const, expected another trait
  gcc/rust/typecheck/rust-hir-type-check-implitem.cc
  gcc/testsuite/rust/compile/non_member_const.rs
Labels: enhancement, diagnostic

#2451 [E0045] Variadic Parameters Used on Non-C ABI Function
  gcc/rust/typecheck/rust-hir-type-check-implitem.cc
  gcc/testsuite/rust/compile/abi-vardaic.rs
Labels: enhancement, diagnostic

#2457 Remove NodeId from identifiers
  gcc/rust/ast/rust-ast.h
Labels: cleanup

#2439 Replace ```Location``` with ```location_t``` in unnamed function parameters
  gcc/rust/backend/rust-compile-base.h
  gcc/rust/metadata/rust-imports.h
  gcc/rust/resolve/rust-name-resolver.cc
  gcc/rust/resolve/rust-name-resolver.h
  gcc/rust/rust-backend.h
  gcc/rust/rust-gcc.cc
  gcc/rust/rust-gcc.h
Labels: cleanup

#2462 Prevent multiple bootstrap builds from running at once
  .github/workflows/bootstrap.yml
Labels: enhancement, CI

#2468 New Error Code Framework
  gcc/rust/backend/rust-compile-intrinsic.cc
  gcc/rust/checks/errors/rust-feature-gate.cc
  gcc/rust/checks/errors/rust-unsafe-checker.cc
  gcc/rust/hir/rust-ast-lower-base.cc
  gcc/rust/resolve/rust-ast-resolve-expr.cc
  gcc/rust/resolve/rust-ast-resolve-path.cc
  gcc/rust/resolve/rust-ast-resolve-pattern.cc
  gcc/rust/resolve/rust-ast-resolve-type.cc
  gcc/rust/resolve/rust-ast-verify-assignee.h
  gcc/rust/rust-diagnostics.cc
  gcc/rust/rust-diagnostics.h
  gcc/rust/typecheck/rust-casts.cc
  gcc/rust/typecheck/rust-hir-path-probe.h
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/rust/typecheck/rust-hir-type-check-implitem.cc
  gcc/rust/typecheck/rust-hir-type-check-item.cc
  gcc/rust/typecheck/rust-hir-type-check-pattern.cc
  gcc/rust/typecheck/rust-hir-type-check-struct.cc
  gcc/rust/typecheck/rust-tyty-call.cc
  gcc/rust/typecheck/rust-tyty-subst.cc
  gcc/rust/typecheck/rust-tyty.cc
Labels: enhancement, diagnostic

#2438 Replace usages of ```Location``` with ```location_t``` in typechecking
  gcc/rust/typecheck/rust-autoderef.cc
  gcc/rust/typecheck/rust-coercion.cc
  gcc/rust/typecheck/rust-coercion.h
  gcc/rust/typecheck/rust-hir-path-probe.h
  gcc/rust/typecheck/rust-hir-trait-reference.cc
  gcc/rust/typecheck/rust-hir-trait-resolve.cc
  gcc/rust/typecheck/rust-hir-type-check-base.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check-implitem.cc
  gcc/rust/typecheck/rust-hir-type-check-item.cc
  gcc/rust/typecheck/rust-hir-type-check-path.cc
  gcc/rust/typecheck/rust-hir-type-check-pattern.cc
  gcc/rust/typecheck/rust-hir-type-check-stmt.cc
  gcc/rust/typecheck/rust-hir-type-check-struct.cc
  gcc/rust/typecheck/rust-hir-type-check-type.cc
  gcc/rust/typecheck/rust-hir-type-check-type.h
  gcc/rust/typecheck/rust-type-util.cc
  gcc/rust/typecheck/rust-type-util.h
  gcc/rust/typecheck/rust-tyty-bounds.cc
  gcc/rust/typecheck/rust-tyty-call.cc
  gcc/rust/typecheck/rust-tyty-call.h
  gcc/rust/typecheck/rust-tyty-cmp.h
  gcc/rust/typecheck/rust-tyty-subst.cc
  gcc/rust/typecheck/rust-tyty-subst.h
  gcc/rust/typecheck/rust-tyty.cc
Labels: cleanup

#2480 error codes: Add rust_error_codes.def, refactor ErrorCode enum
  gcc/rust/rust-diagnostics.cc
  gcc/rust/rust-diagnostics.h
  gcc/rust/rust_error_codes.def
Labels: enhancement

#2425 Add header file generator for Unicode normalization and alphanumeric check
  gcc/rust/Make-lang.in
  gcc/rust/rust-lang.cc
  gcc/rust/rust-system.h
  gcc/rust/util/make-rust-unicode.py
  gcc/rust/util/rust-unicode-data.h
  gcc/rust/util/rust-unicode.cc
  gcc/rust/util/rust-unicode.h
Labels: enhancement

#2484 gccrs: fix ICE when we have unimplemented/invalid trait items
  gcc/rust/typecheck/rust-hir-type-check-item.cc
  gcc/testsuite/rust/compile/issue-2478.rs
  gcc/testsuite/rust/compile/non_member_const.rs
Labels: bug

#2485 Move ```Gcc_backend``` declaration to header file
  gcc/rust/rust-backend.h
  gcc/rust/rust-gcc.cc
Labels: cleanup

#2486 gccrs: fix ice when function is outside of context
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/testsuite/rust/compile/issue-2477.rs
Labels: bug

#2463 Unicode check for crate_name attribute
  gcc/rust/lex/rust-codepoint.h
  gcc/rust/lex/rust-lex.h
  gcc/rust/rust-session-manager.cc
  gcc/rust/util/rust-unicode.cc
  gcc/rust/util/rust-unicode.h
  gcc/testsuite/rust/compile/bad-crate-name1.rs
  gcc/testsuite/rust/compile/bad-crate-name2.rs
Labels: enhancement

#2488 Add missing ```CHECKING_P``` guard to ```rust-unicode.cc```
  gcc/rust/util/rust-unicode.cc
Labels: cleanup

#2490 gccrs: Fix ICE by adding check for enum candidate's
  gcc/rust/typecheck/rust-hir-trait-resolve.cc
  gcc/rust/typecheck/rust-hir-type-check-type.cc
  gcc/testsuite/rust/compile/issue-2479.rs
Labels: bug

#2464 gccrs: use tl::optional for macro transcribers
  gcc/rust/ast/rust-ast-fragment.cc
  gcc/rust/ast/rust-ast-fragment.h
  gcc/rust/ast/rust-macro.h
  gcc/rust/expand/rust-macro-builtins.cc
  gcc/rust/expand/rust-macro-builtins.h
  gcc/rust/expand/rust-macro-expand.cc
Labels: enhancement, cleanup

#2492 fix bootstrap build
  gcc/rust/util/rust-unicode.cc
Labels: bug
