Repository Rust-GCC/gccrs, pull requests merged in 2023-04, with the labels that each got.

#2078 gccrs: Fix bad cast as a char
  gcc/rust/typecheck/rust-casts.cc
  gcc/testsuite/rust/compile/cast5.rs
Labels: enhancement

#2091 Handle "fn" and "fn_mut" lang items
  gcc/rust/util/rust-lang-item.h
Labels: enhancement

#2083 gccrs: Fix ICE using constructors for intilizers in statics
  gcc/rust/backend/rust-compile-item.cc
  gcc/testsuite/rust/execute/torture/issue-2080.rs
Labels: bug

#2099 ast: Add difference between attributes
  gcc/rust/ast/rust-ast.h
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/parse/rust-parse.h
Labels: enhancement

#2107 gccrs: Introduce AST::Visitable class for AST
  gcc/rust/ast/rust-ast-dump.cc
  gcc/rust/ast/rust-ast-dump.h
  gcc/rust/ast/rust-ast.h
Labels: enhancement

#2118 Fix inner attribute tokenstream
  gcc/rust/ast/rust-ast-tokenstream.cc
Labels: enhancement

#2001 Unify AST::IfExprConseqIf{,Let} into AST::IfExprConseqElse
  gcc/rust/ast/rust-ast-dump.cc
  gcc/rust/ast/rust-ast-dump.h
  gcc/rust/ast/rust-ast-full-decls.h
  gcc/rust/ast/rust-ast-tokenstream.cc
  gcc/rust/ast/rust-ast-tokenstream.h
  gcc/rust/ast/rust-ast-visitor.h
  gcc/rust/ast/rust-ast.cc
  gcc/rust/ast/rust-expr.h
  gcc/rust/checks/errors/rust-feature-gate.h
  gcc/rust/expand/rust-cfg-strip.cc
  gcc/rust/expand/rust-cfg-strip.h
  gcc/rust/expand/rust-expand-visitor.cc
  gcc/rust/expand/rust-expand-visitor.h
  gcc/rust/hir/rust-ast-lower-base.cc
  gcc/rust/hir/rust-ast-lower-base.h
  gcc/rust/hir/rust-ast-lower-block.h
  gcc/rust/hir/rust-ast-lower-expr.cc
  gcc/rust/hir/rust-ast-lower-expr.h
  gcc/rust/hir/rust-ast-lower.cc
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/resolve/rust-ast-resolve-base.cc
  gcc/rust/resolve/rust-ast-resolve-base.h
  gcc/rust/resolve/rust-ast-resolve-expr.cc
  gcc/rust/resolve/rust-ast-resolve-expr.h
  gcc/rust/resolve/rust-early-name-resolver.cc
  gcc/rust/resolve/rust-early-name-resolver.h
  gcc/rust/util/rust-attributes.cc
  gcc/rust/util/rust-attributes.h
Labels: cleanup

#2002 Unify AST::IfLetExprConseqIf{,Let} into AST::IfLetExprConseqElse
  gcc/rust/ast/rust-ast-dump.cc
  gcc/rust/ast/rust-ast-dump.h
  gcc/rust/ast/rust-ast-full-decls.h
  gcc/rust/ast/rust-ast-tokenstream.cc
  gcc/rust/ast/rust-ast-tokenstream.h
  gcc/rust/ast/rust-ast-visitor.h
  gcc/rust/ast/rust-ast.cc
  gcc/rust/ast/rust-expr.h
  gcc/rust/checks/errors/rust-feature-gate.h
  gcc/rust/expand/rust-cfg-strip.cc
  gcc/rust/expand/rust-cfg-strip.h
  gcc/rust/expand/rust-expand-visitor.cc
  gcc/rust/expand/rust-expand-visitor.h
  gcc/rust/hir/rust-ast-lower-base.cc
  gcc/rust/hir/rust-ast-lower-base.h
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/resolve/rust-ast-resolve-base.cc
  gcc/rust/resolve/rust-ast-resolve-base.h
  gcc/rust/resolve/rust-early-name-resolver.cc
  gcc/rust/resolve/rust-early-name-resolver.h
  gcc/rust/util/rust-attributes.cc
  gcc/rust/util/rust-attributes.h
Labels: cleanup

#2100 Fix StructExprStructFields tokenstream
  gcc/rust/ast/rust-ast-tokenstream.cc
Labels: bug

#2098 parser: macro: reject separator in `?` repetition
  gcc/rust/parse/rust-parse-impl.h
  gcc/testsuite/rust/compile/macro-issue2092.rs
Labels: bug

#2110 Lower ```if let```
  gcc/rust/hir/rust-ast-lower-block.h
  gcc/rust/hir/rust-ast-lower-expr.cc
  gcc/rust/hir/rust-ast-lower-expr.h
  gcc/rust/hir/rust-ast-lower.cc
  gcc/rust/hir/tree/rust-hir-expr.h
  gcc/rust/resolve/rust-ast-resolve-expr.cc
  gcc/rust/resolve/rust-ast-resolve-expr.h
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/testsuite/rust/compile/if_let_expr.rs
Labels: enhancement

#2124 Lower ErrorPropagationExpr from AST to HIR
  gcc/rust/hir/rust-ast-lower-expr.cc
  gcc/rust/hir/rust-ast-lower-expr.h
Labels: enhancement

#2072 gccrs: Add testcase to show matching of enum variants
  gcc/testsuite/rust/compile/issue-852.rs
Labels: bug

#2122 Fix Bad formatting in AST expanded dump with associated types
  gcc/rust/ast/rust-ast-dump.cc
Labels: enhancement

#2009 Add error message for AltPattern in let statements
  gcc/rust/hir/rust-ast-lower-pattern.cc
  gcc/rust/hir/rust-ast-lower-pattern.h
  gcc/rust/hir/rust-ast-lower-stmt.cc
  gcc/testsuite/rust/compile/let_alt.rs
Labels: enhancement

#2138 parser: Parse reference patterns correctly
  gcc/rust/parse/rust-parse-impl.h
  gcc/testsuite/rust/compile/issue-1807.rs
Labels: enhancement

#2114 Deleted the as_string AST dump
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/rust-session-manager.cc
  gcc/rust/rust-session-manager.h
Labels: cleanup

#2119 libproc_macro: Add Punct type
  libgrust/libproc_macro/Makefile.am
  libgrust/libproc_macro/Makefile.in
  libgrust/libproc_macro/punct.cc
  libgrust/libproc_macro/punct.h
Labels: enhancement

#2151 Resolve identifier-pattern struct pattern fields
  gcc/rust/resolve/rust-ast-resolve-pattern.cc
Labels: bug

#2149 Add libgrust to clang-format checker
  .github/workflows/clang-format.yml
Labels: automation

#2145 patterns: Add execution testcases to verify proper pattern matching
  gcc/testsuite/rust/execute/torture/issue-1852-1.rs
  gcc/testsuite/rust/execute/torture/issue-1852.rs
Labels: testsuite

#2158 gccrs: Fix ICE during method resolution
  gcc/rust/typecheck/rust-hir-dot-operator.cc
  gcc/testsuite/rust/compile/issue-2139.rs
Labels: bug

#2155 Fix -frust-dump-* error messages
  gcc/rust/rust-session-manager.cc
Labels: documentation

#2163 gccrs: Minor tuning in AST dump
  gcc/rust/ast/rust-ast-dump.cc
Labels: enhancement

#2164 Add accessors to HIR::StructPatternFieldIdentPat
  gcc/rust/hir/tree/rust-hir-pattern.h
Labels: enhancement

#2168 gccrs: resolve the associated_predicate when mapping Fn traits
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.h
Labels: bug

#2174 Type check StructPatternFieldIdentPat
  gcc/rust/typecheck/rust-hir-type-check-pattern.cc
Labels: bug, enhancement

#2171 gccrs: Improve operator overload check for recursive overload
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
Labels: bug, enhancement

#2134 Add frust-extern option
  gcc/rust/lang.opt
  gcc/rust/rust-session-manager.cc
  gcc/rust/rust-session-manager.h
Labels: enhancement
