Repository Rust-GCC/gccrs, pull requests merged in 2023-06, with the labels that each got.

#2251 macro-invoc-lexer: Add Copyright header.
  gcc/rust/expand/rust-macro-invoc-lexer.cc
  gcc/rust/expand/rust-macro-substitute-ctx.cc
Labels: cleanup

#2254 gccrs: get rid of useless helper class and fix header usage
  gcc/rust/Make-lang.in
  gcc/rust/backend/rust-compile-block.h
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/backend/rust-compile-fnparam.h
  gcc/rust/backend/rust-compile-item.h
  gcc/rust/backend/rust-compile-pattern.h
  gcc/rust/backend/rust-compile-resolve-path.h
  gcc/rust/backend/rust-compile-stmt.h
  gcc/rust/typecheck/rust-autoderef.cc
  gcc/rust/typecheck/rust-hir-path-probe.cc
  gcc/rust/typecheck/rust-hir-path-probe.h
  gcc/rust/typecheck/rust-hir-trait-reference.h
  gcc/rust/typecheck/rust-hir-trait-resolve.cc
  gcc/rust/typecheck/rust-hir-trait-resolve.h
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check-implitem.h
  gcc/rust/typecheck/rust-hir-type-check-item.h
  gcc/rust/typecheck/rust-hir-type-check-path.cc
  gcc/rust/typecheck/rust-hir-type-check-pattern.h
  gcc/rust/typecheck/rust-hir-type-check-stmt.h
  gcc/rust/typecheck/rust-hir-type-check-type.h
  gcc/rust/typecheck/rust-hir-type-check-util.cc
  gcc/rust/typecheck/rust-hir-type-check-util.h
Labels: cleanup

#2249 Properly match delimiters
  gcc/rust/expand/rust-macro-expand.cc
  gcc/rust/expand/rust-macro-expand.h
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/parse/rust-parse.h
  gcc/testsuite/rust/compile/macro-delim.rs
Labels: bug

#2255 derive: Add #[derive(Clone)] for regular structs
  gcc/rust/ast/rust-ast-builder.cc
  gcc/rust/ast/rust-ast-builder.h
  gcc/rust/expand/rust-derive-clone.cc
  gcc/testsuite/rust/execute/torture/derive_macro4.rs
Labels: enhancement

#2183 fixup: Fix bootstrap build
  Makefile.def
  Makefile.in
Labels: GCC

#2258 builtin-derive-macros: Add dummy builtin transcriber for builtin derive macros.
  gcc/rust/expand/rust-macro-builtins.cc
  gcc/rust/expand/rust-macro-builtins.h
  gcc/testsuite/rust/compile/derive_macro7.rs
Labels: enhancement

#2265 ast: dump literals correctly
  gcc/rust/ast/rust-ast-dump.cc
Labels: enhancement

#2270 Allow parsing a borrow from struct expression
  gcc/rust/parse/rust-parse-impl.h
  gcc/testsuite/rust/compile/struct-expr-parse.rs
Labels: bug

#2267 Handle crate metavariable
  gcc/rust/expand/rust-macro-substitute-ctx.cc
Labels: enhancement

#2269 Fix warning generated by Optional
  gcc/rust/util/rust-optional.h
Labels: bug

#2271 gccrs: Respect the concrete type when resolving qualifed path types
  gcc/rust/typecheck/rust-hir-trait-resolve.cc
  gcc/rust/typecheck/rust-hir-type-check-path.cc
  gcc/rust/typecheck/rust-hir-type-check-type.cc
  gcc/testsuite/rust/compile/issue-2165.rs
  gcc/testsuite/rust/compile/issue-2166.rs
Labels: bug

#2227 Handle file loading from "non-mod-rs" files properly
  gcc/rust/Make-lang.in
  gcc/rust/ast/rust-ast.cc
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/util/rust-dir-owner.cc
  gcc/rust/util/rust-dir-owner.h
  gcc/testsuite/rust/compile/issue-1089/test_mod.rs
  gcc/testsuite/rust/compile/mod_missing_middle.rs
  gcc/testsuite/rust/compile/mod_missing_middle/missing_middle/both_path.rs
  gcc/testsuite/rust/compile/mod_missing_middle/missing_middle/explicit.not.rs
  gcc/testsuite/rust/compile/mod_missing_middle/missing_middle/explicit.not/other.rs
  gcc/testsuite/rust/compile/mod_missing_middle/missing_middle/inner_path.rs
  gcc/testsuite/rust/compile/mod_missing_middle/missing_middle/outer_path.rs
  gcc/testsuite/rust/compile/mod_missing_middle/missing_middle/sub/mod.rs
  gcc/testsuite/rust/compile/torture/extern_mod1/modules/mod.rs
  gcc/testsuite/rust/execute/torture/extern_mod4/modules/mod.rs
Labels: enhancement

#2285 gccrs: introduce new types_compatable
  gcc/rust/typecheck/rust-hir-type-check-implitem.cc
  gcc/rust/typecheck/rust-type-util.cc
  gcc/rust/typecheck/rust-type-util.h
  gcc/rust/typecheck/rust-unify.cc
  gcc/testsuite/rust/compile/traits2.rs
  gcc/testsuite/rust/compile/traits3.rs
Labels: bug

#2291 fixup: Remove obsolete error diagnostic
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/testsuite/rust/compile/break1.rs
  gcc/testsuite/rust/compile/break2.rs
  gcc/testsuite/rust/compile/cfg2.rs
  gcc/testsuite/rust/compile/continue1.rs
  gcc/testsuite/rust/compile/generics4.rs
  gcc/testsuite/rust/compile/generics6.rs
  gcc/testsuite/rust/compile/generics7.rs
  gcc/testsuite/rust/compile/issue-2029.rs
  gcc/testsuite/rust/compile/issue-2139.rs
  gcc/testsuite/rust/compile/issue-2190-1.rs
  gcc/testsuite/rust/compile/issue-925.rs
  gcc/testsuite/rust/compile/method1.rs
  gcc/testsuite/rust/compile/shadow1.rs
  gcc/testsuite/rust/compile/type-bindings1.rs
  gcc/testsuite/rust/compile/unary_negation.rs
  gcc/testsuite/rust/compile/unary_not.rs
  gcc/testsuite/rust/compile/unconstrained_type_param.rs
  gcc/testsuite/rust/compile/usize1.rs
Labels: cleanup

#2283 Fix ICE for reference patterns in match statements
  gcc/rust/backend/rust-compile-expr.cc
  gcc/testsuite/rust/compile/issue-1813.rs
Labels: bug

#2289 gccrs: ensure assoicated types are setup for concrete trait impl blocks
  gcc/rust/backend/rust-compile-item.cc
  gcc/rust/typecheck/rust-hir-trait-reference.h
  gcc/rust/typecheck/rust-hir-trait-resolve.cc
  gcc/testsuite/rust/compile/issue-2019-1.rs
Labels: bug

#2293 derive: Factor common fields inside the base visitor
  gcc/rust/expand/rust-derive-clone.cc
  gcc/rust/expand/rust-derive-clone.h
  gcc/rust/expand/rust-derive-copy.cc
  gcc/rust/expand/rust-derive-copy.h
  gcc/rust/expand/rust-derive.cc
  gcc/rust/expand/rust-derive.h
Labels: cleanup

#2297 gccrs: fortify resolve_method_address to match the types
  gcc/rust/backend/rust-compile-base.cc
  gcc/testsuite/rust/compile/issue-2019-2.rs
  gcc/testsuite/rust/compile/issue-2019-3.rs
Labels: bug

#2298 fixup: Remove old typecheck dump
  gcc/rust/rust-session-manager.cc
  gcc/rust/rust-session-manager.h
  gcc/rust/typecheck/rust-tycheck-dump.h
Labels: cleanup

#2299 gccrs: we can't check the bounds involving empty placeholder types
  gcc/rust/typecheck/rust-unify.cc
  gcc/testsuite/rust/compile/issue-2036.rs
Labels: bug

#2290 Remove direct error on macro rule count-related match failure
  gcc/rust/expand/rust-macro-expand.cc
  gcc/testsuite/rust/compile/macro-issue2229.rs
  gcc/testsuite/rust/compile/macro6.rs
  gcc/testsuite/rust/compile/macro7.rs
Labels: bug

#2301 ErrorCode[E0433]: Use of Undeclared Crate, Module, or Type
  gcc/rust/resolve/rust-ast-resolve-path.cc
  gcc/rust/resolve/rust-ast-resolve-type.cc
Labels: enhancement

#2260 Make MatchedFragmentContainer a tree-like structure
  gcc/rust/expand/rust-macro-expand.cc
  gcc/rust/expand/rust-macro-expand.h
  gcc/rust/expand/rust-macro-substitute-ctx.cc
  gcc/rust/expand/rust-macro-substitute-ctx.h
Labels: enhancement

#2319 Expand expressions/types correctly in more contexts.
  gcc/rust/expand/rust-expand-visitor.cc
  gcc/rust/resolve/rust-early-name-resolver.cc
  gcc/testsuite/rust/compile/macro54.rs
  gcc/testsuite/rust/compile/macro55.rs
Labels: bug

#2315 ErrorCode[E0277] Type Does Not Implement Expected Trait
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/rust/typecheck/rust-tyty.cc
Labels: enhancement

#2321 gccrs: Add method selection to operator overloading
  gcc/rust/typecheck/rust-autoderef.cc
  gcc/rust/typecheck/rust-hir-dot-operator.cc
  gcc/rust/typecheck/rust-hir-dot-operator.h
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/rust/typecheck/rust-type-util.cc
  gcc/rust/typecheck/rust-type-util.h
  gcc/testsuite/rust/compile/issue-2304.rs
Labels: bug

#2322 gccrs: Stop autoderef of raw pointer types
  gcc/rust/typecheck/rust-autoderef.cc
Labels: bug

#2316 rust: Add -frust-name-resolution-2.0 option
  gcc/rust/lang.opt
Labels: enhancement

#2329 Match tokens in macros more closely
  gcc/rust/expand/rust-macro-expand.cc
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/parse/rust-parse.h
  gcc/testsuite/rust/compile/macro-issue2264.rs
Labels: bug

#2326 [E0026] Non-Existent Field Extraction in Struct Pattern
  gcc/rust/typecheck/rust-hir-type-check-pattern.cc
Labels: enhancement, diagnostic

#2325 [E0023] Incorrect Number of Fields in Pattern Extraction
  gcc/rust/typecheck/rust-hir-type-check-pattern.cc
Labels: enhancement, diagnostic

#2279 Fix empty nested repetitions
  gcc/rust/expand/rust-macro-expand.cc
  gcc/rust/expand/rust-macro-expand.h
  gcc/testsuite/rust/compile/macro-issue2268.rs
Labels: enhancement

#2339 Fix lexer to skip utf-8 whitespaces
  gcc/rust/lex/rust-lex.cc
  gcc/testsuite/rust/compile/torture/utf8_whitespaces.rs
Labels: enhancement

#2338 Missing tests for utf-8 identifiers
  gcc/testsuite/rust/compile/torture/raw_identifiers.rs
  gcc/testsuite/rust/compile/torture/utf8_identifiers.rs
Labels: enhancement

#2266 Fix macro nested repetitions
  gcc/rust/expand/rust-macro-expand.cc
  gcc/rust/expand/rust-macro-expand.h
  gcc/testsuite/rust/compile/macro56.rs
Labels: enhancement

#2341 Refactored Field Error Function
  gcc/rust/typecheck/rust-hir-type-check-pattern.cc
Labels: cleanup

#2320 Fix lexing byte literal
  gcc/rust/lex/rust-lex.cc
  gcc/testsuite/rust/compile/bytecharstring.rs
Labels: bug

#2352 Fix type hint propagation
  gcc/rust/ast/rust-pattern.h
  gcc/rust/parse/rust-parse-impl.h
Labels: bug

#2353 abi: Add testcase for using "Rust" as ABI string
  gcc/testsuite/rust/compile/rust_abi.rs
Labels: testsuite

#2335 [E0027] struct pattern fails to specify struct's fields
  gcc/rust/typecheck/rust-hir-type-check-pattern.cc
Labels: diagnostic

#2355 gccrs: fix ICE with inserting autoderef mappings
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
Labels: bug
