Repository Rust-GCC/gccrs, pull requests merged in 2023-03, with the labels that each got.

#1938 Fix casting error behind generics [WIP]
  gcc/rust/typecheck/rust-casts.cc
  gcc/testsuite/rust/compile/cast_generics.rs
Labels: bug

#1942 Fix assignment operator overloads for AST and HIR patterns
  gcc/rust/ast/rust-pattern.h
  gcc/rust/hir/tree/rust-hir-pattern.h
Labels: cleanup

#1929 Add feature gate definition for `extern_types`.
  gcc/rust/checks/errors/rust-feature-gate.cc
  gcc/rust/checks/errors/rust-feature-gate.h
  gcc/rust/checks/errors/rust-feature.cc
  gcc/rust/checks/errors/rust-feature.h
  gcc/testsuite/rust/compile/feature_extern_types.rs
Labels: enhancement

#1946 hir: Refactor ASTLoweringStmt to source file.
  gcc/rust/Make-lang.in
  gcc/rust/hir/rust-ast-lower-stmt.cc
  gcc/rust/hir/rust-ast-lower-stmt.h
Labels: cleanup

#1945 gccrs: add {add,sub,mul}_with_overflow intrinsics
  gcc/rust/backend/rust-compile-intrinsic.cc
  gcc/testsuite/rust/compile/torture/intrinsics-8.rs
Labels: bug, enhancement

#1933 an attempt to implement pretty HIR dump
  gcc/rust/hir/rust-hir-dump.cc
Labels: enhancement

#1943 Fix bootstrap compile error
  gcc/rust/parse/rust-parse-impl.h
Labels: bug, enhancement

#1953 Parse zero sized slice pattern
  gcc/rust/parse/rust-parse-impl.h
  gcc/testsuite/rust/compile/zero_sized_slice.rs
Labels: enhancement

#1948 gccrs: add uninit intrinsic
  gcc/rust/backend/rust-builtins.cc
  gcc/rust/backend/rust-compile-intrinsic.cc
  gcc/testsuite/rust/compile/torture/uninit-intrinsic-1.rs
Labels: enhancement

#1951 parser: Fix while let expr parsing
  gcc/rust/parse/rust-parse-impl.h
  gcc/testsuite/rust/compile/while_let_expr.rs
Labels: bug

#1960 parser: Fix parsing closure parameter
  gcc/rust/parse/rust-parse-impl.h
  gcc/testsuite/rust/compile/closure_no_type_anno.rs
Labels: bug

#1962 gccrs: Take advantage of our new unify_and to inject inference
  gcc/rust/typecheck/rust-hir-trait-resolve.cc
Labels: bug

#1964 Resolve closure parameters without given type
  gcc/rust/resolve/rust-early-name-resolver.cc
  gcc/testsuite/rust/compile/closure_no_type_anno.rs
Labels: bug

#1967 Cleanup and Assertion
  gcc/rust/hir/rust-ast-lower-type.cc
  gcc/rust/rust-object-export.cc
Labels: cleanup

#1966 parser: Fix handling of multiple left angles in null denotation
  gcc/rust/parse/rust-parse-impl.h
  gcc/testsuite/rust/compile/complex_qualified_path_in_expr.rs
Labels: bug

#1963 Add length checking for tuple patterns. Resolves issue Rust-GCC#1849
  gcc/rust/typecheck/rust-hir-type-check-pattern.cc
  gcc/rust/typecheck/rust-hir-type-check-pattern.h
  gcc/testsuite/rust/compile/tuple_mismatch.rs
Labels: bug, enhancement

#1969 Add stringify macro expansion
  gcc/rust/ast/rust-macro.cc
  gcc/rust/ast/rust-macro.h
  gcc/rust/expand/rust-macro-builtins.cc
  gcc/rust/expand/rust-macro-builtins.h
  gcc/rust/util/rust-hir-map.cc
  gcc/testsuite/rust/compile/stringify.rs
  gcc/testsuite/rust/execute/torture/builtin_macro_stringify.rs
Labels: enhancement

#1888 Add AltPattern HIR node
  gcc/rust/backend/rust-compile-fnparam.h
  gcc/rust/backend/rust-compile-pattern.h
  gcc/rust/backend/rust-compile-resolve-path.h
  gcc/rust/backend/rust-compile-var-decl.h
  gcc/rust/checks/errors/rust-const-checker.cc
  gcc/rust/checks/errors/rust-const-checker.h
  gcc/rust/checks/errors/rust-unsafe-checker.cc
  gcc/rust/checks/errors/rust-unsafe-checker.h
  gcc/rust/hir/rust-hir-dump.cc
  gcc/rust/hir/rust-hir-dump.h
  gcc/rust/hir/tree/rust-hir-full-decls.h
  gcc/rust/hir/tree/rust-hir-pattern.h
  gcc/rust/hir/tree/rust-hir-visitor.h
  gcc/rust/hir/tree/rust-hir.h
  gcc/rust/typecheck/rust-hir-type-check-pattern.cc
  gcc/rust/typecheck/rust-hir-type-check-pattern.h
Labels: enhancement

#1970 Fix handling of coherence related lang_items
  gcc/rust/util/rust-lang-item.h
  gcc/testsuite/rust/compile/lang-impl.rs
Labels: enhancement

#1971 typecheck: Add basic typechecking for ReferenceType
  gcc/rust/hir/tree/rust-hir-pattern.h
  gcc/rust/resolve/rust-ast-resolve-pattern.h
  gcc/rust/typecheck/rust-hir-type-check-pattern.cc
  gcc/testsuite/rust/compile/ref_pattern_fn_param.rs
Labels: enhancement

#1980 hir: Fix `ReferencePattern` typechecking
  gcc/rust/typecheck/rust-hir-type-check-pattern.cc
Labels: bug

#1957 enr: Fetch module items during early name resolution
  gcc/rust/expand/rust-attribute-visitor.cc
  gcc/rust/resolve/rust-early-name-resolver.cc
Labels: enhancement

#1974 hir: Provide basic handling for `ReferencePattern`
  gcc/rust/backend/rust-compile-fnparam.cc
  gcc/rust/backend/rust-compile-fnparam.h
  gcc/rust/backend/rust-compile-pattern.cc
  gcc/rust/backend/rust-compile-pattern.h
  gcc/testsuite/rust/compile/ref_pattern_fn_param1.rs
  gcc/testsuite/rust/compile/ref_pattern_fn_param2.rs
  gcc/testsuite/rust/execute/torture/ref-pattern1.rs
Labels: enhancement

#1947 hir: Add ExportedMacro node and handling.
  gcc/rust/backend/rust-compile-item.h
  gcc/rust/backend/rust-compile-stmt.h
  gcc/rust/checks/errors/privacy/rust-privacy-reporter.cc
  gcc/rust/checks/errors/privacy/rust-privacy-reporter.h
  gcc/rust/checks/errors/privacy/rust-pub-restricted-visitor.cc
  gcc/rust/checks/errors/privacy/rust-pub-restricted-visitor.h
  gcc/rust/checks/errors/privacy/rust-reachability.cc
  gcc/rust/checks/errors/privacy/rust-reachability.h
  gcc/rust/checks/errors/privacy/rust-visibility-resolver.cc
  gcc/rust/checks/errors/privacy/rust-visibility-resolver.h
  gcc/rust/checks/errors/rust-const-checker.cc
  gcc/rust/checks/errors/rust-const-checker.h
  gcc/rust/checks/errors/rust-unsafe-checker.cc
  gcc/rust/checks/errors/rust-unsafe-checker.h
  gcc/rust/hir/rust-ast-lower-item.cc
  gcc/rust/hir/rust-ast-lower-item.h
  gcc/rust/hir/rust-hir-dump.cc
  gcc/rust/hir/rust-hir-dump.h
  gcc/rust/hir/tree/rust-hir-full-decls.h
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/hir/tree/rust-hir-visitor.h
  gcc/rust/hir/tree/rust-hir.cc
  gcc/rust/hir/tree/rust-hir.h
  gcc/rust/metadata/rust-export-metadata.cc
  gcc/rust/typecheck/rust-hir-type-check-item.h
  gcc/rust/typecheck/rust-hir-type-check-stmt.cc
  gcc/rust/typecheck/rust-hir-type-check-stmt.h
  gcc/rust/typecheck/rust-tycheck-dump.h
  gcc/rust/util/rust-attributes.cc
Labels: enhancement

#1988 gccrs: Rename compiler proper to crab1
  README.md
  gcc/rust/Make-lang.in
  gcc/rust/config-lang.in
  gcc/rust/lang-specs.h
  gcc/rust/rustspec.cc
Labels: enhancement

#1989 hir: Improve pattern bindings handling in closure parameters
  gcc/rust/backend/rust-compile-expr.cc
  gcc/testsuite/rust/execute/torture/closure4.rs
  gcc/testsuite/rust/execute/torture/ref-pattern2.rs
Labels: enhancement

#1983 resolve: Handle multiple bindings to the same identifier
  gcc/rust/resolve/rust-ast-resolve-expr.cc
  gcc/rust/resolve/rust-ast-resolve-expr.h
  gcc/rust/resolve/rust-ast-resolve-item.cc
  gcc/rust/resolve/rust-ast-resolve-pattern.cc
  gcc/rust/resolve/rust-ast-resolve-pattern.h
  gcc/rust/resolve/rust-ast-resolve-stmt.h
  gcc/testsuite/rust/compile/multiple_bindings1.rs
Labels: enhancement

#1965 Allow all keywords (except `priv`) to follow `:vis` in macro rules
  gcc/rust/parse/rust-parse.cc
  gcc/testsuite/rust/compile/macro47.rs
  gcc/testsuite/rust/compile/macro48.rs
Labels: bug

#1997 resolve: Fix multiple bindings handling in match
  gcc/rust/resolve/rust-ast-resolve-expr.cc
  gcc/testsuite/rust/compile/multiple_bindings2.rs
Labels: enhancement

#1994 Unify HIR::IfExprConseqIf{,Let} into HIR::IfExprConseqElse
  gcc/rust/backend/rust-compile-block.cc
  gcc/rust/backend/rust-compile-block.h
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/checks/errors/privacy/rust-privacy-reporter.cc
  gcc/rust/checks/errors/privacy/rust-privacy-reporter.h
  gcc/rust/checks/errors/rust-const-checker.cc
  gcc/rust/checks/errors/rust-const-checker.h
  gcc/rust/checks/errors/rust-unsafe-checker.cc
  gcc/rust/checks/errors/rust-unsafe-checker.h
  gcc/rust/checks/lints/rust-lint-marklive.h
  gcc/rust/hir/rust-ast-lower.cc
  gcc/rust/hir/rust-hir-dump.cc
  gcc/rust/hir/rust-hir-dump.h
  gcc/rust/hir/tree/rust-hir-expr.h
  gcc/rust/hir/tree/rust-hir-full-decls.h
  gcc/rust/hir/tree/rust-hir-visitor.h
  gcc/rust/hir/tree/rust-hir.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.h
Labels: cleanup

#1995 Unify HIR::IfLetExprConseqIf{,Let} into HIR::IfLetExprConseqElse
  gcc/rust/backend/rust-compile-block.h
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/checks/errors/privacy/rust-privacy-reporter.cc
  gcc/rust/checks/errors/privacy/rust-privacy-reporter.h
  gcc/rust/checks/errors/rust-const-checker.cc
  gcc/rust/checks/errors/rust-const-checker.h
  gcc/rust/checks/errors/rust-unsafe-checker.cc
  gcc/rust/checks/errors/rust-unsafe-checker.h
  gcc/rust/hir/rust-hir-dump.cc
  gcc/rust/hir/rust-hir-dump.h
  gcc/rust/hir/tree/rust-hir-expr.h
  gcc/rust/hir/tree/rust-hir-full-decls.h
  gcc/rust/hir/tree/rust-hir-visitor.h
  gcc/rust/hir/tree/rust-hir.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.h
Labels: cleanup

#1993 resolve: Add name resolution for AltPattern
  gcc/rust/resolve/rust-ast-resolve-pattern.cc
  gcc/rust/resolve/rust-ast-resolve-pattern.h
  gcc/testsuite/rust/compile/torture/alt_patterns1.rs
Labels: enhancement

#1976 Impl `Rust::HIR::Dump::visit`
  gcc/rust/hir/rust-hir-dump.cc
  gcc/rust/hir/rust-hir-dump.h
Labels: enhancement

#2006 Remove unused ResolvePattern visitor
  gcc/rust/resolve/rust-ast-resolve-pattern.h
Labels: cleanup

#1992 ci: Do not run `check-gccrs-prefix` on PRs to master
  .github/workflows/commit-format.yml
Labels: enhancement, upstream

#2010 gccrs: Cleanup unused headers
  gcc/rust/hir/rust-ast-lower-implitem.h
  gcc/rust/hir/rust-ast-lower-item.cc
  gcc/rust/hir/rust-ast-lower-item.h
  gcc/rust/hir/rust-ast-lower-stmt.cc
  gcc/rust/hir/rust-ast-lower-stmt.h
  gcc/rust/hir/rust-ast-lower-type.h
  gcc/rust/hir/rust-ast-lower.cc
  gcc/rust/hir/rust-ast-lower.h
  gcc/rust/resolve/rust-ast-resolve-expr.h
  gcc/rust/resolve/rust-ast-resolve-item.cc
  gcc/rust/resolve/rust-ast-resolve-item.h
  gcc/rust/resolve/rust-ast-resolve-stmt.cc
  gcc/rust/resolve/rust-ast-resolve-stmt.h
  gcc/rust/resolve/rust-ast-resolve-struct-expr-field.h
  gcc/rust/resolve/rust-ast-resolve-toplevel.h
  gcc/rust/resolve/rust-ast-resolve-type.h
  gcc/rust/resolve/rust-ast-resolve.h
Labels: cleanup

#2007 Add name resolution and ast lowering for SlicePattern
  gcc/rust/hir/rust-ast-lower-pattern.cc
  gcc/rust/hir/rust-ast-lower-pattern.h
  gcc/rust/resolve/rust-ast-resolve-pattern.cc
  gcc/rust/resolve/rust-ast-resolve-pattern.h
Labels: enhancement

#1956 Fix `FeatureGate::gate` will crash on 32-bit x86.
  gcc/rust/checks/errors/rust-feature-gate.cc
  gcc/rust/checks/errors/rust-feature.h
Labels: bug

#2008 Lower AltPattern
  gcc/rust/hir/rust-ast-lower-pattern.cc
  gcc/rust/hir/rust-ast-lower-pattern.h
Labels: enhancement

#2013 rust-imports: Fix last few mentions of Go.
  gcc/rust/metadata/rust-imports.cc
Labels: cleanup

#2014 ast: Dump each MacroRule properly without the extra semicolon
  gcc/rust/ast/rust-ast-dump.cc
Labels: enhancement

#2046 gccrs: Fix ICE on parsing trait object missing dyn keyword
  gcc/rust/typecheck/rust-hir-type-check-item.cc
  gcc/testsuite/rust/compile/issue-2037.rs
Labels: bug

#2057 ast: Refactor rust-ast-lower-type.h to source file
  gcc/rust/hir/rust-ast-lower-type.cc
  gcc/rust/hir/rust-ast-lower-type.h
Labels: enhancement

#2055 docker: Do not run update-alternatives on invalid path
  Dockerfile
Labels: enhancement

#2051 Fix parsing of array expressions.
  gcc/rust/parse/rust-parse-impl.h
  gcc/testsuite/rust/compile/array4.rs
  gcc/testsuite/rust/execute/torture/arrays.rs
Labels: enhancement

#1856 `libproc_macro` rust interface
  libgrust/libproc_macro/rust/bridge.rs
  libgrust/libproc_macro/rust/bridge/group.rs
  libgrust/libproc_macro/rust/bridge/ident.rs
  libgrust/libproc_macro/rust/bridge/literal.rs
  libgrust/libproc_macro/rust/bridge/punct.rs
  libgrust/libproc_macro/rust/bridge/span.rs
  libgrust/libproc_macro/rust/bridge/token_stream.rs
  libgrust/libproc_macro/rust/group.rs
  libgrust/libproc_macro/rust/ident.rs
  libgrust/libproc_macro/rust/lib.rs
  libgrust/libproc_macro/rust/literal.rs
  libgrust/libproc_macro/rust/punct.rs
  libgrust/libproc_macro/rust/span.rs
  libgrust/libproc_macro/rust/token_stream.rs
Labels: enhancement

#2069 gccrs: Add missing known attribute stable
  gcc/rust/util/rust-attributes.cc
Labels: bug
