Repository Rust-GCC/gccrs, pull requests merged in 2023-05, with the labels that each got.

#2141 Fix out of bounds indexing while expanding macros with repetition
  gcc/rust/expand/rust-macro-substitute-ctx.cc
  gcc/testsuite/rust/compile/macro52.rs
Labels: bug

#2150 Proc macro type
  libgrust/libproc_macro/proc_macro.cc
  libgrust/libproc_macro/proc_macro.h
Labels: enhancement

#2196 gccrs: Add missing compile locals for constants and statics
  gcc/rust/backend/rust-compile-base.cc
  gcc/testsuite/rust/compile/issue-2178.rs
Labels: bug

#2199 Fix "default unsafe fn ..." parsing
  gcc/rust/parse/rust-parse-impl.h
  gcc/testsuite/rust/compile/parse_specialization.rs
Labels: bug

#1886 Added HIR::InlineAsm
  gcc/rust/ast/rust-ast-full-decls.h
  gcc/rust/ast/rust-expr.h
  gcc/rust/hir/tree/rust-hir-expr.h
  gcc/rust/hir/tree/rust-hir-full-decls.h
Labels: enhancement

#2200 Handle keywords in macro fragments
  gcc/rust/expand/rust-macro-expand.cc
  gcc/rust/lex/rust-token.cc
  gcc/rust/lex/rust-token.h
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/parse/rust-parse.h
  gcc/testsuite/rust/compile/macro-issue2192.rs
Labels: bug

#2208 Address invalid little-endian-only testcases
  gcc/testsuite/rust/compile/const-issue1440.rs
  gcc/testsuite/rust/compile/torture/issue-1432.rs
Labels: enhancement, cleanup

#2214 dump: Dump `TupleIndexExpr`s
  gcc/rust/ast/rust-ast-dump.cc
Labels: enhancement

#2212 Improve Optional<T&> implementation
  gcc/rust/util/rust-optional.h
Labels: enhancement

#2215 ast: Add `outer_attrs` to all `Item`s
  gcc/rust/ast/rust-ast.h
  gcc/rust/ast/rust-expr.h
  gcc/rust/ast/rust-item.h
  gcc/rust/ast/rust-macro.h
Labels: enhancement

#2221 Handle keyword metavariables during macro expansion
  gcc/rust/expand/rust-macro-substitute-ctx.cc
  gcc/rust/lex/rust-token.cc
  gcc/rust/parse/rust-parse-impl.h
  gcc/testsuite/rust/compile/macro-issue2194.rs
Labels: bug

#2213 Improve Optional<T> implementation
  gcc/rust/util/rust-optional.h
Labels: enhancement

#2210 ast: Propagate type suffix
  gcc/rust/ast/rust-ast-collector.cc
Labels: bug

#2185 Parse AST::AttrInputMacro attributes
  gcc/rust/parse/rust-parse-impl.h
  gcc/testsuite/rust/compile/doc_macro.rs
Labels: enhancement

#2230 Only check first item of cfg_attr attribute as predicate
  gcc/rust/ast/rust-ast.cc
  gcc/testsuite/rust/compile/cfg-attr.rs
Labels: enhancement

#2226 Fix macro resolutions in middle of multiple nested macro_use modules
  gcc/rust/resolve/rust-early-name-resolver.cc
  gcc/testsuite/rust/compile/nested_macro_use3.rs
Labels: bug

#2231 enr: Cleanup #[macro_use] accumulation
  gcc/rust/resolve/rust-early-name-resolver.cc
Labels: cleanup

#2241 Avoid invalid metavariable substitutions
  gcc/rust/expand/rust-macro-substitute-ctx.cc
  gcc/rust/expand/rust-macro-substitute-ctx.h
  gcc/testsuite/rust/compile/issue-2225.rs
Labels: bug

#2248 gccrs: Fix cast site to not miss type-unifications
  gcc/rust/typecheck/rust-casts.cc
  gcc/testsuite/rust/compile/issue-2195.rs
Labels: bug
