Repository Rust-GCC/gccrs, pull requests merged in 2023-08, with the labels that each got.

#2493 [E0572] return is outside of function context
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
Labels: enhancement, diagnostic

#2467 Normalize Hangul
  gcc/rust/util/rust-unicode.cc
Labels: enhancement

#2422 gccrs: better handling of incorrect file loading in include_* builtin macros
  gcc/rust/expand/rust-macro-builtins.cc
  gcc/testsuite/rust/compile/empty_file
  gcc/testsuite/rust/compile/issue-2421_str.rs
Labels: enhancement

#2494 [E0308] mismatch types on both sides of assignment Operator
  gcc/rust/typecheck/rust-unify.cc
  gcc/testsuite/rust/compile/arrays1.rs
  gcc/testsuite/rust/compile/bad_type1.rs
  gcc/testsuite/rust/compile/bad_type2.rs
  gcc/testsuite/rust/compile/const_generics_6.rs
  gcc/testsuite/rust/compile/deadcode_err1.rs
  gcc/testsuite/rust/compile/deadcode_err2.rs
  gcc/testsuite/rust/compile/func1.rs
  gcc/testsuite/rust/compile/func3.rs
  gcc/testsuite/rust/compile/func4.rs
  gcc/testsuite/rust/compile/func5.rs
  gcc/testsuite/rust/compile/generics1.rs
  gcc/testsuite/rust/compile/generics2.rs
  gcc/testsuite/rust/compile/generics3.rs
  gcc/testsuite/rust/compile/implicit_returns_err1.rs
  gcc/testsuite/rust/compile/implicit_returns_err2.rs
  gcc/testsuite/rust/compile/implicit_returns_err3.rs
  gcc/testsuite/rust/compile/implicit_returns_err4.rs
  gcc/testsuite/rust/compile/issue-1152.rs
  gcc/testsuite/rust/compile/issue-2477.rs
  gcc/testsuite/rust/compile/mismatched-types.rs
  gcc/testsuite/rust/compile/reference1.rs
  gcc/testsuite/rust/compile/stmt_with_block_err1.rs
  gcc/testsuite/rust/compile/traits1.rs
  gcc/testsuite/rust/compile/traits2.rs
  gcc/testsuite/rust/compile/tuple_mismatch.rs
  gcc/testsuite/rust/compile/tuple_struct3.rs
Labels: enhancement, diagnostic

#2513 [E0635] Use of Unknown feature.
  gcc/rust/checks/errors/rust-feature-gate.cc
  gcc/testsuite/rust/compile/feature.rs
Labels: enhancement, diagnostic

#2502 [E0426] Use of undeclared label
  gcc/rust/resolve/rust-ast-resolve-expr.cc
  gcc/testsuite/rust/compile/undeclared_label.rs
Labels: enhancement, diagnostic

#2539 [E0107] Wrong number of generic argument
  gcc/rust/typecheck/rust-tyty-subst.cc
Labels: diagnostic

#2536 [E0658] Use of mutable reference in constant functions.
  gcc/rust/checks/errors/rust-const-checker.cc
  gcc/rust/checks/errors/rust-feature-gate.cc
Labels: enhancement, diagnostic

#2538 [E0015] Use of non-const inside const
  gcc/rust/checks/errors/rust-const-checker.cc
Labels: enhancement, diagnostic

#2532 Fix a warning about extra semicolon
  gcc/rust/util/rust-common.h
Labels: cleanup

#2489 Normalize all identifiers to NFC
  gcc/rust/lex/rust-input-source.h
  gcc/rust/lex/rust-lex.cc
  gcc/rust/lex/rust-lex.h
  gcc/rust/lex/rust-token.cc
  gcc/rust/lex/rust-token.h
  gcc/rust/rust-lang.cc
  gcc/rust/rust-session-manager.cc
  gcc/rust/util/rust-unicode.cc
  gcc/rust/util/rust-unicode.h
  gcc/testsuite/rust/compile/unicode_norm1.rs
Labels: enhancement

#2506 Remove ```Backend::bool_type``` and ```Backend::char_type```
  gcc/rust/backend/rust-compile-type.cc
  gcc/rust/rust-backend.h
  gcc/rust/rust-gcc.cc
Labels: enhancement, cleanup

#2524 [E0282] type annotations needed
  gcc/rust/typecheck/rust-hir-type-check.cc
Labels: enhancement, diagnostic

#2525 [E0308] array misamatch types
  gcc/rust/backend/rust-compile.cc
  gcc/testsuite/rust/compile/arrays2.rs
Labels: enhancement, diagnostic

#2533 Implement punycode encoding
  gcc/rust/Make-lang.in
  gcc/rust/rust-lang.cc
  gcc/rust/util/rust-punycode.cc
  gcc/rust/util/rust-punycode.h
Labels: enhancement

#2503 Remove unneeded references to ```this``` in backend methods
  gcc/rust/rust-gcc.cc
Labels: cleanup

#2519 [E0703] Use of Invalid ABI
  gcc/rust/hir/rust-ast-lower-base.cc
  gcc/testsuite/rust/compile/abi-options1.rs
Labels: enhancement, diagnostic

#2540 Basic formatting/comment fixes
  gcc/rust/ast/rust-ast-collector.cc
  gcc/rust/checks/errors/rust-feature-gate.cc
  gcc/rust/rust-diagnostics.h
Labels: enhancement, cleanup

#2526 [E0541] Use of unknown meta item
  gcc/rust/backend/rust-compile-base.cc
  gcc/testsuite/rust/compile/attr_deprecated_2.rs
Labels: enhancement, diagnostic

#2528 `[E0054-E0604-E0620-E0606]` TypeCasting ErrorCodes
  gcc/rust/typecheck/rust-casts.cc
  gcc/testsuite/rust/compile/all-cast.rs
  gcc/testsuite/rust/compile/bad_as_bool_char.rs
  gcc/testsuite/rust/compile/cast1.rs
  gcc/testsuite/rust/compile/cast4.rs
  gcc/testsuite/rust/compile/cast5.rs
Labels: enhancement, diagnostic

#2543 gccrs: Adjust HIR dump for IfExpr and IfExprConseqElse
  gcc/rust/hir/rust-hir-dump.cc
  gcc/rust/hir/rust-hir-dump.h
Labels: cleanup

#2520 macro-expand: Keep optional references to last_{def, invoc}
  gcc/rust/expand/rust-macro-expand.cc
  gcc/rust/expand/rust-macro-expand.h
  gcc/rust/rust-session-manager.cc
Labels: bug, enhancement

#2530 Move Codepoint to gcc/rust/util/
  gcc/rust/lex/rust-input-source.h
  gcc/rust/util/rust-codepoint.h
  gcc/rust/util/rust-punycode.cc
  gcc/rust/util/rust-unicode.cc
Labels: enhancement

#2498 Use ```MacroInvocLexerBase``` in ```ProcMacroInvocLexer```
  gcc/rust/expand/rust-proc-macro-invoc-lexer.cc
  gcc/rust/expand/rust-proc-macro-invoc-lexer.h
Labels: cleanup

#2546 Add missing ```CHECKING_P``` guard to ```rust-punycode.cc```
  gcc/rust/util/rust-punycode.cc
Labels: cleanup

#2549 gccrs: remove horrible hack in solving complex generics on impl blocks
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
Labels: bug

#2544 gccrs: Cleanup HIR dump
  gcc/rust/hir/rust-hir-dump.cc
Labels: cleanup

#2550 gccrs: simplify matching possible candidates
  gcc/rust/backend/rust-compile-base.cc
Labels: bug

#2551 gccrs: improve name mangling hash
  gcc/rust/backend/rust-compile-intrinsic.cc
  gcc/rust/backend/rust-mangle.cc
  gcc/rust/typecheck/rust-tyty.h
Labels: bug

#2529 Add type annotation to make-rust-unicode-data.py
  gcc/rust/util/make-rust-unicode.py
Labels: cleanup

#2518 diagnostics: Fix mismatch between new[] and free
  gcc/rust/rust-diagnostics.cc
Labels: bug, enhancement

#2558 [E0534] inline attribute was malformed
  gcc/rust/backend/rust-compile-base.cc
  gcc/testsuite/rust/compile/inline_2.rs
Labels: diagnostic

#2542 Support for `rich-loc` & `errorcode` in parser & expansion errors
  gcc/rust/rust-diagnostics.cc
  gcc/rust/rust-diagnostics.h
Labels: enhancement, diagnostic

#2531 [E0753] Use of inner doc comment in invalid context
  gcc/rust/parse/rust-parse-impl.h
  gcc/testsuite/rust/compile/bad_inner_doc.rs
Labels: enhancement, diagnostic

#2527 [E0380] Use of auto trait with method or associated item
  gcc/rust/parse/rust-parse-impl.h
  gcc/testsuite/rust/compile/auto_trait_invalid.rs
Labels: enhancement, diagnostic

#2559 [E0535] Unknown argument given to inline attribute
  gcc/rust/backend/rust-compile-base.cc
  gcc/testsuite/rust/compile/inline_2.rs
Labels: diagnostic

#2535 Add punycode encoding to v0 mangling
  gcc/rust/backend/rust-mangle.cc
  gcc/rust/lex/rust-lex.cc
  gcc/rust/resolve/rust-ast-resolve-toplevel.h
  gcc/rust/rust-session-manager.cc
  gcc/rust/util/rust-canonical-path.h
  gcc/rust/util/rust-hir-map.cc
  gcc/rust/util/rust-mapping-common.h
Labels: enhancement

#2573 Remove ```stmt_tree``` and dependency on ```cp_token_cache```
  gcc/rust/backend/rust-tree.h
Labels: cleanup

#2575 gccrs: Fix compilation of types which hold onto dangling infer vars
  gcc/rust/backend/rust-compile-type.cc
  gcc/testsuite/rust/compile/iterators1.rs
Labels: bug

#2579 Rename some structs to avoid ODR issues
  gcc/rust/backend/rust-tree.cc
  gcc/rust/backend/rust-tree.h
Labels: cleanup

#2570 Fork ```c++``` resorting methods
  gcc/rust/backend/rust-tree.cc
  gcc/rust/backend/rust-tree.h
Labels: cleanup

#2562 [E0271] Type mismatch between associated type trait.
  gcc/rust/typecheck/rust-tyty.cc
  gcc/testsuite/rust/compile/issue-1725-2.rs
Labels: diagnostic

#2574 diagnostics: Added non-const `rich_location *` function
  gcc/rust/rust-diagnostics.cc
  gcc/rust/rust-diagnostics.h
  gcc/rust/rust_error_codes.def
Labels: cleanup

#2580 Add missing ```gengtype``` related structs
  gcc/rust/backend/rust-tree.h
Labels: cleanup

#2564 [E0769] Use of struct or tuple variant in struct or struct variant
  gcc/rust/typecheck/rust-hir-type-check-pattern.cc
  gcc/testsuite/rust/compile/match4.rs
Labels: diagnostic

#2586 Handle remaining unhandled gengtype annotations
  gcc/rust/backend/rust-tree.cc
  gcc/rust/backend/rust-tree.h
  gcc/rust/config-lang.in
  gcc/rust/rust-lang.cc
Labels: cleanup
