Repository Rust-GCC/gccrs, pull requests merged in 2023-09, with the labels that each got.

#2577 Fix invalid call to ```vector::front``` in ```TypeBoundPredicate``` constructors
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/rust/typecheck/rust-tyty-bounds.cc
  gcc/rust/typecheck/rust-tyty.h
Labels: enhancement

#2589 Move type-related functions into base class ```Backend```
  gcc/rust/rust-backend.h
  gcc/rust/rust-gcc.cc
Labels: cleanup

#2590 Bump ```docker/build-push-action``` to v4
  .github/workflows/docker.yml
Labels: automation

#2569 Top level or-patterns are not allowed let binding
  gcc/rust/hir/rust-ast-lower-pattern.cc
  gcc/testsuite/rust/compile/let_alt.rs
Labels: diagnostic

#2596 Improve type checking for if expressions
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/testsuite/rust/compile/type-if.rs
Labels: bug

#2592 Move debug-related functions into base class ```Backend```
  gcc/rust/rust-backend.h
  gcc/rust/rust-gcc.cc
Labels: enhancement, cleanup

#2597 [E0603] Use of private item outside scope
  gcc/rust/checks/errors/privacy/rust-privacy-reporter.cc
  gcc/testsuite/rust/compile/privacy1.rs
  gcc/testsuite/rust/compile/privacy3.rs
  gcc/testsuite/rust/compile/privacy4.rs
  gcc/testsuite/rust/compile/privacy5.rs
Labels: diagnostic

#2599 Move variable-related methods into base class ```Backend```
  gcc/rust/rust-backend.h
  gcc/rust/rust-gcc.cc
Labels: cleanup

#2600 Move some simple expression-related methods into base class ```Backend```
  gcc/rust/rust-backend.h
  gcc/rust/rust-gcc.cc
Labels: cleanup

#2555 [E0592] method or associated functions already defined with same names
  gcc/rust/typecheck/rust-hir-inherent-impl-overlap.h
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/testsuite/rust/compile/generics7.rs
  gcc/testsuite/rust/compile/generics8.rs
  gcc/testsuite/rust/compile/issue-925.rs
Labels: diagnostic

#2601 Move function-related methods into base class ```Backend```
  gcc/rust/rust-backend.h
  gcc/rust/rust-gcc.cc
Labels: cleanup

#2602 Move statement-related methods into base class ```Backend```
  gcc/rust/rust-backend.h
  gcc/rust/rust-gcc.cc
Labels: cleanup

#2604 Iterators WORKING
  gcc/rust/backend/rust-compile-expr.cc
  gcc/testsuite/rust/execute/torture/iter1.rs
Labels: bug, enhancement

#2440 Remove ```Gcc_backend```
  gcc/rust/rust-backend.h
  gcc/rust/rust-gcc.cc
Labels: cleanup

#2571 [E0599] Failed to resovle method implementation
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/testsuite/rust/compile/cfg2.rs
  gcc/testsuite/rust/compile/issue-2139.rs
  gcc/testsuite/rust/compile/issue-2190-1.rs
  gcc/testsuite/rust/compile/method1.rs
Labels: diagnostic

#2576 Add testcase for #1260
  gcc/testsuite/rust/compile/privacy6.rs
  gcc/testsuite/rust/compile/privacy9.rs
Labels: enhancement

#2622 Remove unused complex number support
  gcc/rust/rust-backend.h
  gcc/rust/rust-gcc.cc
Labels: cleanup

#2619 Add ```assume``` intrinsic
  gcc/rust/backend/rust-compile-intrinsic.cc
  gcc/testsuite/rust/compile/assume.rs
Labels: enhancement

#2625 gccrs: trivial typo fix.
  gcc/rust/backend/rust-compile-base.cc
  gcc/rust/backend/rust-compile-extern.h
  gcc/rust/backend/rust-compile-implitem.cc
  gcc/rust/backend/rust-compile-intrinsic.cc
  gcc/rust/backend/rust-compile-item.cc
  gcc/rust/backend/rust-compile-resolve-path.cc
  gcc/rust/typecheck/rust-coercion.cc
  gcc/rust/typecheck/rust-hir-type-check-item.cc
  gcc/rust/typecheck/rust-hir-type-check-path.cc
  gcc/rust/typecheck/rust-hir-type-check-type.cc
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
Labels: cleanup

#2616 Add license text to libproc_macro rust interface
  libgrust/libproc_macro/bridge.rs
  libgrust/libproc_macro/bridge/ffistring.rs
  libgrust/libproc_macro/bridge/group.rs
  libgrust/libproc_macro/bridge/ident.rs
  libgrust/libproc_macro/bridge/literal.rs
  libgrust/libproc_macro/bridge/punct.rs
  libgrust/libproc_macro/bridge/span.rs
  libgrust/libproc_macro/bridge/token_stream.rs
  libgrust/libproc_macro/group.rs
  libgrust/libproc_macro/ident.rs
  libgrust/libproc_macro/lib.rs
  libgrust/libproc_macro/literal.rs
  libgrust/libproc_macro/punct.rs
  libgrust/libproc_macro/span.rs
  libgrust/libproc_macro/token_stream.rs
Labels: cleanup

#2626 gccrs: Minor typo fix
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-type.cc
  gcc/rust/rust-backend.h
  gcc/rust/rust-gcc.cc
  gcc/rust/typecheck/rust-tyty-call.cc
  gcc/rust/typecheck/rust-tyty.h
Labels: cleanup

#2628 gccrs: Remove HIR::ForLoopExpr
  gcc/rust/backend/rust-compile-block.h
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/checks/errors/privacy/rust-privacy-reporter.cc
  gcc/rust/checks/errors/privacy/rust-privacy-reporter.h
  gcc/rust/checks/errors/rust-const-checker.cc
  gcc/rust/checks/errors/rust-const-checker.h
  gcc/rust/checks/errors/rust-unsafe-checker.cc
  gcc/rust/checks/errors/rust-unsafe-checker.h
  gcc/rust/checks/lints/rust-lint-marklive.h
  gcc/rust/hir/rust-ast-lower.cc
  gcc/rust/hir/rust-hir-dump.cc
  gcc/rust/hir/rust-hir-dump.h
  gcc/rust/hir/tree/rust-hir-expr.h
  gcc/rust/hir/tree/rust-hir-full-decls.h
  gcc/rust/hir/tree/rust-hir-visitor.h
  gcc/rust/hir/tree/rust-hir.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.h
Labels: cleanup

#2627 [E0617] Attempt for invalid type variable in `variadic` function
  gcc/rust/typecheck/rust-tyty-call.cc
  gcc/testsuite/rust/compile/variadic.rs
Labels: diagnostic

#2629 gccrs: port over readonly_error from c-family for lvalue assignment checks
  gcc/rust/Make-lang.in
  gcc/rust/checks/errors/rust-readonly-check.cc
  gcc/rust/checks/errors/rust-readonly-check.h
  gcc/rust/resolve/rust-ast-resolve-expr.cc
  gcc/rust/resolve/rust-ast-verify-assignee.h
  gcc/rust/rust-session-manager.cc
  gcc/testsuite/rust/compile/issue-2391.rs
  gcc/testsuite/rust/compile/wrong_lhs_assignment.rs
Labels: diagnostic

#2633 Fix CanonicalPath for impl
  gcc/rust/resolve/rust-ast-resolve-item.cc
  gcc/rust/resolve/rust-ast-resolve-toplevel.h
  gcc/rust/util/rust-canonical-path.h
Labels: enhancement

#2639 Fix ICE when emitting an error during cfg strip
  gcc/rust/rust-session-manager.cc
Labels: enhancement
