Repository Rust-GCC/gccrs, pull requests merged in 2023-01, with the labels that each got.

#1716 rust: add bound parsing in parse_generic_arg.
  gcc/rust/parse/rust-parse-impl.h
  gcc/testsuite/rust/compile/bounds.rs
Labels: bug

#1709 Check const functions for mutable references
  gcc/rust/checks/errors/rust-const-checker.cc
  gcc/testsuite/rust/compile/const10.rs
Labels: enhancement

#1711 unsafe: check use of `target_feature` attribute
  gcc/rust/checks/errors/rust-unsafe-checker.cc
  gcc/rust/checks/errors/rust-unsafe-checker.h
  gcc/rust/util/rust-attributes.cc
  gcc/testsuite/rust/compile/unsafe11.rs
Labels: enhancement

#1708 Parse declarative macro (decl_macro 2.0)
  gcc/rust/ast/rust-ast-full-decls.h
  gcc/rust/ast/rust-ast-full-test.cc
  gcc/rust/ast/rust-ast.h
  gcc/rust/ast/rust-item.h
  gcc/rust/ast/rust-macro.h
  gcc/rust/lex/rust-token.h
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/parse/rust-parse.h
  gcc/testsuite/rust/compile/decl_macro1.rs
  gcc/testsuite/rust/compile/decl_macro2.rs
  gcc/testsuite/rust/compile/decl_macro3.rs
  gcc/testsuite/rust/compile/decl_macro4.rs
  gcc/testsuite/rust/compile/decl_macro5.rs
  gcc/testsuite/rust/compile/decl_macro6.rs
  gcc/testsuite/rust/compile/decl_macro7.rs
  gcc/testsuite/rust/execute/torture/decl_macro1.rs
  gcc/testsuite/rust/execute/torture/decl_macro2.rs
  gcc/testsuite/rust/execute/torture/decl_macro3.rs
  gcc/testsuite/rust/execute/torture/decl_macro4.rs
Labels: enhancement

#1724 Add support for generics associated type binding
  gcc/rust/hir/tree/rust-hir-path.h
  gcc/rust/resolve/rust-ast-resolve-type.cc
  gcc/rust/typecheck/rust-hir-path-probe.h
  gcc/rust/typecheck/rust-hir-trait-resolve.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/rust/typecheck/rust-tyty-bounds.cc
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust/compile/bounds.rs
  gcc/testsuite/rust/execute/torture/issue-1720.rs
Labels: bug

#1730 Improve type checking on let statements
  gcc/rust/typecheck/rust-hir-type-check-stmt.cc
Labels: enhancement

#1734 Add get_locus function for abstract class MetaItemInner.
  gcc/rust/ast/rust-ast.h
  gcc/rust/ast/rust-expr.h
  gcc/rust/ast/rust-macro.h
Labels: enhancement

#1733 diagnostics: Add underline for tokens in diagnostics.
  gcc/rust/lex/rust-lex.cc
  gcc/testsuite/rust/compile/diagnostic_underline.rs
Labels: enhancement

#1736 Change how CompileVarDecl outputs Bvariable's
  gcc/rust/backend/rust-compile-base.cc
  gcc/rust/backend/rust-compile-var-decl.h
Labels: enhancement

#1746 Add CL checking automation to gcc-patch-dev
  .github/workflows/commit-format.yml
Labels: upstream

#1751 README.md: Added experimental flag & updated gccrs path
  README.md
Labels: enhancement, documentation

#1760 Support GroupedPattern during name resolution
  gcc/rust/resolve/rust-ast-resolve-pattern.h
Labels: enhancement

#1763 Do not crash on empty macros expand. Fixes #1712
  gcc/rust/expand/rust-macro-expand.cc
  gcc/testsuite/rust/compile/macro45.rs
Labels: bug

#1769 Add HIR lowering for GroupedPattern
  gcc/rust/hir/rust-ast-lower-pattern.cc
  gcc/rust/hir/rust-ast-lower-pattern.h
Labels: enhancement

#1771 Add type resolution for grouped patterns
  gcc/rust/hir/tree/rust-hir-pattern.h
  gcc/rust/typecheck/rust-hir-type-check-pattern.cc
Labels: enhancement

#1772 Added missing GroupedPattern visitors for code generation
  gcc/rust/backend/rust-compile-pattern.cc
  gcc/rust/backend/rust-compile-pattern.h
Labels: enhancement

#1759 Revert 10-second timeout for each test
  gcc/testsuite/lib/rust.exp
Labels: testsuite, cleanup

#1777 Rename file rust-ast-full-test.cc to rust-ast.cc
  gcc/rust/Make-lang.in
  gcc/rust/ast/rust-ast.cc
Labels: cleanup

#1735 macro: Allow builtin `MacroInvocation`s within the AST
  gcc/rust/ast/rust-macro.h
  gcc/rust/expand/rust-attribute-visitor.cc
  gcc/rust/parse/rust-parse-impl.h
Labels: upstream

#1776 fixed compiler error message on wildcard pattern within expression
  gcc/rust/parse/rust-parse-impl.h
  gcc/testsuite/rust/compile/issue-867.rs
Labels: enhancement

#1775 Create and use CompilePatternLet visitor for compiling let statments
  gcc/rust/backend/rust-compile-pattern.cc
  gcc/rust/backend/rust-compile-pattern.h
  gcc/rust/backend/rust-compile-stmt.cc
Labels: enhancement

#1788 ci: Add commit format checker
  .github/workflows/commit-format.yml
Labels: CI, upstream
