Repository Rust-GCC/gccrs, pull requests merged in 2024-12, with the labels that each got.

#3280 gccrs: Remove bad assertion in name resolution
  gcc/rust/resolve/rust-ast-resolve-item.cc
  gcc/testsuite/rust/compile/issue-2423.rs
  gcc/testsuite/rust/compile/nr2/exclude
Labels: bug

#3281 gccrs: constant evaluation like these are coercion sites
  gcc/rust/backend/rust-compile-base.cc
  gcc/rust/backend/rust-compile-base.h
  gcc/rust/backend/rust-compile-implitem.cc
  gcc/rust/backend/rust-compile-item.cc
  gcc/testsuite/rust/compile/issue-1525.rs
Labels: bug, typechecking, codegen

#3279 gccrs: add checks for division by zero and left shift overflow
  gcc/rust/backend/rust-constexpr.cc
  gcc/rust/rust-gcc.cc
  gcc/testsuite/rust/compile/issue-2394.rs
Labels: bug, diagnostic

#3282 gccrs: add test case to show issue is fixed
  gcc/testsuite/rust/compile/issue-266.rs
  gcc/testsuite/rust/compile/nr2/exclude
Labels: bug

#3283 gccrs: fix crash in hir dump
  gcc/rust/hir/rust-hir-dump.cc
Labels: bug

#3303 gccrs: implement the TuplePattern and use it for function patterns
  gcc/rust/backend/rust-compile-fnparam.cc
  gcc/rust/backend/rust-compile-fnparam.h
  gcc/rust/backend/rust-compile-pattern.cc
  gcc/rust/backend/rust-compile-pattern.h
  gcc/testsuite/rust/compile/issue-2847.rs
Labels: bug

#3298 gccrs: Made changes to AST::TraitImpl constructor for TypePath
  gcc/rust/ast/rust-item.h
Labels: cleanup, AST

#3312 gccrs: disable macos github workflow
  .github/workflows/ccpp.yml
Labels: automation

#3321 allow ptr to int and int to ptr type casting
  gcc/rust/typecheck/rust-casts.cc
  gcc/testsuite/rust/compile/ptr_int_cast.rs
Labels: bug, typechecking

#3317 typecheck-path: Fix typo (reciever -> receiver)
  gcc/rust/typecheck/rust-hir-path-probe.cc
  gcc/rust/typecheck/rust-hir-path-probe.h
  gcc/rust/typecheck/rust-hir-type-check-path.cc
Labels: cleanup
