Repository Rust-GCC/gccrs, pull requests merged in 2024-11, with the labels that each got.

#3234 gccrs: add test case to show method resolution is working
  gcc/testsuite/rust/compile/issue-3033.rs
  gcc/testsuite/rust/compile/nr2/exclude
Labels: typechecking

#3232 Make `TyTy::TupleType::get_unit_type` cache its return value
  gcc/rust/resolve/rust-late-name-resolver-2.0.cc
  gcc/rust/resolve/rust-name-resolver.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/rust/typecheck/rust-hir-type-check-implitem.cc
  gcc/rust/typecheck/rust-hir-type-check-item.cc
  gcc/rust/typecheck/rust-hir-type-check-stmt.cc
  gcc/rust/typecheck/rust-hir-type-check-type.cc
  gcc/rust/typecheck/rust-hir-type-check.cc
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
Labels: cleanup, HIR, typechecking

#3235 gccrs: fix bad type inferencing on path's
  gcc/rust/typecheck/rust-hir-type-check-path.cc
  gcc/testsuite/rust/compile/issue-3009.rs
  gcc/testsuite/rust/compile/nr2/exclude
Labels: bug, typechecking

#3236 Remove usage of `Resolver::get_builtin_types`
  gcc/rust/backend/rust-compile-context.cc
  gcc/rust/typecheck/rust-hir-type-check.h
  gcc/rust/typecheck/rust-typecheck-context.cc
Labels: cleanup

#3237 gccrs: fix bad type inference on local patterns
  gcc/rust/typecheck/rust-hir-type-check-path.cc
  gcc/testsuite/rust/compile/issue-2323.rs
  gcc/testsuite/rust/compile/nr2/exclude
Labels: bug, typechecking

#3238 Improve handling of implicit `Self` parameter in AST
  gcc/rust/ast/rust-item.h
  gcc/rust/hir/rust-ast-lower-item.cc
  gcc/rust/resolve/rust-ast-resolve-item.cc
  gcc/rust/resolve/rust-early-name-resolver.cc
  gcc/rust/resolve/rust-toplevel-name-resolver-2.0.cc
  gcc/testsuite/rust/compile/nr2/exclude
  gcc/testsuite/rust/link/generic_function_0.rs
  gcc/testsuite/rust/link/trait_import_0.rs
  gcc/testsuite/rust/link/trait_import_1.rs
Labels: bug

#3243 gccrs: add test case to show issue is fixed
  gcc/testsuite/rust/compile/issue-1773.rs
  gcc/testsuite/rust/compile/issue-3242.rs
  gcc/testsuite/rust/compile/nr2/exclude
Labels: bug

#3250 gccrs: Fix bad handling for recursive type query
  gcc/rust/typecheck/rust-hir-type-check-item.cc
  gcc/rust/typecheck/rust-hir-type-check-type.cc
  gcc/rust/typecheck/rust-tyty-subst.cc
  gcc/testsuite/rust/compile/issue-2905-1.rs
  gcc/testsuite/rust/compile/issue-2905-2.rs
  gcc/testsuite/rust/compile/nr2/exclude
Labels: bug, typechecking

#3255 Add a new CI step to detect raw issue references in commit messages
  .github/workflows/commit-format.yml
Labels: automation

#3267 gccrs: fix crash in hir dump with missing guards
  gcc/rust/hir/rust-hir-dump.cc
Labels: bug, HIR

#3269 gccrs: improve handling of Self Type paths
  gcc/rust/typecheck/rust-hir-trait-resolve.cc
  gcc/rust/typecheck/rust-hir-type-check-implitem.cc
  gcc/rust/typecheck/rust-hir-type-check-path.cc
  gcc/rust/typecheck/rust-hir-type-check-type.cc
  gcc/rust/typecheck/rust-hir-type-check-type.h
  gcc/rust/typecheck/rust-hir-type-check.h
  gcc/rust/typecheck/rust-typecheck-context.cc
  gcc/testsuite/rust/compile/issue-2907.rs
  gcc/testsuite/rust/compile/nr2/exclude
Labels: bug, HIR, typechecking

#3276 hir: Remove duplicate function in TraitItemFunc
  gcc/rust/backend/rust-compile-implitem.cc
  gcc/rust/checks/errors/rust-const-checker.cc
  gcc/rust/checks/errors/rust-hir-pattern-analysis.cc
  gcc/rust/checks/errors/rust-unsafe-checker.cc
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/typecheck/rust-hir-trait-resolve.cc
Labels: cleanup
