Repository Rust-GCC/gccrs, pull requests merged in 2025-07, with the labels that each got.

#3891 gccrs: Fix ice with invalid borrow expression
  gcc/rust/ast/rust-ast-collector.cc
  gcc/rust/ast/rust-expr.h
  gcc/testsuite/rust/compile/issue-3874.rs
Labels: bug, AST

#3900 gccrs: Fix cast rules logic to try simple casts then fall back to coercions
  gcc/rust/typecheck/rust-casts.cc
  gcc/rust/typecheck/rust-casts.h
  gcc/testsuite/rust/compile/issue-2680.rs
Labels: typechecking

#3909 gccrs: Add test case to show we emit better errors now
  gcc/testsuite/rust/compile/issue-3144.rs
Labels: diagnostic

#3986 gccrs: Add test case to show issue is fixed
  gcc/testsuite/rust/compile/issue-3524.rs
Labels: testsuite

#3987 gccrs: Fix ICE with duplicate root item main function
  gcc/rust/backend/rust-compile-base.cc
  gcc/testsuite/rust/compile/issue-3978.rs
Labels: bug, codegen

#3985 gccrs: Add initial support for deffered operator overload resolution
  gcc/rust/hir/tree/rust-hir-expr.cc
  gcc/rust/hir/tree/rust-hir-expr.h
  gcc/rust/hir/tree/rust-hir-path.h
  gcc/rust/typecheck/rust-hir-trait-reference.cc
  gcc/rust/typecheck/rust-hir-trait-reference.h
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/typecheck/rust-hir-type-check.h
  gcc/rust/typecheck/rust-typecheck-context.cc
  gcc/testsuite/rust/compile/issue-3916.rs
Labels: typechecking

#3988 gccrs: return error node when this fails during constexpr case
  gcc/rust/backend/rust-compile-resolve-path.cc
Labels: typechecking

#3992 gccrs: fix bad monomophization of generic paths - GOAL TEST CASE SIP HASHER WORKS!
  gcc/rust/backend/rust-compile-resolve-path.cc
  gcc/testsuite/rust/compile/issue-3915.rs
  gcc/testsuite/rust/execute/torture/sip-hasher.rs
Labels: typechecking

#4011 nr1.0: Remove `rust/typecheck` support
  gcc/rust/typecheck/rust-hir-trait-resolve.cc
  gcc/rust/typecheck/rust-hir-type-check-base.cc
  gcc/rust/typecheck/rust-hir-type-check-base.h
  gcc/rust/typecheck/rust-hir-type-check-enumitem.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/rust/typecheck/rust-hir-type-check-implitem.cc
  gcc/rust/typecheck/rust-hir-type-check-item.cc
  gcc/rust/typecheck/rust-hir-type-check-path.cc
  gcc/rust/typecheck/rust-hir-type-check-pattern.cc
  gcc/rust/typecheck/rust-hir-type-check-type.cc
  gcc/rust/typecheck/rust-hir-type-check.cc
  gcc/rust/typecheck/rust-type-util.cc
Labels: cleanup, typechecking

#4026 gccrs: Fix ICE during const eval of const capacity
  gcc/rust/backend/rust-compile-expr.cc
  gcc/testsuite/rust/compile/issue-3960.rs
Labels: bug, typechecking, codegen
