Repository Rust-GCC/gccrs, pull requests merged in 2025-04, with the labels that each got.

#3675 gccrs: Fix ICE when resolving lifetimes without name
  gcc/rust/typecheck/rust-hir-type-check-base.cc
  gcc/testsuite/rust/compile/issue-3657.rs
Labels: bug, typechecking

#3676 gccrs: Fix ICE when doing shift checks on const decl
  gcc/rust/rust-gcc.cc
  gcc/testsuite/rust/compile/issue-3665.rs
Labels: bug, codegen

#3687 gccrs: Fix ICE on invalid match arms
  gcc/rust/typecheck/rust-hir-type-check-pattern.cc
  gcc/testsuite/rust/compile/issue-3656.rs
Labels: bug, typechecking

#3688 gccrs: Fix ICE on raw reference
  gcc/rust/backend/rust-compile-base.cc
  gcc/rust/backend/rust-compile-base.h
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-extern.h
  gcc/rust/backend/rust-compile-resolve-path.cc
  gcc/rust/hir/rust-ast-lower-expr.cc
  gcc/rust/hir/tree/rust-hir-expr.cc
  gcc/rust/hir/tree/rust-hir-expr.h
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/testsuite/rust/compile/issue-3667.rs
Labels: bug, typechecking, codegen

#3684 gccrs: Fix ICE when hitting invalid types for generics
  gcc/rust/resolve/rust-ast-resolve-type.cc
  gcc/rust/typecheck/rust-substitution-mapper.cc
  gcc/rust/typecheck/rust-substitution-mapper.h
  gcc/testsuite/rust/compile/issue-3643.rs
  gcc/testsuite/rust/compile/issue-3646.rs
  gcc/testsuite/rust/compile/issue-3654.rs
  gcc/testsuite/rust/compile/issue-3663.rs
  gcc/testsuite/rust/compile/issue-3671.rs
  gcc/testsuite/rust/compile/nr2/exclude
Labels: bug, name resolution, typechecking

#3691 nr2.0: Remove duplicate self visit
  gcc/rust/ast/rust-ast-visitor.cc
  gcc/testsuite/rust/compile/nr2/exclude
Labels: name resolution

#3513 chore: refactoring rust_error_at "redefined multiple times"
  gcc/rust/resolve/rust-ast-resolve-base.h
  gcc/rust/resolve/rust-ast-resolve-implitem.h
  gcc/rust/resolve/rust-ast-resolve-stmt.cc
  gcc/rust/resolve/rust-ast-resolve-stmt.h
  gcc/rust/resolve/rust-ast-resolve-toplevel.h
Labels: cleanup

#3694 gccrs: Fix segv in unsafe chcker
  gcc/rust/checks/errors/rust-unsafe-checker.cc
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/typecheck/rust-hir-trait-resolve.cc
  gcc/testsuite/rust/compile/issue-3612.rs
Labels: bug, typechecking

#3743 gccrs: Fix crash in hir dump as labels are optional
  gcc/rust/hir/rust-hir-dump.cc
Labels: bug, HIR

#3744 gccrs: Fix ICE when checking shift's which are behind array refs
  gcc/rust/rust-gcc.cc
  gcc/testsuite/rust/compile/issue-3664.rs
Labels: bug

#3745 gccrs: Add check for placeholder (infer) type in return position
  gcc/rust/typecheck/rust-hir-type-check-item.cc
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust/compile/issue-402.rs
Labels: diagnostic, HIR, typechecking

#3750 gccrs: Add test case to show issue is fixed
  gcc/testsuite/rust/compile/issue-3711.rs
Labels: bug, typechecking

#3752 gccrs: Add test case to show ICE is fixed
  gcc/testsuite/rust/compile/issue-3662.rs
Labels: bug

#3753 nr2.0: Handle `StructPatternFieldIdent`
  gcc/rust/resolve/rust-late-name-resolver-2.0.cc
  gcc/rust/resolve/rust-late-name-resolver-2.0.h
  gcc/testsuite/rust/compile/nr2/exclude
Labels: AST, name resolution

#3748 gccrs: Fix ICE in struct expressions
  gcc/rust/typecheck/rust-hir-type-check-struct-field.h
  gcc/rust/typecheck/rust-hir-type-check-struct.cc
  gcc/testsuite/rust/compile/issue-3628.rs
  gcc/testsuite/rust/compile/macros/mbe/macro-issue2983_2984.rs
  gcc/testsuite/rust/compile/struct_init1.rs
Labels: bug

#3756 nr2.0: Remove unnecessary copy of `Node`
  gcc/rust/resolve/rust-forever-stack.hxx
Labels: cleanup, name resolution

#3747 gccrs: Fix ICE when handling case of unknown field in HIR::FieldAccess
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/testsuite/rust/compile/issue-3581-1.rs
  gcc/testsuite/rust/compile/issue-3581-2.rs
  gcc/testsuite/rust/compile/nonexistent-field.rs
Labels: HIR, typechecking

#3758 gccrs: Add test case to show ice is fixed
  gcc/testsuite/rust/compile/issue-3652.rs
  gcc/testsuite/rust/compile/nr2/exclude
Labels: bug, name resolution

#3749 gccrs: Fix ICE with empty generic arguments
  gcc/rust/ast/rust-ast-visitor.cc
  gcc/rust/expand/rust-expand-visitor.cc
  gcc/testsuite/rust/compile/issue-3649.rs
  gcc/testsuite/rust/compile/nr2/exclude
Labels: AST

#3751 gccrs: prealloc the initilizer vector
  gcc/rust/backend/rust-compile-expr.cc
Labels: codegen

#3763 NR2: Change error message to match expected test output
  gcc/rust/resolve/rust-late-name-resolver-2.0.cc
  gcc/testsuite/rust/compile/nr2/exclude
Labels: name resolution

#3765 Change expected error output to match nr2
  gcc/testsuite/rust/compile/nr2/exclude
  gcc/testsuite/rust/compile/use_1.rs
Labels: name resolution

#3766 Completely duplicate path node
  gcc/rust/expand/rust-derive-clone.cc
  gcc/testsuite/rust/compile/nr2/exclude
Labels: name resolution
