Repository Rust-GCC/gccrs, pull requests merged in 2025-06, with the labels that each got.

#3827 gccrs: Improve HIR dumps for patterns
  gcc/rust/hir/rust-hir-dump.cc
Labels: cleanup, HIR

#3830 Adjust external crate lowering and type checking
  gcc/rust/hir/rust-ast-lower-item.cc
  gcc/rust/hir/rust-ast-lower-item.h
  gcc/rust/rust-session-manager.cc
  gcc/rust/typecheck/rust-hir-type-check-item.cc
  gcc/rust/typecheck/rust-hir-type-check-item.h
Labels: HIR, typechecking

#3843 gccrs: Ensure we look at the bounds behind a reference
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.h
Labels: typechecking

#3845 gccrs: Fix cyclical projection to placeholder
  gcc/rust/typecheck/rust-hir-trait-resolve.cc
Labels: typechecking

#3847 gccrs: Refactor marker builtin trait assembly
  gcc/rust/typecheck/rust-hir-type-bounds.h
  gcc/rust/typecheck/rust-tyty-bounds.cc
Labels: typechecking

#3848 gccrs: Cleanup and refactor method resolution
  gcc/rust/typecheck/rust-hir-dot-operator.cc
  gcc/rust/typecheck/rust-hir-dot-operator.h
Labels: typechecking

#3846 gccrs: Fix bug with bad type bindings not looking at super traits
  gcc/rust/typecheck/rust-tyty-bounds.cc
  gcc/rust/typecheck/rust-tyty.h
Labels: typechecking

#3849 gccrs: Add unify rules for fnptr and closures
  gcc/rust/typecheck/rust-unify.cc
Labels: typechecking

#3853 gccrs: Fix bug with non compiled const decl
  gcc/rust/backend/rust-compile-resolve-path.cc
  gcc/testsuite/rust/compile/issue-3525.rs
Labels: bug, codegen

#3839 nr2.0: Adjust resolution of external crates
  gcc/rust/resolve/rust-default-resolver.cc
  gcc/rust/resolve/rust-default-resolver.h
  gcc/rust/resolve/rust-toplevel-name-resolver-2.0.cc
  gcc/rust/resolve/rust-toplevel-name-resolver-2.0.h
  gcc/rust/rust-session-manager.cc
Labels: bug, name resolution

#3859 gccrs: Implement type checking for ItemType::RANGED in TuplePattern
  gcc/rust/typecheck/rust-hir-type-check-pattern.cc
Labels: HIR, typechecking

#3826 nr2.0: Adjust resolution of modules
  gcc/rust/resolve/rust-forever-stack.hxx
  gcc/rust/resolve/rust-toplevel-name-resolver-2.0.cc
  gcc/testsuite/rust/compile/nr2/exclude
Labels: bug, name resolution
