Repository Rust-GCC/gccrs, pull requests merged in 2025-09, with the labels that each got.

#4127 gccrs: remove docker github workflow
  .github/workflows/docker.yml
Labels: CI

#4132 gccrs: track abi and unsafety on fnptrs for proper type checking
  gcc/rust/hir/tree/rust-hir-item.h
  gcc/rust/typecheck/rust-hir-type-check-type.cc
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/rust/typecheck/rust-unify.cc
Labels: typechecking

#4172 gccrs: Fix ICE handling division by zero in const eval
  gcc/rust/backend/rust-constexpr.cc
  gcc/testsuite/rust/compile/issue-2394.rs
  gcc/testsuite/rust/compile/issue-4146.rs
Labels: constexpr

#4177 gccrs: Fix ICE for invalid const capacity expression handling
  gcc/rust/typecheck/rust-hir-type-check-type.cc
  gcc/testsuite/rust/compile/issue-4168.rs
Labels: bug, typechecking

#4135 Implement `TokenCollector::visit(AST::FormatArgs&)`
  gcc/rust/ast/rust-ast-collector.cc
  gcc/rust/ast/rust-builtin-ast-nodes.h
Labels: bug

#4179 gccrs: fnptr types can hold onto generic params so it needs to handle substs
  gcc/rust/typecheck/rust-substitution-mapper.cc
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust/compile/issue-4090-1.rs
  gcc/testsuite/rust/compile/issue-4090-2.rs
Labels: bug, typechecking

#4180 gccrs: Remove old hack from resolve operator overload
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
Labels: cleanup, typechecking

#4182 gccrs: Add error diag for self params on plain functions
  gcc/rust/hir/rust-ast-lower-item.cc
  gcc/testsuite/rust/compile/issue-3592.rs
Labels: bug

#4191 ci: handle empty commit list
  .github/workflows/send-emails.yml
Labels: CI
