Repository Rust-GCC/gccrs, pull requests merged in 2025-01, with the labels that each got.

#3346 gccrs: fix ICE during HIR dump
  gcc/rust/hir/rust-hir-dump.cc
Labels: bug

#3356 gccrs: fix ICE in borrows to invalid expressions
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/rust/typecheck/rust-tyty-call.cc
  gcc/testsuite/rust/compile/issue-3046.rs
  gcc/testsuite/rust/compile/issue-3140.rs
  gcc/testsuite/rust/compile/nr2/exclude
Labels: bug, typechecking

#3347 gccrs: add support for lang_item eq and PartialEq trait
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-expr.h
  gcc/rust/hir/tree/rust-hir-expr.cc
  gcc/rust/hir/tree/rust-hir-expr.h
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.h
  gcc/rust/util/rust-lang-item.cc
  gcc/rust/util/rust-lang-item.h
  gcc/rust/util/rust-operators.h
  gcc/testsuite/rust/compile/cmp1.rs
  gcc/testsuite/rust/compile/nr2/exclude
Labels: bug, HIR, typechecking, codegen

#3358 gccrs: fix ICE with hir dump on closure
  gcc/rust/hir/rust-hir-dump.cc
Labels: bug

#3357 gccrs: cleanup our enum type layout to be closer to rustc
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-pattern.cc
  gcc/rust/backend/rust-compile-resolve-path.cc
  gcc/rust/backend/rust-compile-type.cc
  gcc/rust/rust-gcc.cc
Labels: Rust Integrations, codegen

#3319 Allow float type to be casted as integer type
  gcc/rust/typecheck/rust-casts.cc
  gcc/testsuite/rust/compile/cast_float_as_integer.rs
Labels: bug, typechecking

#3360 gccrs: match arms are a LUB
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/rust/typecheck/rust-unify.cc
Labels: cleanup, typechecking

#3311 gccrs: improve mutability checks
  gcc/rust/checks/errors/rust-readonly-check.cc
  gcc/testsuite/rust/compile/mutability_checks1.rs
  gcc/testsuite/rust/execute/torture/builtin_macro_include_bytes.rs
Labels: bug, diagnostic

#3251 Add `ForeverStackStore`
  gcc/rust/Make-lang.in
  gcc/rust/resolve/rust-forever-stack.cc
  gcc/rust/resolve/rust-forever-stack.h
Labels: name resolution

#3364 nr2.0: Early resolve pending eager macro invocations
  gcc/rust/resolve/rust-early-name-resolver-2.0.cc
  gcc/testsuite/rust/compile/nr2/exclude
Labels: bug, AST, name resolution

#3374 Add receiver lang item
  gcc/rust/util/rust-lang-item.cc
  gcc/rust/util/rust-lang-item.h
  gcc/testsuite/rust/compile/issue-2954.rs
Labels: HIR, typechecking

#3369 derive(Copy): Improve bounds when deriving Copy
  gcc/rust/expand/rust-derive-copy.cc
Labels: AST, expansion

#3266 Fix rust breakage with nr2
  gcc/rust/Make-lang.in
  gcc/rust/resolve/rust-ast-resolve-expr.cc
  gcc/rust/resolve/rust-ice-finalizer.cc
  gcc/rust/resolve/rust-ice-finalizer.h
  gcc/rust/resolve/rust-late-name-resolver-2.0.cc
  gcc/rust/resolve/rust-late-name-resolver-2.0.h
  gcc/testsuite/rust/compile/nr2/exclude
Labels: Rust Integrations, name resolution

#3375 lang-items: Add Result and Try lang items
  gcc/rust/util/rust-lang-item.cc
  gcc/rust/util/rust-lang-item.h
  gcc/testsuite/rust/compile/try-trait.rs
Labels: Rust Integrations, HIR

#3379 backend: Allow anything as a match scrutinee
  gcc/rust/backend/rust-compile-expr.cc
Labels: bug

#3146 Infer crate name after file opening
  gcc/rust/rust-session-manager.cc
  gcc/rust/rust-session-manager.h
Labels: waiting DCO

#3380 gccrs: catch missing guard for optional result
  gcc/rust/backend/rust-compile-resolve-path.cc
  gcc/testsuite/rust/compile/nr2/exclude
Labels: bug

#3383 gccrs: add new -frust-overflow-checks to control overflow checks
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/lang.opt
Labels: Rust Integrations, codegen

#3376 gccrs: add support for ref literal patterns
  gcc/rust/backend/rust-compile-pattern.cc
  gcc/rust/typecheck/rust-hir-type-check-pattern.cc
  gcc/testsuite/rust/compile/issue-3174.rs
  gcc/testsuite/rust/compile/nr2/exclude
Labels: bug, typechecking, codegen
