Repository Rust-GCC/gccrs, pull requests merged in 2025-02, with the labels that each got.

#3406 Fix an issue with `ForeverStack::dfs_rib`
  gcc/rust/resolve/rust-forever-stack.hxx
Labels: bug, name resolution

#3408 nr2.0: Remove accidental copies of resolver
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-item.cc
  gcc/rust/backend/rust-compile-resolve-path.cc
  gcc/rust/checks/lints/rust-lint-marklive.cc
  gcc/rust/typecheck/rust-hir-type-check-enumitem.cc
  gcc/rust/typecheck/rust-hir-type-check-implitem.cc
  gcc/rust/typecheck/rust-hir-type-check-item.cc
  gcc/rust/typecheck/rust-hir-type-check-path.cc
  gcc/rust/typecheck/rust-hir-type-check-type.cc
Labels: bug, name resolution

#3277 Fix bug in type resolution of paths
  gcc/rust/resolve/rust-early-name-resolver-2.0.cc
  gcc/rust/resolve/rust-early-name-resolver-2.0.h
  gcc/rust/resolve/rust-forever-stack.h
  gcc/rust/resolve/rust-forever-stack.hxx
  gcc/rust/resolve/rust-late-name-resolver-2.0.cc
  gcc/rust/resolve/rust-name-resolution-context.h
  gcc/rust/typecheck/rust-hir-type-check-path.cc
  gcc/rust/typecheck/rust-hir-type-check-type.cc
  gcc/testsuite/rust/compile/nr2/exclude
Labels: bug, AST, name resolution

#3409 gccrs: Fix ICE when fn_once and fn_once_output lang item is not defined
  gcc/rust/typecheck/rust-tyty.cc
Labels: bug, HIR

#3410 gccrs: Fix ICE during path probe
  gcc/rust/typecheck/rust-hir-path-probe.cc
Labels: bug

#3411 gccrs: coercion sites allow for type inference as well.
  gcc/rust/typecheck/rust-type-util.cc
  gcc/testsuite/rust/compile/reference1.rs
Labels: bug

#3412 gccrs: Fix crash in privay reporter for placeholder types
  gcc/rust/checks/errors/privacy/rust-privacy-reporter.cc
Labels: bug

#3414 gccrs: Fix compilation of trait-items which map to impl items
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/backend/rust-compile-item.cc
  gcc/rust/backend/rust-compile-resolve-path.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/rust/typecheck/rust-hir-type-check-path.cc
  gcc/rust/typecheck/rust-hir-type-check-type.cc
  gcc/rust/typecheck/rust-hir-type-check.h
  gcc/rust/typecheck/rust-typecheck-context.cc
  gcc/testsuite/rust/execute/torture/issue-3381.rs
Labels: bug, HIR, typechecking

#3417 gccrs: Add test case to show issue is fixed
  gcc/testsuite/rust/compile/issue-3402-1.rs
  gcc/testsuite/rust/compile/issue-3402-2.rs
  gcc/testsuite/rust/compile/nr2/exclude
Labels: bug

#3220 Resolve instances of `TypePath` more accurately
  gcc/rust/Make-lang.in
  gcc/rust/resolve/rust-forever-stack.hxx
  gcc/rust/resolve/rust-late-name-resolver-2.0.cc
  gcc/rust/resolve/rust-name-resolution-context.h
  gcc/rust/util/rust-unwrap-segment.cc
  gcc/rust/util/rust-unwrap-segment.h
  gcc/testsuite/rust/compile/nr2/exclude
Labels: name resolution

#3421 gccrs: remove bad type checking diagnostic
  gcc/rust/typecheck/rust-tyty-subst.cc
  gcc/testsuite/rust/compile/issue-3403.rs
  gcc/testsuite/rust/compile/nr2/exclude
Labels: bug, typechecking

#3423 Get rid of duplicate interface #3396
  gcc/rust/typecheck/rust-autoderef.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/rust/typecheck/rust-hir-type-check-pattern.cc
  gcc/rust/typecheck/rust-hir-type-check.h
  gcc/rust/typecheck/rust-typecheck-context.cc
Labels: cleanup

#3425 gccrs: add discriminant value intrinsic
  gcc/rust/backend/rust-compile-intrinsic.cc
  gcc/rust/typecheck/rust-hir-trait-resolve.cc
  gcc/rust/typecheck/rust-hir-type-check-base.cc
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/rust/typecheck/rust-hir-type-check-item.cc
  gcc/rust/typecheck/rust-hir-type-check-type.cc
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/rust/util/rust-lang-item.cc
  gcc/rust/util/rust-lang-item.h
  gcc/testsuite/rust/execute/torture/enum_intrinsics1.rs
Labels: bug, HIR, typechecking, codegen

#3426 gccrs: add variant_count intrinsic
  gcc/rust/backend/rust-compile-intrinsic.cc
  gcc/testsuite/rust/execute/torture/enum_intrinsics2.rs
Labels: bug, codegen

#3427 gccrs: enum type layout needs to respect the enum repr type
  gcc/rust/backend/rust-compile-type.cc
  gcc/rust/backend/rust-compile-type.h
Labels: codegen

#3435 gccrs: fix name resolution for generics where type param is declared later
  gcc/rust/resolve/rust-ast-resolve-item.cc
  gcc/rust/resolve/rust-ast-resolve-stmt.h
  gcc/rust/resolve/rust-ast-resolve-type.h
Labels: AST, name resolution

#3436 gccrs: self paths are patterns but we dont have mappings for it
  gcc/rust/hir/rust-ast-lower-base.cc
  gcc/rust/typecheck/rust-hir-type-check-path.cc
  gcc/testsuite/rust/compile/issue-3022.rs
Labels: bug, typechecking

#3439 gccrs: improve error diagnostic for bad type-resolution in CallExpr
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/testsuite/rust/compile/generics4.rs
  gcc/testsuite/rust/compile/generics6.rs
  gcc/testsuite/rust/compile/issue-2035.rs
  gcc/testsuite/rust/compile/type-bindings1.rs
  gcc/testsuite/rust/compile/unconstrained_type_param.rs
Labels: diagnostic

#3440 gccrs: Add name resolution and HIR lowering for ImplTraitType's
  gcc/rust/checks/errors/borrowck/rust-bir-builder-struct.h
  gcc/rust/checks/errors/borrowck/rust-function-collector.h
  gcc/rust/checks/errors/rust-const-checker.cc
  gcc/rust/checks/errors/rust-const-checker.h
  gcc/rust/checks/errors/rust-hir-pattern-analysis.cc
  gcc/rust/checks/errors/rust-hir-pattern-analysis.h
  gcc/rust/checks/errors/rust-unsafe-checker.cc
  gcc/rust/checks/errors/rust-unsafe-checker.h
  gcc/rust/hir/rust-ast-lower-type.cc
  gcc/rust/hir/rust-ast-lower-type.h
  gcc/rust/hir/rust-hir-dump.cc
  gcc/rust/hir/rust-hir-dump.h
  gcc/rust/hir/tree/rust-hir-full-decls.h
  gcc/rust/hir/tree/rust-hir-type.h
  gcc/rust/hir/tree/rust-hir-visitor.h
  gcc/rust/hir/tree/rust-hir.cc
  gcc/rust/resolve/rust-ast-resolve-type.cc
  gcc/rust/resolve/rust-ast-resolve-type.h
  gcc/rust/typecheck/rust-hir-type-check-type.h
Labels: HIR, AST, name resolution

#3441 gccrs: initial setup for new OpaqueType to represent Impl types
  gcc/rust/backend/rust-compile-type.cc
  gcc/rust/backend/rust-compile-type.h
  gcc/rust/checks/errors/borrowck/rust-bir-fact-collector.h
  gcc/rust/checks/errors/borrowck/rust-bir-place.h
  gcc/rust/checks/errors/privacy/rust-privacy-reporter.cc
  gcc/rust/typecheck/rust-hir-type-check-type.cc
  gcc/rust/typecheck/rust-hir-type-check-type.h
  gcc/rust/typecheck/rust-substitution-mapper.cc
  gcc/rust/typecheck/rust-substitution-mapper.h
  gcc/rust/typecheck/rust-tyty-bounds.cc
  gcc/rust/typecheck/rust-tyty-call.h
  gcc/rust/typecheck/rust-tyty-cmp.h
  gcc/rust/typecheck/rust-tyty-variance-analysis-private.h
  gcc/rust/typecheck/rust-tyty-visitor.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/rust/typecheck/rust-unify.cc
  gcc/rust/typecheck/rust-unify.h
Labels: HIR, typechecking

#3416 nr2.0: Resolve paths which start with Self
  gcc/rust/resolve/rust-forever-stack.hxx
  gcc/rust/resolve/rust-late-name-resolver-2.0.cc
  gcc/testsuite/rust/compile/nr2/exclude
Labels: name resolution

#3306 Add type check on if-expr
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/testsuite/rust/compile/if-without-else.rs
  gcc/testsuite/rust/compile/implicit_returns_err3.rs
  gcc/testsuite/rust/compile/torture/if.rs
Labels: typechecking

#3442 Add comments to `resolve_segments`
  gcc/rust/resolve/rust-forever-stack.hxx
Labels: cleanup

#3443 nr2.0: Fix issue with external crates
  gcc/rust/resolve/rust-toplevel-name-resolver-2.0.cc
  gcc/testsuite/rust/compile/nr2/exclude
Labels: bug

#3418 nr2.0: Run `DefaultResolver::visit` on `PathInExpression`
  gcc/rust/resolve/rust-late-name-resolver-2.0.cc
  gcc/testsuite/rust/compile/nr2/exclude
Labels: bug, name resolution

#3446 Remove `PathInExpression::get_pattern_node_id`
  gcc/rust/ast/rust-path.h
Labels: cleanup, AST

#3445 Fix expansion of macros inside modules
  gcc/rust/expand/rust-expand-visitor.cc
  gcc/rust/expand/rust-expand-visitor.h
  gcc/testsuite/rust/compile/macros/mbe/macro-expand-module.rs
Labels: bug, expansion

#3447 Remove some member functions from `SingleASTNode`
  gcc/rust/ast/rust-ast.h
  gcc/rust/expand/rust-expand-visitor.cc
Labels: cleanup

#3316 hir-dump: Fix more segfaults in the HIR dump
  gcc/rust/hir/rust-hir-dump.cc
  gcc/rust/hir/tree/rust-hir-path.h
Labels: HIR
