Repository Rust-GCC/gccrs, pull requests merged in 2025-03, with the labels that each got.

#3501 gccrs: check for recursion trait cycle with bounds checks
  gcc/rust/typecheck/rust-hir-trait-resolve.cc
  gcc/rust/typecheck/rust-hir-trait-resolve.h
  gcc/rust/typecheck/rust-type-util.cc
  gcc/rust/typecheck/rust-tyty-bounds.cc
  gcc/rust/typecheck/rust-tyty.cc
  gcc/testsuite/rust/execute/torture/issue-3126.rs
Labels: bug, typechecking

#3511 nr2.0: Fix test `self-path2.rs`
  gcc/rust/resolve/rust-ast-resolve-path.cc
  gcc/rust/resolve/rust-ast-resolve-type.cc
  gcc/testsuite/rust/compile/nr2/exclude
  gcc/testsuite/rust/compile/self-path2.rs
Labels: bug

#3512 nr2.0: Fix `StructExprFieldIdentifier` handling
  gcc/rust/resolve/rust-late-name-resolver-2.0.cc
  gcc/rust/resolve/rust-late-name-resolver-2.0.h
  gcc/testsuite/rust/compile/nr2/exclude
Labels: bug

#3522 gccrs: support generic super traits recursively
  gcc/rust/typecheck/rust-hir-path-probe.cc
  gcc/rust/typecheck/rust-hir-trait-reference.cc
  gcc/rust/typecheck/rust-hir-trait-reference.h
  gcc/rust/typecheck/rust-hir-trait-resolve.cc
  gcc/rust/typecheck/rust-tyty-bounds.cc
  gcc/rust/typecheck/rust-tyty-bounds.h
  gcc/rust/typecheck/rust-tyty-subst.cc
  gcc/rust/typecheck/rust-tyty-subst.h
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust/execute/torture/issue-3502.rs
Labels: bug, typechecking

#3504 ci: disable network
  .github/workflows/bootstrap.yml
  .github/workflows/ccpp.yml
Labels: CI

#3572 Fix core library test's canonical path
  gcc/testsuite/rust/compile/issue-2905-2.rs
Labels: name resolution

#3575 gccrs: Fix ICE when array elements are not a value
  gcc/rust/backend/rust-compile-expr.cc
  gcc/testsuite/rust/compile/issue-3567.rs
Labels: bug, codegen

#3578 gccrs: Add check for super traits being implemented by Self
  gcc/rust/typecheck/rust-hir-type-check-item.cc
  gcc/rust/typecheck/rust-tyty-bounds.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust/compile/issue-3553.rs
Labels: bug, typechecking

#3579 gccrs: Fix ICE when compiling block expressions in array capacity
  gcc/rust/backend/rust-compile-base.cc
  gcc/rust/backend/rust-compile-base.h
  gcc/rust/backend/rust-compile-type.cc
  gcc/testsuite/rust/compile/issue-3566-1.rs
  gcc/testsuite/rust/compile/issue-3566-2.rs
Labels: bug, constexpr

#3576 gccrs: Fix ICE when using super mid way though path
  gcc/rust/resolve/rust-ast-resolve-path.cc
  gcc/testsuite/rust/compile/issue-3568.rs
  gcc/testsuite/rust/compile/nr2/exclude
Labels: bug, name resolution

#3580 gccrs: Fix ICE when doing method resolution on trait predicates
  gcc/rust/typecheck/rust-hir-dot-operator.cc
  gcc/testsuite/rust/compile/issue-3554-1.rs
  gcc/testsuite/rust/compile/issue-3554-2.rs
Labels: bug, typechecking

#3601 gccrs: Fix ICE when compiling path which resolves to trait constant
  gcc/rust/backend/rust-compile-resolve-path.cc
  gcc/rust/hir/rust-hir-dump.cc
  gcc/testsuite/rust/compile/issue-3552.rs
Labels: codegen

#3602 gccrs: Fix ICE during const expr eval on array expressions
  gcc/rust/backend/rust-compile-context.h
  gcc/rust/backend/rust-compile-type.cc
  gcc/testsuite/rust/compile/issue-3588.rs
Labels: bug

#3619 gccrs: Fix ICE in array ref constexpr
  gcc/rust/backend/rust-constexpr.cc
  gcc/testsuite/rust/compile/issue-3563.rs
Labels: bug, constexpr

#3620 gccrs: FIX ICE when working with HIR::BareFunctionType
  gcc/rust/hir/rust-hir-dump.cc
  gcc/rust/hir/tree/rust-hir-type.cc
  gcc/testsuite/rust/compile/issue-3615.rs
Labels: bug, HIR

#3621 gccrs: FIX ICE for malformed repr attribute
  gcc/rust/typecheck/rust-hir-type-check-base.cc
  gcc/testsuite/rust/compile/issue-3614.rs
Labels: bug, typechecking

#3623 gccrs: fix ice when setting up regions
  gcc/rust/typecheck/rust-tyty-subst.h
  gcc/testsuite/rust/compile/issue-3605.rs
Labels: bug

#3622 gccrs: fix crash in parse repr options and missing delete call
  gcc/rust/typecheck/rust-hir-type-check-base.cc
  gcc/testsuite/rust/compile/issue-3606.rs
Labels: bug, HIR, typechecking
