Repository Rust-GCC/gccrs, pull requests merged in 2025-08, with the labels that each got.

#4017 gccrs: Add rest pattern support for AST::SlicePattern
  gcc/rust/ast/rust-ast-collector.cc
  gcc/rust/ast/rust-ast-collector.h
  gcc/rust/ast/rust-ast-full-decls.h
  gcc/rust/ast/rust-ast-visitor.cc
  gcc/rust/ast/rust-ast-visitor.h
  gcc/rust/ast/rust-pattern.cc
  gcc/rust/ast/rust-pattern.h
  gcc/rust/expand/rust-cfg-strip.cc
  gcc/rust/expand/rust-cfg-strip.h
  gcc/rust/expand/rust-derive.h
  gcc/rust/hir/rust-ast-lower-base.cc
  gcc/rust/hir/rust-ast-lower-base.h
  gcc/rust/hir/rust-ast-lower-pattern.cc
  gcc/rust/parse/rust-parse-impl.h
  gcc/rust/resolve/rust-ast-resolve-base.cc
  gcc/rust/resolve/rust-ast-resolve-base.h
  gcc/rust/resolve/rust-ast-resolve-pattern.cc
Labels: HIR, AST

#4033 gccrs: Ensure we track the const generic substitution on the param mappings
  gcc/rust/typecheck/rust-tyty-subst.cc
  gcc/rust/typecheck/rust-tyty.cc
Labels: const-generics

#4034 gccrs: Remove more calls to the old TyTy::BaseType::can_eq interface
  gcc/rust/typecheck/rust-autoderef.cc
  gcc/rust/typecheck/rust-coercion.cc
  gcc/rust/typecheck/rust-hir-inherent-impl-overlap.h
  gcc/rust/typecheck/rust-hir-path-probe.cc
  gcc/rust/typecheck/rust-hir-path-probe.h
  gcc/rust/typecheck/rust-hir-type-check-base.cc
  gcc/rust/typecheck/rust-hir-type-check-base.h
  gcc/rust/typecheck/rust-hir-type-check-expr.cc
  gcc/rust/typecheck/rust-hir-type-check.h
  gcc/rust/typecheck/rust-typecheck-context.cc
  gcc/rust/typecheck/rust-tyty-bounds.cc
  gcc/rust/typecheck/rust-tyty-subst.cc
  gcc/rust/typecheck/rust-tyty-subst.h
  gcc/rust/typecheck/rust-tyty.cc
  gcc/rust/typecheck/rust-tyty.h
  gcc/testsuite/rust/compile/generics8.rs
Labels: cleanup, typechecking

#4021 Add offset_of!() evaluation
  gcc/rust/backend/rust-compile-expr.cc
  gcc/rust/rust-backend.h
  gcc/rust/rust-gcc.cc
  gcc/testsuite/rust/execute/torture/offset_of1.rs
Labels: codegen

#4069 Replace old read-only checker with new one.
  gcc/rust/Make-lang.in
  gcc/rust/checks/errors/rust-readonly-check.cc
  gcc/rust/checks/errors/rust-readonly-check.h
  gcc/rust/checks/errors/rust-readonly-check2.cc
  gcc/rust/checks/errors/rust-readonly-check2.h
  gcc/rust/rust-session-manager.cc
Labels: diagnostic
